### ISSUE TITLE
Savoir ce qu'une salle déjà construite fait

### ISSUE THREAD

**Issue by jeremy-boes** [JulienNigon/SpellcasterUniversity-Bug-Report#101]
Parce qu'on oublie au bout d'un moment, on ne sait plus ce qu'on a déjà installé.

**Comment by JulienNigon** [comment]
Normalement il est possible de revoir l'effet des artefacts (pas des salles). Tu n'as jamais eu l'occasion de le voir ? (si non c'est que ce n'est pas assez intuitif)

**Comment by jeremy-boes** [comment]
Hmm, j'ai pas fait attention plus que ça pour les artefacts, il faudra que je retente.

**Comment by JulienNigon** [comment]
L'infobulle des artefacts a été améliorée et devrait pouvoir être utilisée de manière plus intuitive. Je passe l'issue sur le problème des salles.

**Comment by JulienNigon** [comment]
Une première solution pour la lecture d'effets des salles est en test. Je ferme pour l'instant. On réouvrira si ça ne convient pas aux testeurs.
