### ISSUE TITLE
plantage et fermeture du jeu

### ISSUE THREAD

**Issue by kaori01** [JulienNigon/SpellcasterUniversity-Bug-Report#1012]
Bonjour, 
Sur la carte des Yaks
Au moment de choisir l'orientation des élèves, après avoir validé l'un de destins, l'écran s'est totalement figé, plus aucune réponse, et finalement le jeu s'est totalement fermé de lui-même...

**Comment by Neelan22** [comment]
Ah mince... En reprenant la sauvegarde le jeu a bien voulu aller plus loin que les avenirs?

**Comment by kaori01** [comment]
oui sans problème, ça a repris tout à fait normalement à la sauvegarde précédente (ceci dit, un peu frileuse, j'ai passé la première série en automatique, puis j'ai recommencé à faire mes sélections manuellement sans aucun soucis non plus)

**Comment by Neelan22** [comment]
Ok. On n'a pas encore eu de retour concernant un avenir bugé, donc il y a peu de chance que ça vienne de là (d'autant que nous vérifions tous les avenirs avant de les ajouter). Je vais fermer l'issue en attendant plus d'information.
