### ISSUE TITLE
Récompense royaume

### ISSUE THREAD

**Issue by EclipseEternelle** [JulienNigon/SpellcasterUniversity-Bug-Report#1016]
Bonjour

Tout d'abord, j'aimerais vous dire que j'ai beaucoup apprécié votre jeu.
Il n'y a pas beaucoup de jeu sur des écoles de sorcellerie et une gestion par deck était une bonne idée.

Je pense cependant avoir rencontré un petit problème.
Avec le faction royaume, il est possible de tomber sur une quête où il faut retrouver un formulaire.
Si on choisit d'aider à chercher le formulaire, il y a une possibilité de réponse qui ne s'active que si on a un scriptorium runique. 
Or pour moi, cela ne fonctionne jamais. Je peux avoir plusieurs scriptoriums, le choix reste bloqué.

Bonne journée.

**Comment by Neelan22** [comment]
Bonjour et merci beaucoup pour ton soutien !
on note le bug #1017 #1004

**Comment by Neelan22** [comment]
corrigé pour la prochaine mise à jour :)
