### ISSUE TITLE
Kingdom faction: Runic scriptorum option not working

### ISSUE THREAD

**Issue by tanisdlj** [JulienNigon/SpellcasterUniversity-Bug-Report#1017]
When contacting the king, while having a Runic Scriptorum, when they complain about not finding some potions trade documents.
IF you have the scriptorum it does not allow you to tell them that you will make copies (Requisite: At least 1 Runic Scriptorum +15 reputation with Kingdom faction).

**Comment by Neelan22** [comment]
Hello Tanisdlj and thank you for your feedback, we will work on it ! #1016 #1004

**Comment by Neelan22** [comment]
Rectified for the next update :)
