### ISSUE TITLE
Bilan du trimestre

### ISSUE THREAD

**Issue by scpsc** [JulienNigon/SpellcasterUniversity-Bug-Report#1018]
Plutôt une question de logique qu'un bug : quand l'icône "bilan du trimestre" apparaît, on est immédiatement prélevé alors qu'il y a un timer qui s'écoule. Ca ne me paraît pas super intuitif : on s'attend plutôt à être prélevé à la fin du timer. Je ne sais pas si le moment du prélèvement a une importance mais si oui, l'icône pourrait apparaître plus tôt pour qu'il ait lieu à la fin du timer.

**Comment by Neelan22** [comment]
Il s'agit juste d'une information pour indiquer au joueur quelle quantité d'or a été prélevée à chaque trimestre.  Nous ne prévoyons pas changer ce mécanisme, mais nous pourrions peut être modifier l'affichage. Nous y réfléchirons !
