### ISSUE TITLE
Chasseur de prime

### ISSUE THREAD

**Issue by scpsc** [JulienNigon/SpellcasterUniversity-Bug-Report#1019]
L'avenir "Chasseur de prime" permet d'augmenter les gains de réputation auprès des mercenaires. Mon problème c'est que j'ai du mal à comprendre qui sont les mercenaires. Est-ce une faction présente sur une seule carte ?

**Comment by Neelan22** [comment]
Il s'agit des aventuriers, on va corriger ça, merci !
