### ISSUE TITLE
Impossible de vider le chaudron

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#1023]
0.93 Brave Explorer

Quand je clique sur la poubelle une fois le chaudron ouvert, le chaudron ne se vide pas :(

![image](https://user-images.githubusercontent.com/15092739/80752589-019b5380-8b2c-11ea-9687-0a1edfeb59ea.png)

**Comment by Neelan22** [comment]
C'est normal, la poubelle n'est pas faite pour ça. Il faut drag&drop la carte dans la poubelle.

**Comment by Fouindor** [comment]
Ah ben j'ai pas l'air bête. Merci ^^
![image](https://user-images.githubusercontent.com/15092739/81157521-581eec80-8f87-11ea-8c39-99878582ccab.png)
