### ISSUE TITLE
Suggestion for the diplomas

### ISSUE THREAD

**Issue by jeanfran2404** [JulienNigon/SpellcasterUniversity-Bug-Report#1030]
Bonjour,
Tout d'abord super jeu !
Je trouve toutefois la gestion des futurs un peu frustrante: si l'on veut viser des futurs précis, non seulement il est difficile de viser juste sans connaitre la cuisine derrière les pourcentages des différents futurs, mais surtout il est difficile d'orienter précisément les élèves vers des sous-écoles de magie précises. Par exemple, lors d'une run orientée nature, je souhaite concentrer mes élèves sur la nature (évidemment) mais aussi leur faire étudier la nécromancie car la synergie nature-nécromancie produit des métiers utiles à la nature entre autres (créateur de chimère, invocateur de verre de terre, druide de la peste). Seulement, soit j'essaye de n'obtenir que les salles en question dans le deck concerné mais il faut beaucoup de chance pour par exemple piocher la crypte tôt, soit je prends toutes les salles du deck pour accroître ma production de mana d'ombre et ainsi augmenter mes chances de tomber sur la crypte mais auquel cas mes élèves perdent du temps à étudier la démonologie ou l'assassinat.
Bref, à mon avis, la solution la plus simple serait sans doute de permettre d'autoriser ou de prioriser au sein des différentes écoles de magie des sous-écoles. A part cela je vois deux autres solutions mais qui me semblent moins intéressantes: (1) soit multiplier le nombre d'artefacts/décorations/reliques permettant d'enseigner une magie (tapisserie démoniaque etc...) mais auquel cas il faudrait sans doute accroitre la probabilité de tomber sur une salle en piochant dans un deck, sans cela on ne tomberait que sur des accessoires en nombre démultiplié ; (2) soit changer tout le système des futurs pour qu'il soit moins fondé sur la chance, mais cela rendrait peut-être les parties trop faciles.
Désolé pour ce long post et, encore une fois, tout mon soutien pour ce jeu !

**Comment by Neelan22** [comment]
Bonjour JeanFran2404, 
Merci pour tes retours. Pour le moment nous n'avons pas prévu d'aller en ce sens mais nous notons ta demande dans notre liste des réflexions. Je me permet donc de fermer cette issue.
Bonne journée !
