### ISSUE TITLE
imposibilité de finir une partie 

### ISSUE THREAD

**Issue by Yrisi** [JulienNigon/SpellcasterUniversity-Bug-Report#1034]
j'ai lacée une campagne hier et à la fin de la première école impossible de passer à la suite, de retourner au menu ou de quitter le jeu. 
j'ai réésayé aujourd'hui et là encore impossible de retourner au menu ou de quitter le jeu.

**Comment by Neelan22** [comment]
Bonjour Yrisi, désolée de lire ça...
Pourrais tu nous envoyer ta sauvegarde pour qu'on voit d'ou vient le souci stp?
Pour la trouver c'est :
PC : C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster University
Mac : ~/Library/Application Support/Sneaky Yak Studio/Spellcaster University/Saves
merci pour ton aide !

**Comment by Yrisi** [comment]
bonjourLe problème c’est que le jeux refusai de sauvegarder la partie également donc je ne peux pas vous evoyer la saveNavréBonne journée tout de mêmeYrisi  De : Neelan22Envoyé le :mardi 12 mai 2020 13:22À : JulienNigon/SpellcasterUniversity-Bug-ReportCc : Yrisi; AuthorObjet :Re: [JulienNigon/SpellcasterUniversity-Bug-Report] imposibilité de finir une partie (#1034) Bonjour Yrisi, désolée de lire ça...Pourrais tu nous envoyer ta sauvegarde pour qu'on voit d'ou vient le souci stp?Pour la trouver c'est :PC : C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster UniversityMac : ~/Library/Application Support/Sneaky Yak Studio/Spellcaster University/Savesmerci pour ton aide !—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Yrisi** [comment]
Bonjour Je viens de retenter de faire une campagne et les sauvegardes et retour au menu fonctionnentJe suppose que la dernière mise à jour était mal passéeMerci pour votre retour Yrisi De : Neelan22Envoyé le :mardi 12 mai 2020 13:22À : JulienNigon/SpellcasterUniversity-Bug-ReportCc : Yrisi; AuthorObjet :Re: [JulienNigon/SpellcasterUniversity-Bug-Report] imposibilité de finir une partie (#1034) Bonjour Yrisi, désolée de lire ça...Pourrais tu nous envoyer ta sauvegarde pour qu'on voit d'ou vient le souci stp?Pour la trouver c'est :PC : C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster UniversityMac : ~/Library/Application Support/Sneaky Yak Studio/Spellcaster University/Savesmerci pour ton aide !—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Neelan22** [comment]
ok !
Tant pieux si le problème est passé :)
