### ISSUE TITLE
Bug: Recette de potion

### ISSUE THREAD

**Issue by Hykus1605** [JulienNigon/SpellcasterUniversity-Bug-Report#1035]
Bonjour,
J'ai rencontré un bug, lorsque je craft une potion avec l'ingrédient "âme de dormeur" la recette qui s'affiche après l'avoir crafter ne comporte pas l'"âme de dormeur" mais un autre ingrédient souvent "racine de mandragore" mais aussi parfois "fromage". 
Je rencontre systématiquement ce bug (plusieurs session de jeu et même plusieurs campagne )

En vous remerciant pour votre travail sur ce jeu que j'apprécie beaucoup

**Comment by MlleMau** [comment]
Bonjour Hykus1605,

En vérité, c'est tout à fait normal ! Si tu lis la description de l'item, l'âme de dormeur est en vérité un élément aléatoire, qui prend n'importe quelle forme. Tu ne sais donc jamais quelle potion tu auras avec cet élément !

Bon jeu à toi,
Maureen.

**Comment by Neelan22** [comment]
merci pour la réponse MlleMau ;)
