### ISSUE TITLE
Je ne sais pas si c'est un bug mais...

### ISSUE THREAD

**Issue by Scordralion** [JulienNigon/SpellcasterUniversity-Bug-Report#1038]
Bon voilà, alors c'est dérangeant dans toutes les campagnes, que l'on soit spécialisés et qu'on tente de faire des archimages ou alors qu'on ait une universités gigantesque... Pourquoi les élèves continuent-ils d'étudier une branche alors qu'ils sont déjà niveau 5 (et que grosso modo ils savent tout sur le sujet ?)... C'est très frustrant de voir un élève brillant étudier une branche qu'il maîtrise déjà et être mauvais dans tous les autres domaines...

**Comment by Neelan22** [comment]
En fait nous ne voulions pas pénaliser le joueur car les bons élèves génèrent beaucoup de mana. Mais nous en avons discuté avec des joueurs et entre nous et nous pensons modifier ça en faisant que les élèves n'aillent plus étudier dans les salles où ils sont niveau 5 (mais il pourront toujours généré du mana avec des artefact ou à la bibliothèque par exemple)

**Comment by Scordralion** [comment]
Haaaaa, excellente nouvelle, merci bien !
