### ISSUE TITLE
Progression des niveaux de salles

### ISSUE THREAD

**Issue by Scordralion** [JulienNigon/SpellcasterUniversity-Bug-Report#1039]
je sais que je ne suis pas le premier à soulever le sujet mais je me permets de relancer la chose pour avoir une réponse; Pourrait-on, in game, connaître les bonus apportés par l'augmentation du niveau d'une salle, de façon chiffrée car au final, on ne sait pas vraiment ce qui est le plus rentable entre améliorer une salle ou prendre un artefact ou autre. Par la même, il serait pratique de pouvoir interagir avec les stats, les classes et le jeu en général quand on fait un choix de cartes/de maison ou autre ^^

**Comment by Neelan22** [comment]
On est en train de préparer tout ça pour la prochaine mise à jour :)
patience !
