### ISSUE TITLE
Salle en feu et professeur serein

### ISSUE THREAD

**Issue by AuretteW** [JulienNigon/SpellcasterUniversity-Bug-Report#1040]
Bonsoir,
je ne sais pas si ce bug a déjà été rapporté : quand une salle de classe prend feu, le professeur continue à faire cours comme si de rien n'était. Il faut que ce soit un autre professeur qui vienne et éteigne le feu.
J'ai essayé de faire une sauvegarde à un moment où ça se produit, j'espère qu'elle présente bien le bug.
[save.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/4612214/save.zip)

**Comment by Neelan22** [comment]
Ce n'est pas un bug, c'est comme ça que nous avons programmé les IA des professeurs. Elles méritent d'être affinées, mais cela prend du temps ^^
