### ISSUE TITLE
Défauts sur des métiers

### ISSUE THREAD

**Issue by AuretteW** [JulienNigon/SpellcasterUniversity-Bug-Report#1041]
Bonsoir,
- métier démoniste . Dans les prérequis, il est indiqué que les traits "brute" et "mauvais" sont requis, or une de mes élèves qui n'avait pas ces traits est devenue démoniste (Nina Rolandus dans la sauvegarde, on évalue son diplôme en 16ème avant la fin, si l'ordre n'est pas aléatoire). Il est possible que ses traits aient changé pendant la partie ; est-ce que ce sont les traits de départ ou les traits modifiés qui comptent ?
- métier jardinier : le texte de description du métier dit "grâce à son attention en cours d'herborisme", alors que la condition réelle du métier est "druidisme niv. 2"
- planteur d'herbes hallucinogènes (bravo pour cette inventivité ! :D) : les prérequis indiquent que le trait "comique" est requis, mais j'ai un élève "non comique" qui a eu ce métier

Sinon, hors sujet : MERCI pour ce jeu, il est SUPER ! :)

[save.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/4612224/save.zip)

**Comment by Neelan22** [comment]
Normalement, ce sont les traits qu'a l'élève au moment où il reçoit son diplôme qui compte dans le choix des avenirs.
On va aller voir si il n'y a pas un bug sous tout ça.
Merci pour ton soutien et ton aide !

**Comment by Neelan22** [comment]
Ah, je pense à un truc : 
pour le métier planteur d'herbes hallu, le trait comique n'est pas un prérequis c'est un trait qui favorise cet avenir : comprendre par là que l'avenir a une plus grande probabilité d'être sélectionné (10%).
Pour démoniste, je n'ai rien de noté dans ma fiche de donnée qui pourrait pondérer cet avenir, mais ça a peut etre été ajouté après, on va quand même regarder. Pour info, il y très peu de métiers (3 ou 4 je crois) où un trait spécifique est obligatoire pour l'obtenir (le trait amorphe pour devenir Zombie par ex)

**Comment by AuretteW** [comment]
Oh, c'est moi qui avais mal compris, alors. Ce sont des modificateurs de probabilité, et non des pré-requis.
Désolée, et merci pour ces explications.
