### ISSUE TITLE
Choix grisé quand conditions remplies

### ISSUE THREAD

**Issue by Myu-Wynn** [JulienNigon/SpellcasterUniversity-Bug-Report#1043]
Bonsoir,

J'ai rencontré le problème en cherchant à aider le Roi au cours de l'événement "Problème Administratif". Je possédais un Scriptorium runique, mais impossible de choisir la dernière option pour augmenter la réputation de 15 auprès de lui.

![20200511234522_1](https://user-images.githubusercontent.com/65197571/81617336-8bc5a080-93e5-11ea-998f-1ef8cb74a82c.jpg)

**Comment by Neelan22** [comment]
Oui, c'est un bug qu'on doit corriger, merci !
#974 #1004 #1016 #1017

**Comment by Myu-Wynn** [comment]
D'accord merci, désolée s'il avait déjà été remonté !
