### ISSUE TITLE
problèmes de sauvegardes 

### ISSUE THREAD

**Issue by Yrisi** [JulienNigon/SpellcasterUniversity-Bug-Report#1050]
après quelques temps sur une partie le jeux ne parvient pas à la sauvegarder ce qui empêche toute sauvegarde (logique), toute fin de partie, retour au menu et fermeture du jeux

**Comment by Neelan22** [comment]
même la sauvegarde automatique est touchée?

**Comment by Yrisi** [comment]
C’est justement la sauvegarde auto que semble touchée car lorsque je souhaite quitter ça affiche le cygle de la sauvegarde automatique en boucle et ça refuse de quitter la partie  De : Neelan22Envoyé le :vendredi 29 mai 2020 17:24À : JulienNigon/SpellcasterUniversity-Bug-ReportCc : Yrisi; AuthorObjet :Re: [JulienNigon/SpellcasterUniversity-Bug-Report] problèmes de sauvegardes (#1050) même la sauvegarde automatique est touchée?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Yrisi** [comment]
bonjourJe vient de réessayer et cela fonctionne je pense que la mise à jour précédente était mal passée et que la nouvelle à « corrigé » mon problème Désolé du dérangement Yrisi De : Neelan22Envoyé le :vendredi 29 mai 2020 17:24À : JulienNigon/SpellcasterUniversity-Bug-ReportCc : Yrisi; AuthorObjet :Re: [JulienNigon/SpellcasterUniversity-Bug-Report] problèmes de sauvegardes (#1050) même la sauvegarde automatique est touchée?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Neelan22** [comment]
super !
