### ISSUE TITLE
Impossible de continuer la campagne quand on a gagné

### ISSUE THREAD

**Issue by Bykozor** [JulienNigon/SpellcasterUniversity-Bug-Report#1052]
Je m'explique: J'ai remplis toutes les étapes de préparation du plan d'attaque, même les quêtes secondaires (étoiles), le bouton "terminer la campagne" apparaît, et.... impossible de cliquer dessus ! Les animations en arrière plan se déclenchent bien (élèves et professeurs qui fuient l'île). J'ai tout essayé, même d'attendre jusqu'a la fin mais rien ne se passe. Alors j'ai sauvegardé, je suis revenue dessus, et, normal, le jeu m'annonce que j'ai perdu car le temps est écoulé... Snif!

Ca ne me le faisait pas avant la dernière mise à jour.

**Comment by GreBarbe** [comment]
Même bug chez moi. 
J'ai eu l'impression qu'un professeur était coincé entre deux salles sur l'animation de fuite. Et quand on recharge la sauvegarde temps écoulé donc défaite malgré les conditions de victoires remplies

C'est un peu frustrant :)
(cela dit bravo pour la maj qui est top en terme de contenu)

**Comment by Neelan22** [comment]
humm, c'est bien embêtant tout ça :(
On va regarder ça, merci pour les retours.

**Comment by Neelan22** [comment]
vous auriez encore la sauvegarde?

**Comment by Bykozor** [comment]
Oui, je l'ai encore, mais je n'arrive pas à la retrouver dans les fichiers du jeu, je veux bien vous la transmettre mais il faudra me dire comment.

**Comment by Neelan22** [comment]
Ah oui, j'ai oublié de préciser, désolée.
Pour trouver la sauvegarde c'est :
PC : C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster University
Mac : ~/Library/Application Support/Sneaky Yak Studio/Spellcaster University/Saves

Merci pour ton aide

**Comment by Neelan22** [comment]
Nous avons identifié le pb, il sera corrigé pour la prochaine mise à jour, merci pour votre aide !
pour info : le jeu buggait si aucun n'objectif n'était validé :)
