### ISSUE TITLE
Campagne perdue alors que gagnée ! 

### ISSUE THREAD

**Issue by HermelineRosewood** [JulienNigon/SpellcasterUniversity-Bug-Report#1054]
Bonjour, 

J'ai achevé toutes les étapes de la quête du niveau final (tout juste mais dans les temps), le bouton "finir la campagne" s'affiche mais rien ne se passe lorsque je clique dessus... Je sauvegarde donc avant de revenir sur le menu du jeu. Je charge ma partie tout juste gagnée, le bouton "finir la partie" s'affiche et lorsque je clique dessus, le jeu m'annonce que j'ai perdu...

Bonne journée.

**Comment by ThibaultUrien** [comment]
J'ai aussi eu un bug similaire : la mission final été fini mais le bouton faisait rien. J'ai aussi essayer de sauvegarder, quitter et recharger, mais moi en chargeant, la mission final a repris son cours, (alors que tout le monde avait évacué après la validation de la dernière étape). Par contre il n'était plus possible d'interagir avec le crane et j'ai perdu au temps.

**Comment by Neelan22** [comment]
désolée pour ce vilain bug :(
est ce que vous auriez encore la sauvegarde d'avant la fin? 
#1052

**Comment by ThibaultUrien** [comment]
Je pense que je l'ai encore. Par contre je n'ai aucune idée de l'endroit où trouver le fichier.

**Comment by Neelan22** [comment]
Ah oui, j'ai oublié de préciser, désolée.
Pour trouver la sauvegarde c'est :
PC : C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster University
Mac : ~/Library/Application Support/Sneaky Yak Studio/Spellcaster University/Saves

Merci pour ton aide !

**Comment by Neelan22** [comment]
Nous avons identifié le pb, il sera corrigé pour la prochaine mise à jour, merci pour votre aide !
pour info : le jeu buggait si aucun n'objectif n'était validé :)

**Comment by ThibaultUrien** [comment]
J'avais validé les trois objectifs et j'ai quand même eu le problème. Du coup à tout hasard je met la sauvegarde quand même. 
[save.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/4759896/save.zip)

**Comment by Neelan22** [comment]
Le problème est bien réglé, j'avais mal compris les explications du dev : ça arrive systématiquement si la partie n'est pas en mode défi. Nous ferons un fix sous peu. Merci pour la sauvegarde et ton aide !
