### ISSUE TITLE
Pas (encore) de problème mais des remerciements ^^

### ISSUE THREAD

**Issue by Scordralion** [JulienNigon/SpellcasterUniversity-Bug-Report#1059]
la nouvelle mise à jour est d'enfer !!! Enfin des détails sur le niveau des salles (depuis le temps qu'on les demandent) et chacune des salles de classes ont des effets personnalisés, c'est génial ! Merci beaucoup, ça ajoute énormément au jeu et les défis donnent envie de refaire la campagne avec un challenge :D

**Comment by Neelan22** [comment]
merci beaucoup <3
