### ISSUE TITLE
Plusieurs soucis

### ISSUE THREAD

**Issue by carolinebach** [JulienNigon/SpellcasterUniversity-Bug-Report#1065]
Le belvédère est impossible à placer, j'ai 50 parties à mon actif, ça marche jamais. Ma dernière partie, j'ai validé tous les objectifs et ai quand même eu la fin game over à ma campagne. Il a été impossible de cliquer sur le bouton finir la partie, j'ai donc sauvegardé et quitté, en revenant le bouton finir n'était plus disponible et quand les forces du mal ont fini par arriver j'ai eu le game over alors que je devais avoir l'ecran de victoire. Les durées de campagnes autre que le rythme normal sont juste impossible à gagner. l'ensemble reste très dur, il m'a fallu 40 parties pour finir une partie acolyte en victoire. L'archimage est impossible à faire même en mode très facile

**Comment by Neelan22** [comment]
Voici les conditions pour poser un belvédère : 
![image](https://user-images.githubusercontent.com/47151033/84127230-45447f80-aa3f-11ea-9acf-eed4e7fdbd20.png)
Nous sommes conscient du travail d'équilibrage qui nous attend, mais tant que tout le contenu ne sera pas présent, ce ne serait pas efficace de commencer à y travailler dessus maintenant. nous avons quand même des joueurs acharnés qui maîtrisent toutes les difficultés :)
Merci pour les retours de bug !

**Comment by Neelan22** [comment]
Il y a visiblement un bug en fin de partie, nous avant plusieurs retours concernant ce bouton de fin de jeu impossible à valider. As tu une sauvegarde? Te souviens tu des quêtes que tu as validé pour atteindre la fin?
edit : le bug de fin de partie vient d'être identifié et sera corrigé pour la prochaine mise à jour :)
