### ISSUE TITLE
I can't play any cards

### ISSUE THREAD

**Issue by calamityson** [JulienNigon/SpellcasterUniversity-Bug-Report#1066]
Hey,

since the brave explorer update I wasn't able to play cards anymore. I can buy them, the events trigger and when i go on the cards they get bigger to read but I can not swipe nor click them to play. they just stay in the bar. No rooms, no students, no game.

**Comment by Neelan22** [comment]
well, s*** !
Did you try to uninstall then re install the game? What are your configs? Does reloading a game help? You are the first one reporting us such a bug :/
Very sorry for this
NB : Before you do any of that, did you remember to set your game camera close to ground level? (this way, the playing air is in the upper part of the screen) Cards can't be played in the lower part of the screen.

**Comment by calamityson** [comment]
You were right, changing the screensettings helped a bit. I have problems with the fullscreen. Now I can grab the card, but it will stuck in the air. It works in windowed screen, even when half the cardsbar is out of sight. There the rooms appear/cards work just have to do it very slow and carefully.  Which configurations do you need?

**Comment by calamityson** [comment]
Now I can play with every screensetting. The error appeard once again when I started the game with buying cards and my bar was full but reloading solved this problem. I have to move the cards straight upwards first otherwise they will switch back to the bar. When I move a room on the side of the screen it will be placed even when I'm still holding the mouse down.

**Comment by calamityson** [comment]
When continuing playing the switching back error gets worse. I have to go up in 90 degree first or the card is back in the bar. 
And a new error appeared: the card dissapears in the bar and the blue-where-to-built-room appears but the room can't be placed and nothing else can be clicked. I can redo that by pressing windows and open the game again, then the card is back in the bar and i can start a new try.

**Comment by Neelan22** [comment]
The minimal config must be :
OS : Windows 7 or more recent
Processor : Intel i3-2100 / AMD A8-5600k
RAM : 4 GB de mémoire
Graphics : GeForce GTX 630 / Radeon HD 6570

The bug seems to be related to a config problem, did you try to reinstall the game?

**Comment by calamityson** [comment]
OS: Windows 10
Processor: Intel i7-4510U
RAM: 8GB
Graphics: GeForce 840 M

By now the proble resolved somehow, i didnt play for a month and now i can play fluently. Sometimes cards get stuck, like every 2 -3 hours but it doesnt stop the playflow anymore.

**Comment by Neelan22** [comment]
Ok, nice to read that. We stay aware about the game optimisation
