### ISSUE TITLE
La case de priorité ( Arcane )

### ISSUE THREAD

**Issue by Astral-7** [JulienNigon/SpellcasterUniversity-Bug-Report#1074]
Bonjour

Lorsque je veux choisir le niveau de priorité de la magie Arcannique elle est mise en Interdit & l'un des deux autres ...
Lorsqu’on clique sur interdit puis sur un autre statut le problème est réglé, mais sa le fais à chaque fois que j'ouvre la fenêtre des priorités

En espérant que cela vous soit utile

**Comment by Neelan22** [comment]
oh, ok. On va regarder ça, merci pour le retour

**Comment by Karscorps** [comment]
![image](https://user-images.githubusercontent.com/67207076/85211416-4c299700-b349-11ea-97ec-9d30560b6d0f.png)

J'ai le même problème, ça se met dès qu'on regarde les prio du coup je ne sais pas trop comment réagissent les étudiants :(

**Comment by Kpriss** [comment]
Même problème pour moi aussi.

**Comment by Neelan22** [comment]
problème corrigé pour la prochaine mise à jour :)
