### ISSUE TITLE
Door did not create a path 

### ISSUE THREAD

**Issue by Starexplorer** [JulienNigon/SpellcasterUniversity-Bug-Report#1076]
So I think at least, that a Guinea Pig tower is supposed to connect to a dormitory, but in my save it did not so I guess it had a bad day :D The towers outline looked strange too, so I decided to report it. 
![image](https://user-images.githubusercontent.com/67241871/85234469-4352c700-b416-11ea-8c5e-f348049fb37c.png)
![image](https://user-images.githubusercontent.com/67241871/85234476-4fd71f80-b416-11ea-953b-750aa5c14199.png)

**Comment by Neelan22** [comment]
The only access to a guinea pig tower is by the back door, who is linked to the castle by the bottom room.
This is ok to see a wall in front of your door, such a build close the way. We will add featurs like a closed door to clear up any confusion
