### ISSUE TITLE
Bug d'objectif

### ISSUE THREAD

**Issue by Scordralion** [JulienNigon/SpellcasterUniversity-Bug-Report#1099]
Outre l'objectif classique, j'avais les objectifs guerriers de la horde et Archimage, c'est la classe ! J'ai sauvegardé et quitté alors que je n'avais aucun des deux objectifs rempli. Je reviens et l'objectif d'archimage est compté comme rempli ("tant mieux" de toute façon j'en ai plusieurs par la suite) par contre, bien que j'aie atteint 100 de réputation avec orcs, leur objectif ne s'est pas rempli... :'(

**Comment by Neelan22** [comment]
oui, on a un bug avec les quêtes. Les quêtes de relations sont "oubliées", elles sont donc à revalider si la réputation est descendue, et à l'inverse, les autres quêtes se valident automatiquement ^^

**Comment by Neelan22** [comment]
corrigé pour la prochaine MaJ
