### ISSUE TITLE
Arcana stuck on prohibited.

### ISSUE THREAD

**Issue by IAmFurai** [JulienNigon/SpellcasterUniversity-Bug-Report#1100]
Encountered a bug a few hours in, on both campaign and normal mode, where Arcana just sets itself to prohibited, no matter what. Every time I closed and reopened the window, it was back on prohibited. I tried restarting new games, but it is still bugged. 

Thank you!

**Comment by Neelan22** [comment]
It's only visual, your choice in taken into account. This bug is actually solved and will be corrected in the next update :)

**Comment by IAmFurai** [comment]
Oh, thank you so much!

Have a great day
