### ISSUE TITLE
Sauvegarde automatique

### ISSUE THREAD

**Issue by KesneyTorras** [JulienNigon/SpellcasterUniversity-Bug-Report#1111]
Bonjour,

J'ai remarqué que je ne pouvais pas remonter dans le temps... En effet, si je quitte une partie pour effacer une mauvaise manip, mon jeu reprend exactement où je l'ai quitté, même si je n'avais pas sauvé au préalable.

Bien à vous
KT

**Comment by Neelan22** [comment]
Nous avons mis en place des sauvegardes automatiques régulières. C'est pour éviter que les joueurs "recommencent" une partie jusqu'à avoir les cartes qui leur plaisent.
Nous comptons améliorer l'UI pour éviter des mauvaises manips maladroites
