### ISSUE TITLE
Toile d'araignée

### ISSUE THREAD

**Issue by Jieffff** [JulienNigon/SpellcasterUniversity-Bug-Report#1112]
La toile d'araignée que l'on débloque en terminant le défi de célérité (carte ombre, les personnages actifs dans cette pièce génèrent la ressource la plus basse) génère également du prestige (environ 1 par seconde), je pense pas que ce soit voulu.

**Comment by KrabbaTester** [comment]
L'objet s'appelle "Araignée Tisse-Ombre"
J'ai remarqué le même problème et cela déséquilibre complètement le jeu.

**Comment by Neelan22** [comment]
corrigé dans la dernière mise à jour, désolée pour le délais de réponse
Merci pour vos retours !
