### ISSUE TITLE
Crash intempestif [save dispo]

### ISSUE THREAD

**Issue by Tioy0** [JulienNigon/SpellcasterUniversity-Bug-Report#1122]
Crash durant la campagne, comme mentionné dans un précédent post, il y a possibilité de recharger la partie, de progresser un peu (et même de sauvegarder) mais crash inévitable au bout de quelques minutes. J'ai désinstaller/réinstaller le jeu sans succès
Jeu très sympa soit dit en passant !

[save.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/5176335/save.zip)

**Comment by CherryWingNLR** [comment]
Après, ça dépend des conditions. Tu devrais précisé. Moi par exemple, j'ai eu ce bug sur la carte des marais, mais seulement quand j'ai joué la malédiction des aberration.

En tout cas, je suis obligé d'attendre la prochaine mise à jour, quand elle arrivera, pour continuer ma partie

**Comment by Neelan22** [comment]
merci pour la sauvegarde et désolée pour ta partie :/

**Comment by Neelan22** [comment]
CherryWingNLR, ton bug est toujours d'actualité?

**Comment by Neelan22** [comment]
on pense avoir corrigé le pb avec le hotfix d'hier (la coupable était la boule de cristal). Merci pour la sauvegarde, ça nous a bien aidé.
