### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by kaori01** [JulienNigon/SpellcasterUniversity-Bug-Report#1124]
tout est dans le titre... le jeu s'est figé... J'étais en train de piocher une carte pour faire une potion.

**Comment by Neelan22** [comment]
Je reviens après une longue période d'absence...
Si ce genre de chose se reproduit, je suis intéressée pour récupérer la dernière auto save du jeu. 
les saves sont là : 

PC : C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster University
Mac : ~/Library/Application Support/Sneaky Yak Studio/Spellcaster University/Saves

merci pour ton aide !

**Comment by kaori01** [comment]
Bonsoir,
Pour le moment le fait ne s'est pas reproduit... mais je note !
Bien à vous,
Karine

**Comment by kaori01** [comment]
Bonjour, cela vient de se reproduire (au moment où je cliquais sur le petit
cochon d'inde pour ouvrir la carte), je vous met la sauvegarde!
Bonne journée!
Karine

**Comment by Neelan22** [comment]
il faut un .zip à glisser dans l'espace de texte stp.

**Comment by kaori01** [comment]
c'est que...depuis... j'ai fini la campagne en question... c'est
récupérable quelque part?

**Comment by Neelan22** [comment]
non, la sauvegarde a été écrasée depuis. C'est pas grave. C'est juste qu'avec la tournure de ta phrase, je pensais qu'il manquait la sauvegarde jointe.

**Comment by kaori01** [comment]
elle est en pièce jointe dans ma première réponse :)

**Comment by Neelan22** [comment]
est ce que tu peux la récupérer et la glisser dans l'encart de texte sur le site github stp? Github n'envoie pas les pièces jointes par mails, il faut passer par le site pour l'envoi de fichiers.

**Comment by kaori01** [comment]
je tente (je l'ai aussi mis sur mon drive et lancé une invitation pour que
vous y accédiez)

**Comment by Neelan22** [comment]
tu peux mettre le lien du drive ici?

**Comment by kaori01** [comment]
https://drive.google.com/file/d/1Jqdt5lEp3O5NyFeZY1vSCwGHfHRn2UBR/view?usp=sharing

**Comment by Neelan22** [comment]
merci

**Comment by Neelan22** [comment]
je n'ai pas eu de problème dans mon test. On a peut être corrigé le problème avec le hotfix d'hier.
Merci pour ton aide.
