### ISSUE TITLE
Des crash à répétition depuis la mise à jour rendent le jeu injouable

### ISSUE THREAD

**Issue by Alleria86** [JulienNigon/SpellcasterUniversity-Bug-Report#1125]
Des freeze et crash apparaissent constamment depuis la dernière mise à jour, avec une fréquence telle qu'il est devenu impossible de progresser dans la campagne. 

Auparavant, le jeu plantait régulièrement, mais rien de trop alarmant pour un jeu en early access. 

Mais depuis la MAJ, mes deux sauvegardes en mode campagne sont foutues (une sur la carte du volcan en 5ème ou 6ème mission, une sur la carte du lac en 3ème ou 4ème mission) : à peine quelques minutes après avoir lancé, le jeu freeze et il n'y a plus qu'à relancer. J'ai essayé la stratégie consistant à sauvegarder toutes les 3 minutes pour essayer de ne pas perdre ma progression et quand même avancer, mais au bout d'un moment les crash font de plus en plus fréquent, tellement qu'on ne peut même plus jouer 1 saison entière ! Et donc sauvegarder ne sert plus à rien.

Je me suis dit bon, il doit y avoir une incompatibilité avec les anciennes sauvegardes, c'est triste mais tant pis. Donc j'ai lancé de nouvelles campagne. La première map (qu'on prenne le lac, la ville ou le village), ça fonctionne nickel... Mais dès la deuxième map les crash constants se repointent. Sur ma dernière campagne, j'en suis juste à la 2ème map, j'ai pris la forêt, et c'est devenu injouable (c'est à dire que je ne peux plus passer 1 saison avant d'avoir un crash) environ à la moitié de la progression du seigneur du mal.

Dommage, le jeu est vraiment sympa, mais en fait ce n'est même plus possible d'y jouer...

**Comment by Neelan22** [comment]
Je suis désolée de lire ça...
Nous allons bientôt mettre en ligne une nouvelle mise à jour. J'espère que ça corrigera tes bugs. 
Je peux quand même regarder de mon coté si tu m'envoies une sauvegarde.
Tu peux la trouver ici : 
PC : C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster University
Mac : ~/Library/Application Support/Sneaky Yak Studio/Spellcaster University/Saves

Merci pour ton retour

**Comment by Alleria86** [comment]
J'ai deux saves dispos que je te mets en pièce jointe. J'avais bien plus de campagnes mais j'ai fini par les supprimer de désespoir. En espérant que ça vous aide !.
[Ecole des blaireaux.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/5467278/Ecole.des.blaireaux.zip)

[Bis Repetita.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/5467277/Bis.Repetita.zip)

**Comment by Neelan22** [comment]
merci !

**Comment by Neelan22** [comment]
on a trouvé le pb et fait un hot fix hier. Merci pour tes sauvegardes, elles nous ont bien aidé.
