### ISSUE TITLE
Ingrédients pour les potions

### ISSUE THREAD

**Issue by link34200** [JulienNigon/SpellcasterUniversity-Bug-Report#1131]
Bonjour,

Je ne sais pas si c'est normal mais concernant les ingrédients des potions, il y a quelque chose de bizarre pour les obtenir si on ne prend pas en compte l'item qui en donne de manière random : 
- les cornes peuvent s'obtenir par un objet ET dans la serre améliorée
- les plumes ne peuvent pas s'obtenir automatiquement via la serre ou un objet
de fait il y a une dizaine de recette (celle contenant une plume) qui sont beaucoup plus difficilement obtenable que les autres.
Je suppose que c'est une erreur et que la serre devrait donner les plumes car l'item a sa propre image alors que l'amélioration de serre n'est que du texte à modifier.
Merci d'avoir créé ce jeu super sympa.

Olivier

**Comment by Neelan22** [comment]
Merci pour ce retour link34200.
Il s'agit tout simplement d'un manque de contenu qui va arriver d'ici la sortie définitive. Il est vrai qu'à l'heure actuelle, les plumes sont difficiles à obtenir, mais ça ne durera pas !
