### ISSUE TITLE
l'araignée tisse ombre tisse surtout du prestige

### ISSUE THREAD

**Issue by potir0n** [JulienNigon/SpellcasterUniversity-Bug-Report#1133]
bonjour!
après deux manches où mon prestige s'est envolé ( > 400 ) , j ai enfin compris: l'araignée ( installée dans le réfectoire ) génère de l'or jusque à ce que j'ai plus d'or que de prestige, et ensuite génère du prestige ( à une vitesse folle! )
alors que , si j'ai bien compris le descriptif, elle devrait générer du mana!
( d'ailleurs, le niveau de mana n'a pas l'air d'influencer, et sur ma partie elle n'en produit pas à priori! )

Bonne journée!

**Comment by RavingStory** [comment]
J'allais justement signaler la même chose, ce n'est pas un bug isolé. L'araignée fait grimper le prestige en flèche. Perso, je me suis retrouvé à plus de 1000 en quelques minutes.

**Comment by Neelan22** [comment]
merci pour l'info !

**Comment by Neelan22** [comment]
corrigé pour la prochaine mise à jour 👍
