### ISSUE TITLE
Gros Phoenix ?

### ISSUE THREAD

**Issue by Tioy0** [JulienNigon/SpellcasterUniversity-Bug-Report#1136]
Tout est dans le titre, j'avais poster un message sur Steam pour savoir si la carte était buggée, je la récupère seulement via l'avenir "Dresseur d'Animaux Fantastiques". Est-ce voulu ? La carte ne m'apparait pas suffisamment forte pour mériter ça, et en même temps la rajouter dans le deck lumière (en référence à sa couleur) est pas forcément utile.

**Comment by Neelan22** [comment]
Je ferme l'issue parce que ce n'est pas vraiment un bug, c'est juste qu'il y a un moyen d'obtenir cette carte maintenant alors qu'on ne l'a encore vraiment mise en jeu. D'ailleurs je ne sais même pas si son effet marche. Je pensais avoir répondu à cette remarque (je ne sais plus sur quelle plateforme). Merci de l'avoir signalé ;)
