### ISSUE TITLE
Dragon féérique dans la quête du Lac

### ISSUE THREAD

**Issue by PLG35** [JulienNigon/SpellcasterUniversity-Bug-Report#1143]
Sur la carte du lac, le monstre aquatique nous propose plusieurs quête successive.
L'une d'entre elles consiste à posséder des dragons de quatre type différents.

J'avais trois dragons de couleurs (bleu, violet et vert il me semble) et un dragon féérique.
Je ne pouvais pas valider la quête.
C'est seulement lorsque j'ai eu un dragon noir en plus de ceux précédemment mentionnés que j'ai pu valider la quête.
Je soupçonne que le dragon féérique ne soit pas compté comme un type de dragon à part entière dans cette quête. Cela ne me semble pas cohérent avec le nom qu'il porte.

**Comment by Neelan22** [comment]
effectivement, on va changer ça pour la prochaine mise à jour (c'est un oubli). On va l'ajouter à la quete.
