### ISSUE TITLE
Bug : durée infinie?

### ISSUE THREAD

**Issue by M1rar1** [JulienNigon/SpellcasterUniversity-Bug-Report#1145]
Bonjour,
Je viens de trouver un méthode qui fait reculer le mal plus vite qu'il n'avance basée sur les items "Signe très ancien" et "l'arc elfique". C'est valable sur n'importe quel map si on tire les bonnes cartes

Je joue sur la carte village et j'ai supprimé le malus du ménestrel avec le molosse et les 2 prisons.

J'ai placé l'arc elfique dans l'entrée pour que le bonus s'applique à tous les nouveaux élèves.
J'ai une salle des démons et une salle dimensionnelle lvl 3.
Ainsi que 2 cochoniers lvl 5 boostés par le scriptorum (et le bonus de 30% sur l'étage).
Avec une école spécialisée en ombre et arcane. J'y place la majorité des élèves qui valident assez vite la condition du "signe des anciens"
A chaque fin d'année le recul est énorme (avec les diplômés) et comme avec les cochoniers la faction orc m'aide à faire reculer l'avancée du seigneur des ténèbres (elle n'avance pas beaucoup au cours de l'année).

En 3 années, je suis passé de +/- 60% à +/- 20%.

Avec 200 de réputations, les nouveaux élèves se succèdent. Les profonds amplifient la diminution.

En continuant comme ça, il devrait être possible de le garder à 0.
Je n'en suis encore qu'à ma 10ème année, je n'ai pas encore poussé jusqu'à 0% mais parti comme ça. 
Ca devrait être possible

**Comment by Neelan22** [comment]
Oui on a rééquilibrage à faire de ce coté là. Il est techniquement impossible de repousser le mal à l'infinie, nous nous en sommes bien assurés, mais la limite est encore trop haute. Les joueurs les plus acharnés ont atteint 35 ans ;)
