### ISSUE TITLE
Etudiant bloqué en prison

### ISSUE THREAD

**Issue by M1rar1** [JulienNigon/SpellcasterUniversity-Bug-Report#1147]
Bonsoir, 

J'ai un étudiant bloqué en prison.
C'est une prison lvl2 . 
L'élève veut sortir, la porte est ouverte mais quand il arrive à la porte, elle est fermée. Il fait demi-tour pendant que la porte s'ouvre. Il se retourne (la porte est ouverte) pour sortir et la porte se referme. et il tourne en boucle
J'ai sauvé et rechargé. Ca a corrigé le problème (l'élève a été téléporté hors de la pièce) mais aussi supprimé l'étoile de la mission réputation des orcs.
Le problème, c'est que c'est la 6 ème fois que ça arrive sur cette prison sur cette partie.

Je ne sais pas si ça peut aidé, mais mon clavier a été subitement passé en qwerty pendant la partie.

**Comment by M1rar1** [comment]
DSL pour le double post
, il y a eu un bug de firefox

**Comment by Neelan22** [comment]
pas de pb, je supprime
