### ISSUE TITLE
Problème avec les objectifs.

### ISSUE THREAD

**Issue by izBapt** [JulienNigon/SpellcasterUniversity-Bug-Report#1153]
Bonjour l'équipe,

Je vous signale les 2 problèmes que j'ai eu récemment après avoir sauvegardé, quitté le jeu, puis y être revenu en chargeant ma partie:
- j'ai réalisé l'objectif avec les orcs (90pts d'amitié, l'étoile était validée), puis ai fait baissé mon amitié avec eux. J'ai alors sauvegardé et quitté. Quand j'ai rechargé ma partie, le jeu a alors considéré que mon objectif avec les orcs n'était plus réalisé.
- Après avoir rechargé le jeu, celui ci a considéré comme validé l'objectif des zombies aux marécages, alors même que les conditions n'était pas requises.

Voilà, j'espère que cela vous aidera, super jeu ;) !

**Comment by Neelan22** [comment]
Oui, le bug est connu... Merci pour ton retour ! :)

**Comment by Neelan22** [comment]
corrigé pour la prochaine MaJ :)
