### ISSUE TITLE
crash après tirage carte étudiant

### ISSUE THREAD

**Issue by myrealmisbeautiful** [JulienNigon/SpellcasterUniversity-Bug-Report#1154]
bonjour,

je vous fais remonter un crash récurrent que je rencontre dans le niveau de la tortue.
C'est ma 1ere campagne, je viens de faire un 1er retour dans le temps après avoir échoué à compléter les quêtes.
Au début de la seconde tentative le jeu plante systématiquement après le tirage d'une carte "nouveaux étudiants" depuis le deck initial.
Seule la case avec la poubelle apparaît, plus rien ne répond. Obligé d'arrêter depuis Steam.
J'ai essayé plusieurs fois en rechargeant la campagne depuis la sauvegarde précédente.
Je peux tirer d'autres cartes et placer des salles, pas de souci. La carte "nouveaux étudiants" fait toujours planter le jeu, qu'elle soit tirée en premier ou non.
J'ai rechargé la partie après avoir baissé la qualité des graphismes, puis après avoir vidé le cache et fichiers temporaires, sans résultat.
J'ai fini par commencer une nouvelle campagne, dans celle-ci je peux utiliser la carte sans souci au 1er niveau.

**Comment by Neelan22** [comment]
Ok, merci beaucoup pour les précisions. Si tu peux nous envoyer ta sauvegarde ça nous aiderait beaucoup.
Tu la trouveras ici : 
PC : C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster University
Mac : ~/Library/Application Support/Sneaky Yak Studio/Spellcaster University/Saves
Il suffit de zipper le dossier et de le placer dans la fenetre de texte sur le site de github, pas par retour de mail.
Merci pour ton aide

**Comment by myrealmisbeautiful** [comment]
La voilà, en espérant que ça aide :

[crash_student_card.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/5569685/crash_student_card.zip)

**Comment by Neelan22** [comment]
Nous avons corrigé le bug, il sera effectif lors de la prochaine mise à jour
