### ISSUE TITLE
Double défi ?

### ISSUE THREAD

**Issue by Astate22275** [JulienNigon/SpellcasterUniversity-Bug-Report#1159]
[
![20201122140410_1](https://user-images.githubusercontent.com/74860850/99904609-40614880-2ccc-11eb-832b-1cc0eecd161a.jpg)
](url)

Après avoir réussis le défi de transmutation et commencé le défi des ténèbre je me retrouve avec ça... C'est normal ?
(Je ne pense pas)

**Comment by Neelan22** [comment]
Oui c'est un bug qu'on nous a déjà rapporté, merci :) 
ça a été corrigé et ça sera effectif pour la prochaine MaJ !
