### ISSUE TITLE
Mission réussie après chargement d'une sauvegarde

### ISSUE THREAD

**Issue by M1rar1** [JulienNigon/SpellcasterUniversity-Bug-Report#1162]
Bonjour, 
Je viens de découvrir un heureux bug. :-)
Sur la carte  zombies, je galérais à finir la 1ère mission : surtout avec le seigneur des ténèbres (-22) en réputation 
2ème mission 6000 en arcane
3ème mission 90 pour les orcs.

J'avais fini la mission orc. Devant quitter et pour ne pas devoir la refaire, j'ai monté mon affinité (100/90) avec les orcs avant de sauvegarder. 
Aujourd'hui en chargeant ma partie SURPRISE, j'avais toujours -22/30 dans la mission zombie, j'avais toujours l'étoile de la mission orcs (100/90) mais j'avais aussi l'étoile de la mission zombie.
Je viens de finir la partie et j'ai obtenu un grimoire 3 étoiles.

**Comment by Neelan22** [comment]
Nous venons de corriger ce bug, la correction sera effective lors de la prochaine mise à jour 👍 merci pour ton retour !
