### ISSUE TITLE
Changer la vitesse du jeu

### ISSUE THREAD

**Issue by Minigerbox** [JulienNigon/SpellcasterUniversity-Bug-Report#1165]
Bonjour,
Ce commentaire est peut-être déjà apparu dans les retours plus globaux de certains utilisateurs, mais comme j'ai la flemme de tout lire : ce serait pratique de pouvoir moduler la vitesse du jeu en appuyant directement sur les touches numériques du clavier (1, 2, 3).
On peut déjà mettre en pause en appuyant sur la barre d'espace, mais pour l'instant (à moins que je n'aie pas encore trouvé la subtilité), je ne peux ralentir ou accélérer le jeu qu'en appuyant avec ma souris sur la zone dédiée à l'écran (qui est assez petite).

**Comment by Neelan22** [comment]
C'est effectivement le seul moyen de modifier la vitesse de jeu, je fais une note pour le dev

**Comment by Neelan22** [comment]
et il m'a répondu que les touches + et - fonctionnent ;)

**Comment by Minigerbox** [comment]
ah ben super !! il faut juste le savoir ;-)
