### ISSUE TITLE
Impossible d'affecter des nouveaux élèves

### ISSUE THREAD

**Issue by M1rar1** [JulienNigon/SpellcasterUniversity-Bug-Report#1167]
Début de partie et voici ce que j'obtiens

![image](https://user-images.githubusercontent.com/74323542/100772874-75724700-3400-11eb-82a6-b7a5f04665a6.png)
 impossible de sauver, de recharger

J'avais eu des bonnes cartes :'(

**Comment by Neelan22** [comment]
En relançant le jeu la partie a pu recommencer normalement?
Désolée pour le bug

**Comment by M1rar1** [comment]
Je suis revenu comme en début de partie.
J'ai perdu tout mon tirage et j'ai du tout refaire.
Mais oui, ça a été. 
Sauf que lors du tirage, je n'avais pas accès aux texte explicatif des cartes (ça arrive assez souvent d'ailleurs)

**Comment by Neelan22** [comment]
Le texte accessible avec un clic droit?

**Comment by M1rar1** [comment]
Oui,
Chez moi, le texte apparait automatiquement dés que je passe la souris dessus. 
Et parfois le texte disparait. Il n'est plus mis automatiquement et le click droit ne fonctionne pas non plus.

**Comment by Neelan22** [comment]
Nous pensons avoir corrigé le problème, je te demande juste confirmation : 
Est ce que le bug visible sur l'image est arrivé après un retour dans le temps, après avoir perdu une première fois le niveau?
Le bug du texte a aussi été corrigé

**Comment by M1rar1** [comment]
Oui, c'était à la première fois que je finissais (et perdais) la carte de la tortue. Et que je remontais le temps.

J'ai rechargé et fini la campagne.

**Comment by Neelan22** [comment]
parfait alors, je ferme l'issue
 merci
