### ISSUE TITLE
Evénement du lac - Dragon féérique

### ISSUE THREAD

**Issue by Grapline** [JulienNigon/SpellcasterUniversity-Bug-Report#1170]
Bonjour,

Je suis en train de faire la "quête" de Nessie sur le lac (rassembler 4 dragons différents). J'ai bien quatre dragons (bleu, blanc, violet, féérique), mais cela ne valide pas l'événement. Vu que je n'ai jamais rencontré le problème jusqu'ici, je suppose que c'est le féérique qui ne rentre pas en ligne de compte.
Si jamais c'est volontaire il manque une petite précision sur quels sont les dragons pris en compte ou pas.

Et sur le global, je profite du petit report du bug pour vous dire que le jeu est vraiment chouette. Il manque de musiques, mais j'ai cru comprendre que c'était en projet, hâte de voir la suite. J'aime beaucoup l'ajout des améliorations de salles, ça apporte un vrai gros plus au jeu. Et même si c'est du détail, l'ajout de détails dans les salles au fur et à mesure qu'on les améliore est vraiment agréable, comme tous les autres petits détails dont on profite dès qu'on se rapproche des salles. 
Donc merci, et chapeau pour tout le travail fait sur ce jeu !

**Comment by Neelan22** [comment]
Merci pour tes retours !
Le dragon féérique a effectivement été oublié, nous l'ajoutons pour la prochaine MaJ. Il y aura une mise à jour centrée sur les musiques courant janvier
