### ISSUE TITLE
erreur d'affichage carte

### ISSUE THREAD

**Issue by MetyNapa** [JulienNigon/SpellcasterUniversity-Bug-Report#1173]
Bonjour, une petite erreur d'affichage lors de la sélection du biome : Les falaises sont indiqué "plage" dans le cadre de description qui apparaît lorsqu'on passe la souris dessus.
![image](https://user-images.githubusercontent.com/61111230/102019372-78abf200-3d73-11eb-9812-27b9024bd305.png)

**Comment by Neelan22** [comment]
C'est modifié, merci !
