### ISSUE TITLE
Visiting Peasants stadart options wrong values

### ISSUE THREAD

**Issue by Wikifan0** [JulienNigon/SpellcasterUniversity-Bug-Report#1175]
Hello! Sorry, I don't speak french. I will use google translate below.../ Salut! Désolé, je ne parle pas français. J'utiliserai google translate ci-dessous.

When visiting peasants the 1. option only grants 10 reputation for 25(30?) nature mana. Second option also gives 10 reputation, but  for free. Is this intended? Because picking the first option would never make sense if it gives the same reward but you also pay mana.

français
Lorsque vous visitez des paysans, l'option 1. n'accorde que 10 points de réputation pour 25 (30?) Mana de nature. La deuxième option donne également 10 points de réputation, mais gratuitement. Est-ce voulu? Parce que choisir la première option n'aurait jamais de sens si elle donne la même récompense, mais vous payez également du mana.

**Comment by Rentaboy** [comment]
I believe the 2nd option makes it possible for a next encounter to have the "We're really gonna have to explain to you about the cows" option which gives 20 reputation with the peasants.

**Comment by Neelan22** [comment]
corrected for the next update, thank you !
