### ISSUE TITLE
Locale mistake

### ISSUE THREAD

**Issue by Rentaboy** [JulienNigon/SpellcasterUniversity-Bug-Report#1176]
It says "Not asking me question again" but should be "Don't ask this question again" or something along those lines.
("Don't ask again" would be nice and short)

If you guys need someone to check localization for english or dutch I'd be glad to help.

![image](https://user-images.githubusercontent.com/51852976/103161077-2d66fa00-47dd-11eb-99e1-8123db2e21f5.png)

**Comment by Neelan22** [comment]
Thank you for the feedback, I corrected it.
Thank you for your offer, we have already chosen someone for a proofreading in English
