### ISSUE TITLE
Problem choosing teacher

### ISSUE THREAD

**Issue by Sheretech** [JulienNigon/SpellcasterUniversity-Bug-Report#1188]
The game crashes at when you choose teacher for rooms. You place the x'th classroom and it will not let you choose one of the 2 teachers. Game continues in the background, but you can not close the game and reopen, it will keep on asking to choose teacher.
Updated game today

**Comment by Neelan22** [comment]
We made a fix today, did you download it? We corrected the problem concerning teachers with the "Scholar" trait. Does this seem consistent with your problem?

**Comment by Sheretech** [comment]
This concerns update 0.98. Did not have this issue before today.

**Comment by Neelan22** [comment]
ok, we made fix 0.983, you shouldn't have this bug now

**Comment by DVLOS** [comment]
When does this fix come out on Steam?

**Comment by Neelan22** [comment]
yesterday

**Comment by DVLOS** [comment]
IT says I have 0.984 just grew my university to about 4 classrooms and 4 other rooms.. Placed another class, and it froze on the teacher screen, both teachers appeared to be excellent choices.

**Comment by Neelan22** [comment]
can you put your save here?
It is here: C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster University\SteamID\Saves

**Comment by DVLOS** [comment]
Here it is
[save.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/5850991/save.zip)

**Comment by DVLOS** [comment]
![20210121125357_1](https://user-images.githubusercontent.com/77796358/105391116-c7a53c80-5be7-11eb-98d0-6ce3c4c30322.jpg)


My latest crash

**Comment by Neelan22** [comment]
ok you were right, the bug was still here for english players :/
This is fixed know, thank you for your help !

**Comment by DVLOS** [comment]
Thanks! Loving the game so far!
