### ISSUE TITLE
Crash jeu tortue lors de selection de classe

### ISSUE THREAD

**Issue by Mitlor66** [JulienNigon/SpellcasterUniversity-Bug-Report#1190]
Bonjour, 
Je joue a Spellcaster University depuis une semaine sans aucun soucis majeur, jeu fluide et optimisé. Cependant, lors de la derniere mission sur la tortue, je ne savais pas si il fallait donner les 5 cartes a la tortue ou finir les 7 quetes de l'université. En donnant les cartes a la tortue, j'ai du recommencer ma derniere game avec quelques bonus supplémentaire. Cependant, impossible de placer une classe, le jeu me demandait de choisir un prof et je ne pouvais cliquer nul part. J'ai donc coupé et relancé le jeu et je me retrouve maintenant directement a l'année 127 et mon ecran ne repond plus. Le jeu est ultra lent et freeze. Ma sauvegarde est donc corrompue et je devrais recommencer a 0 (ce n'est pas un soucis, ce sont les aléas des alpha :D) mais j'aimerai ne plus retomber sur ce bug qui peut etre tres genant surtout en fin de partie :) 
Un grand merci a vous les devs qui faites un travail extraordinaire avec ce jeu dont je suis tombé amoureux.

**Comment by Neelan22** [comment]
Bonjour Mitlor66 et merci pour ton retour. Nous avons fait un fix hier pour corriger ce bug, il ne devrait plus arriver normalement :)
Certains joueurs ont pu continuer leur partie après le fix, si ce n'est pas le cas pour toi, tu peux nous poser ta save ici et notre dev te corrigera le bug.
Tu la trouveras ici :
C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster University\SteamID\Saves

**Comment by Mitlor66** [comment]
Merci infiniment pour le debug si c'est possible!
[Mitlorian.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/5848892/Mitlorian.zip)

Cependant j'ai rencontré ce bug ce matin apres avoir download le patch, je ne sais pas si c'est normal? Peut etre est-ce parce que ma partie etait deja en cours. Dans tout les cas merci et j'espere que cela ne se reproduira plus :)

**Comment by JulienNigon** [comment]
[save.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/5850615/save.zip)

A décompresser et à mettre à la place de l'ancien save.xml. J'ai corrigé et testé ça me semble bon. Mais je reste dispo si un soucis que je n'ai pas vu :)
