### ISSUE TITLE
The game always crash when I try to choose teacher for the new classroom

### ISSUE THREAD

**Issue by poonpoonpoon** [JulienNigon/SpellcasterUniversity-Bug-Report#1191]
The game always crash and start to change into French and I have to start the new game in order to play again

**Comment by poonpoonpoon** [comment]
Its been happening since the new update

**Comment by DVLOS** [comment]
IT is not always. I have a discussion on this on the STEAM forums too. No response from the Devs but it happens way too often ...

**Comment by JulienNigon** [comment]
We have found the bug. A fix should be released in a few hours. We try to do it as quickly as possible.
