### ISSUE TITLE
Laisser appuyé une des touches fonction ralentit le jeu

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#120]
v0.62
Elles n'ont l'air de rien faire pour l'instant.

**Comment by JulienNigon** [comment]
Comment a tu pu détecter ça??
Merci :)

**Comment by Fouindor** [comment]
https://media.giphy.com/media/jM66C09QgTon6/giphy.gif

Plus sérieusement, un livre est tombé sur mon clavier au moment opportun ^^'

**Comment by JulienNigon** [comment]
C'est avec un grand regret que je ferme mon bug préféré. Qu'il repose en paix.

**Comment by Fouindor** [comment]
https://i.4pcdn.org/pol/1480096111125.gif
