### ISSUE TITLE
Show what cards you have when you are choosing a new card

### ISSUE THREAD

**Issue by RichardJECooke** [JulienNigon/SpellcasterUniversity-Bug-Report#1206]
Not a bug, but the most important feature request we need in the game. 
Like so please:

![spellcaster upgrade](https://user-images.githubusercontent.com/5468805/107371166-a0f26b80-6aec-11eb-8517-7d71ad9d8e0d.jpg)

**Comment by Neelan22** [comment]
Currently working on it :)
