### ISSUE TITLE
Evenement orcs affamés : la machine a raclette ne marche pas

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#121]
v0.62 :
Erreur de clé inexistante sur l'option raclette:
https://drive.google.com/open?id=1fFNUsghaXXACDSb7dKDmIkWxYDQxs5qD
https://drive.google.com/open?id=1GGCXgTgGiaIKtAiAH47gTfX6galkEQNp

Même quand j'ai l'appareil a raclette:
https://drive.google.com/open?id=1TVQYl6nEsa8yA5JSqUPniqvTEKzJN1nD

**Comment by JulienNigon** [comment]
Normalement c'est bon.
