### ISSUE TITLE
Wrong potion receipe

### ISSUE THREAD

**Issue by Azutas** [JulienNigon/SpellcasterUniversity-Bug-Report#1212]
J'ai utilisé Licorne ; Mandragore ; Chapeau et Mandragore ; Fromage ; Chapeau >>> j'ai obtenu des elixirs sacrés 

En tout cas, très bon jeu en général et super pour une version alpha
Félicitations à vous !

**Comment by Neelan22** [comment]
Il y a toujours 2 recettes disponibles pour la fabrication de chaque potion. Celles-ci changent d'une campane à l'autre.
