### ISSUE TITLE
Condition pour choix multiple valide mais non cliquable (2)

### ISSUE THREAD

**Issue by Bubulle09** [JulienNigon/SpellcasterUniversity-Bug-Report#1233]
Durant la campagne sur le niveau de la tortue, j'ai un choix multiple et je remplis toutes les conditions pour en valider un mais je ne peux pas cliquer dessus, il n'est pas considéré comme validé.

![bugSpellcaster University](https://user-images.githubusercontent.com/84470541/119234853-4c6d7c00-bb30-11eb-88ab-adae85dd439a.png)

**Comment by Bubulle09** [comment]
My bad j'ai lu top vite j'avais pas les conditions pour celui-ci

**Comment by JulienNigon** [comment]
Ah oui je me suis laissé avoir aussi ^^

Merci !
