### ISSUE TITLE
Concierge a un comportement aller-retour avec son lit quand il n'a rien à faire

### ISSUE THREAD

**Issue by JulienNigon** [JulienNigon/SpellcasterUniversity-Bug-Report#139]

**Comment by LeBanc** [comment]
Pour info, j'ai eu un cas similaire avec un élève qui avait majoré toutes les disciplines de sa magie et qui appartenait à une une classe où je n'avais pas autoriser l'apprentissage d'autre chose.

**Comment by JulienNigon** [comment]
Je note ce second problème
