### ISSUE TITLE
Mes élèves sont bloqués !!!

### ISSUE THREAD

**Issue by Neelan22** [JulienNigon/SpellcasterUniversity-Bug-Report#149]
![image](https://user-images.githubusercontent.com/47151033/51924020-8ad54f00-23ec-11e9-931d-34f36a4887a0.png)

**Comment by JulienNigon** [comment]
Il faut que l'on agrandisse l'île ou qu'on réduise la taille du chateau.

**Comment by JulienNigon** [comment]
J'ai réduit la taille du chateau pour éviter ce problème.
