### ISSUE TITLE
texte des pensées bugé

### ISSUE THREAD

**Issue by Neelan22** [JulienNigon/SpellcasterUniversity-Bug-Report#152]
![image](https://user-images.githubusercontent.com/47151033/51925367-2e276380-23ef-11e9-9e5e-328e6038595b.png)

**Comment by Fouindor** [comment]
C'est bizarre. Dans la v0.60 et v0.62, ça ne m'est jamais arrivé. Soit c'est un bug d'une nouvelle version ou soit ça apparaît dans un cas particulier (p-e que ça n'affecte que les conseillers ?)

**Comment by JulienNigon** [comment]
Ok je pense que c'est les pensées des profs qui plantent. D'ailleurs il a des pensées normalement liées aux élèves.
