### ISSUE TITLE
bug dans les classes. Juste affichage?

### ISSUE THREAD

**Issue by Neelan22** [JulienNigon/SpellcasterUniversity-Bug-Report#154]
![image](https://user-images.githubusercontent.com/47151033/51926218-1224c180-23f1-11e9-80e5-6ca8c11bab77.png)

**Comment by Neelan22** [comment]
il y a une 4e classe avec les robes blanches et ils ne sont pas sensé étudier l'alchimie ! Et pourtant ils ont la fiole autour du cou

**Comment by JulienNigon** [comment]
Je n'arrive pas à reproduire le bug. Il y avait eu des bugs avant que ça apparaisse? Je suis preneur si d'autres réussissent à reproduire ce bug.

**Comment by Fouindor** [comment]
J'ai également eu le bug sur une grosse école (> 30 élèves dans chaque classe) : https://drive.google.com/open?id=12IeofLlvRuQPfDOBraYUkXUcpfsj9Py5

**Comment by Neelan22** [comment]
Mes classes n’etaient Pas aussi remplies mais je dépassais les 20 élèves (~25 max je pense)

**Comment by Fouindor** [comment]
Après avoir testé avec les outils de débug, j'arrive a avoir > 80 éléves dans une seule classe sans bug

**Comment by Neelan22** [comment]
Avec 1 classe? Moi j’en avais 3

**Comment by JulienNigon** [comment]
Ok ça veut dire que ce n'est pas forcement lié à la taille des classes. Je pense que c'est un élève qui fait planter, et que du coup statistiquement ça arrive plutôt dans des parties avancées.

**Comment by Fouindor** [comment]
Après, même si c'est statistiquement rare, je trouve qu'il est bizarre de ne pas arriver a le produire en accéléré avec les outils de débug mais de le reproduire facilement sur une longue partie si c'est une simple occurrence statistique. Peut-être que c'est dû à l'acquisition d'un trait à cause d'un objet installé dans une salle ? c'est le seul exemple de chose statistiquement rare pouvant affecter les élèves impossible à reproduire avec la toolbox débug auquel je peux penser.

**Comment by JulienNigon** [comment]
Malin. Je vais regarder de ce côté.

**Comment by Fouindor** [comment]
J'ai essayé de prêter un peu d'attention à ce qui fait apparaître ce bug durant mon test sur la v0.65.

Le bug est arrivé après avoir joué la carte des cornes du druide (j'ai regardé a ce moment-là mais est-ce que c'est ça qui l'a déclenché ? pas sur)

![20190216183605_1](https://user-images.githubusercontent.com/15092739/52903162-19820280-321a-11e9-9c44-fda73d3e496d.jpg)

Quand je clique sur l'étudiant sans face, la fiche qui s'ouvre est vraiment bizarre:

![20190216183649_1](https://user-images.githubusercontent.com/15092739/52903164-19820280-321a-11e9-89cf-bd8877b14f19.jpg)

**Comment by Fouindor** [comment]
Pas réussi a le reproduire sur une seconde partie, en jouant toutes les cartes équipement que je pouvais.

**Comment by JulienNigon** [comment]
Cet étudiant bizarre est celui de la fiche "de base". ça signifie qu'elle ne s'est pas mise à jour un truc l'a fait planter avant. Je vais regarder si les cornes de druide sont responsables.

**Comment by JulienNigon** [comment]
J'avais espoir mais non les cornes de druides ne sont pas responsables. Ou en tout cas pas directement responsables.

**Comment by JulienNigon** [comment]
Je pense que c'est résolu. Tant que le contraire ne sera pas prouvé, ce bug est considéré comme réglé.
