### ISSUE TITLE
Accès bloqué par la chambre privée

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#175]
v 0.62

Dans la private room, les personnages se bloquent derrière le mur (ce qui n'est pas pratique parce qu'on peut pas les sélectionner pour les TP back). Ça m'est arrivé sur deux essais différents : 

![bloque](https://user-images.githubusercontent.com/15092739/52162854-0596b680-26da-11e9-8b95-0f2cd2ca7378.gif)

![bloque2](https://user-images.githubusercontent.com/15092739/52162855-0596b680-26da-11e9-90f1-32d35f964150.gif)

Lors du second essai, j'ai ensuite construit une salle de cours au dessus, personne n'y allait, ça a donc l'air d'également bloquer l'accès aux autres salles. Une fois que j'ai construit une salle à côté de la salle du dessus, les élevés pouvaient y accéder normalement.

**Comment by JulienNigon** [comment]
L’ascenseur de la chambre a été corrigé et elle fonctionne à nouveau normalement.
