### ISSUE TITLE
Certaines carrières ont des clés inexistantes

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#194]
v 0.63

Pas sur de les avoir tous trouvés

![20190208190419_1](https://user-images.githubusercontent.com/15092739/52498081-021e9600-2bd8-11e9-9a19-d1ac11610efc.jpg)
![20190208190829_1](https://user-images.githubusercontent.com/15092739/52498089-05b21d00-2bd8-11e9-9dc4-5eb452d68479.jpg)
![20190202100645_1](https://user-images.githubusercontent.com/15092739/52498113-19f61a00-2bd8-11e9-8c2d-153f748d29f5.jpg)
![20190208190402_1](https://user-images.githubusercontent.com/15092739/52498071-fd59e200-2bd7-11e9-9d2b-6500040aa941.jpg)

**Comment by JulienNigon** [comment]
Il en reste beaucoup d'autres !
