### ISSUE TITLE
Bureau du directeur nulle part dans l'école

### ISSUE THREAD

**Issue by jeremy-boes** [JulienNigon/SpellcasterUniversity-Bug-Report#238]
On peut aller via le menu dans le bureau du directeur... mais cette salle n'est nulle part dans l'école ! C'est un peu bizarre quand on y pense, non ? :D

Bon en vrai je m'en rend compte que maintenant donc ça doit pas être si gênant^^

**Comment by JulienNigon** [comment]
Le bureau du directeur flotte à travers les mondes. Ce sera dit entre les lignes dans certains événements. Oui c'est un peu bizarre :)
