### ISSUE TITLE
Organiser les cartes en main

### ISSUE THREAD

**Issue by ArnaudGL** [JulienNigon/SpellcasterUniversity-Bug-Report#263]
Avoir un moyen de trier entre les salles, les objets, les ingrédients et les artefacts. Ou mieux, avoir les artefacts positionnés dans des slots ailleurs que dans la main et les ingrédients directement ajoutés au menu des potions. (également rendre le menu des potions ouvrable)

**Comment by JulienNigon** [comment]
On garde le menu des potions ouvrables.
Après réflexions, on préfère conserver les cartes groupées pour des raisons de lisibilité. Mais la fréquence d'apparition des ingrédients réduites devrait simplifier la lecture.
