### ISSUE TITLE
Recrutement des étudiants envahissant

### ISSUE THREAD

**Issue by ArnaudGL** [JulienNigon/SpellcasterUniversity-Bug-Report#264]
le popup de recrutement des étudiants arrive a n'importe quel moment. Si vous êtes en train de poser une salle ou une potion, le menu chevauche ce que vous êtes en train de faire. A la limite, bloquez le temps et mettez un eye-catcher pour montrer qu'une décision de recrutement doit être prise.

**Comment by JulienNigon** [comment]
Oui, il y a un problème sur le recrutement des étudiants. Il devrait être bloqué lorsque le jeu est en pause.
