### ISSUE TITLE
Bastion Royal ( le roi )

### ISSUE THREAD

**Issue by DioudeDamien** [JulienNigon/SpellcasterUniversity-Bug-Report#270]
![55525871_259494568290871_7599894533773459456_n](https://user-images.githubusercontent.com/48966795/55032518-4f808680-5011-11e9-80bd-1761cbe0edf3.jpg)
Quand on lance la discution avec le roi dans la 1er réponse que l'on peut donner il y a deux fois le mot simplement

**Comment by JulienNigon** [comment]
Bien vu.
