### ISSUE TITLE
Traits de caractère 

### ISSUE THREAD

**Issue by DioudeDamien** [JulienNigon/SpellcasterUniversity-Bug-Report#273]
Il y a le trait " Subtil " Qui na pas d'info texte 
La bulle indique " Pas d'infotexte ! "

**Comment by JulienNigon** [comment]
Ce trait de caractère ne devrait jamais apparaître. C'est un bug. Nous allons enquêter. Des circonstances spéciales ont menées au moment ou tu as vu ce trait?

**Comment by DioudeDamien** [comment]
Non 
J'ai vu ce trait de caractère sur 2 ou 3 élevés en 2 partit différentes

**Comment by JulienNigon** [comment]
C'était un problème d'affichage. Il est désormais résolu, normalement.
