### ISSUE TITLE
bug avec les éléves le portail n'apparait pas et ne peut rien faire ... 

### ISSUE THREAD

**Issue by DioudeDamien** [JulienNigon/SpellcasterUniversity-Bug-Report#292]
![Sans titre](https://user-images.githubusercontent.com/48966795/55681061-24a40580-5922-11e9-89a8-0d12c7119bd2.png)

**Comment by DioudeDamien** [comment]
c'est la 3eme partie a la suite que j'ai le bug

**Comment by JulienNigon** [comment]
Désolé. Ce bug n'a impacté "que" la version Steam, mais a été corrigé maintenant. On a posté un hotfix. Merci !
