### ISSUE TITLE
Supprimer la classe de base?

### ISSUE THREAD

**Issue by JulienNigon** [JulienNigon/SpellcasterUniversity-Bug-Report#332]

**Comment by jeremy-boes** [comment]
Gros +1 là-dessus !

Ou au moins pouvoir éditer le nom, le logo et les robes. En tout cas c'est le genre de truc qui m'importe beaucoup quand je joue. :)

**Comment by JulienNigon** [comment]
Done ! Je l'avais mis en mineur mais vu ton commentaire Jeremy je l'ai fait tout de même.
