### ISSUE TITLE
Evénement "Les astres sont alignés" - Pas d'attaque de morts vivants

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#334]
v 0.71
Le titres explique plutôt bien le bug - n'ayant ni astrolabe ni observatoire, j'ai du prendre la 3e option lors de l'event "Les astres sont alignés", où 7 morts vivants sont sensés m'attaquer. Je n'ai jamais vu ces morts vivants.

A noter que j'ai bien subi les attaques orcs après et avant l'event susnommé.

**Comment by JulienNigon** [comment]
Les morts-vivants ne sont pas encore intégrés en effet.

**Comment by LeBanc** [comment]
Je laisse un commentaire ici car je ne sais pas si ça peut être un bug ou non mais c'est lié à cet évènement.
J'ai eu le droit à l'apparition de cet évènement dès l'automne de l'année 0 sur deux parties et j'étais plutôt content de ne pas voir arriver 7 squelettes dû à leur non-implémentation :)

**Comment by JulienNigon** [comment]
- [x] bug corrigé
- [x] condition ajouté pour s'assurer que l'event ne tombe pas en début de partie
