### ISSUE TITLE
Résurrection miraculeuse

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#336]
Je peux re-roll le destin d'un étudiant mort... bug or feature? 😁 

![20190417130534_1](https://user-images.githubusercontent.com/15092739/56284955-48333100-6116-11e9-8502-51f502735aa6.jpg)
![20190417130542_1](https://user-images.githubusercontent.com/15092739/56284956-48cbc780-6116-11e9-9784-e2e09db2d293.jpg)

**Comment by JulienNigon** [comment]
Feature ! XD
Pour de vrai :) Bien formé il survivra dans ce monde cruel...
