### ISSUE TITLE
Le badge "communication disponible" n’apparaît plus

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#337]
En effet, je trouvais curieux que le cochonier mette autant de temps à charger...
![20190417130451_1](https://user-images.githubusercontent.com/15092739/56285096-a829d780-6116-11e9-956b-8f5dbe232f92.jpg)
![20190417130454_1](https://user-images.githubusercontent.com/15092739/56285098-a95b0480-6116-11e9-9015-9c7bcd4bec7c.jpg)

**Comment by Fouindor** [comment]
Duplicata de #294 .

**Comment by JulienNigon** [comment]
Bien reçu. Enquête en cours.

**Comment by JulienNigon** [comment]
Une piste pour reproduire le bug,

**Comment by LeBanc** [comment]
[Demo_v3] J'ai également eu ce problème après avoir contacter le cimetière et choisi l'option "Oubliez ça. Je m'en vais" et également la deuxième option chez les paysans ("S'assurer que tout va bien")
Le badge ne réapparait plus dans la fenêtre principale après ces choix de dialogue (pas exhaustif, je n'ai pas fait le tour des possibilités) mais si on fait un nouveau contact avec un dialogue qui fonctionne (premier des paysans, dialogues des orcs (normalement tous)), le badge réapparait de manière normal (après son délai de chargement)

**Comment by JulienNigon** [comment]
Effectivement, bien joué @LeBanc ! Je pense que je vais pouvoir faire quelque chose avec ça !

**Comment by LeBanc** [comment]
J'ai du nouveau sur ce bug !
Le badge a aussi disparu alors que je ne faisais que des contacts normalement sans problème !
Il me semble que c'est lié à des évènements qui apparaissent (Paiement d'un tribut aux Orcs, évènement "On a faim" - non exhaustif). Je n'ai pas l'impression que ce soit régulier ou lié à la réponse à ces évènements mais c'est assez difficile à évaluer en jouant.
J'ai également remarqué qu'un évènement est arrivé à terme (barre chrono autour du badge à fond et apparition de la fenêtre de dialogue) au moment où le badge "Communication" devait apparaître et que ce dernier n'est pas apparu mais je ne peux pas dire si c'est lié au timing, à l'évènement ou à la réponse que j'ai donné.

Ça m'a l'air un peu complexe, j’essaierai de mieux faire attention lors de prochains tests (mais ça casse un peu le plaisir de jouer). Bon courage !

**Comment by JulienNigon** [comment]
Merci à tous les enquêteurs ! Le bug du cochon d'inde "devrait" être corrigé.

**Comment by JulienNigon** [comment]
Second round. Je ne le voit plus bugger, mais à tester sur le long cours avec ce nouveau patch.
