### ISSUE TITLE
Événement "Archives" - Condition manquante

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#340]
v 0.71

La 3e option de l’événement initial d'exploration des archives n'a pas de condition :'(
(je suppose qu'il s'agit d'avoir au moins une bibliothèque ?)

![20190419172021_1](https://user-images.githubusercontent.com/15092739/56444333-87b97300-62f8-11e9-8800-92eda05f3f25.jpg)

**Comment by JulienNigon** [comment]
Bien vu. Done.
