### ISSUE TITLE
La zone de surbrillance du seigneur du mal sur la map est trop haute

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#342]
v 0.71

Tout est dans le titre

![20190419172429_1](https://user-images.githubusercontent.com/15092739/56444458-25ad3d80-62f9-11e9-84a4-4b280fccc20e.jpg)
![20190419172432_1](https://user-images.githubusercontent.com/15092739/56444459-2645d400-62f9-11e9-9d31-a791d65074e8.jpg)

**Comment by JulienNigon** [comment]
Je crois que c'est bon
