### ISSUE TITLE
Succès steam Hic sunt dracones

### ISSUE THREAD

**Issue by E-Rosario** [JulienNigon/SpellcasterUniversity-Bug-Report#345]
Sans avoir fait quoi que ce soit en lançant le jeu pour la deuxième fois sans avoir joué la première fois, le succès steam Hic sunt dracones a été validé.

![image](https://user-images.githubusercontent.com/50151272/56983233-67ed3f00-6b83-11e9-8502-ceb6b02b50f2.png)

**Comment by JulienNigon** [comment]
Les succès vont fonctionner correctement dans le prochain patch.
