### ISSUE TITLE
Menu paramètre choix de langue

### ISSUE THREAD

**Issue by E-Rosario** [JulienNigon/SpellcasterUniversity-Bug-Report#346]
Lorsque je change de Langue de English à French, English reste coché alors que French l'est aussi.
Il y a une fine bande blanche derrière le menu environ au premier tiers

**Comment by JulienNigon** [comment]
Dans le menu principal, ou dans le menu des options en jeu?

**Comment by E-Rosario** [comment]
C'est dans le menu principal!
