### ISSUE TITLE
Texte pensées

### ISSUE THREAD

**Issue by E-Rosario** [JulienNigon/SpellcasterUniversity-Bug-Report#347]
Les textes dépassent le cadre si on utilise la molette, la caméra zoom et dezoom en même temps

![image](https://user-images.githubusercontent.com/50151272/56985690-337c8180-6b89-11e9-96e4-c696bd47103d.png)

**Comment by JulienNigon** [comment]
Bien vu. La prochaine version devrait supprimer ce problème. Je le note comme résolu.
