### ISSUE TITLE
Affichage Niveau magie max erroné

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#365]
v0.71
Quand un élève maîtrise une discipline, le chiffre affiché dans sa fiche de personnage n'est pas toujours "5" (par contre l'infotexte est bon)

Quand je sélectionne un étudiant dans le jeu, le chiffre est à '0' (en tout cas c'est ce que j'ai remarqué).

Quand je sélectionne un étudiant depuis la liste des classes, le chiffre correspond si c'est ma première sélection, sinon le chiffre reste le même que l'étudiant précédant (mais l'effet sur le logo de la discipline pour montrer qu'elle est au max fonctionne)

**Comment by JulienNigon** [comment]
Parfait. Cela remarche normalement. Merci :)
