### ISSUE TITLE
Instantanéité? des avenirs

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#366]
J'ai remarqué que les instantanéités des avenirs n'étaient pas correctes dans la liste du bureau du directeur.
Assassin, Maître assassin, Aventurier, Sbire, Prêtre, Druide, Mage du village et surement d'autres ont le trait "Permanent" au lieu de "Immédiat" (Instantané?)

C'est peut-être déjà le sujet de l'item #199 ?

**Comment by JulienNigon** [comment]
En effet. Problème corrigé (un mauvais remplissage des fichiers de données). Merci.
