### ISSUE TITLE
Son très répétitif

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#368]
J'ai parfois un son très répétitif :
bldwork.000webhostapp.com/son_repetitif.wav

J'ai du mal à déterminer d'où il vient. J'ai l'impression que c'est lié au cochonnier ou à la librairie puisque le son était spatialement centré sur cette colonne de salles mais je n'arrive pas à clairement identifier son origine.
Le son n'est pas tout le temps présent, il disparait parfois.
Il reste lorsqu'on passe en pause.

C'est à peu près tout ce que je peux dire.
Ah non, c'est plutôt désagréable à la longue :)

**Comment by JulienNigon** [comment]
Bien vu, c'est un placeholder malheureux en vu de la mise en place des bruitages que nous avons laissé passer... il sera bientôt remplacé par des vrais sons :) (et oui c'est la librairie)
