### ISSUE TITLE
Volume musique pas totalement coupé avec case décochée

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#371]
J'ai décoché la case "Musique" dans les options pour investiguer sur un son gênant et ça ma bien atténué la musique mais pas totalement coupé.
En jouant sur le volume principal, tout le son était bien coupé et en réactivant la case et en mettant la barre "Volume Musique" à gauche la musique ne s'entendait pas donc je me suis dit que c'était un problème de réduction de volume lors du décochage de la case "Musique".
Sauf que j'ai eu une autre fois le cas d'une musique dont le son ne s'est pas coupé alors que j'avais bien fait glisser la barre "Volume Musique" tout à gauche, il était très faible mais toujours audible.

Ma première piste serait qu'une des musiques à un volume plus élevé de base et que l'atténuation appliquée ne suffit pas à assez le réduire mais je ne sais pas si c'est une bonne hypothèse.

**Comment by JulienNigon** [comment]
Je regarde ça c'est assez bizarre en effet. Mais je confirme l'existence du bug.

**Comment by JulienNigon** [comment]
Cela devrait être bon.
