### ISSUE TITLE
Touche clavier pour gestion de la vitesse

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#372]
Pour beaucoup jouer en vitesse x3 après quelques parties et souvent mettre en pause, je trouverais utile d'avoir des raccourcis clavier pour ça (au moins la pause).

**Comment by JulienNigon** [comment]
Je rajoute la pause sur "espace" et +/- pour la vitesse pour la beta.
