### ISSUE TITLE
Conditions des Avenir dans la liste du bureau du directeur

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#374]
On a bien les effets des avenirs découverts dans le bureau du directeur mais on ne voit pas les conditions nécessaires pour que les élèves les obtiennent.
Je trouverais utile de retrouver l'infotexte qui existe sur le point d'exclamation lorsqu'on choisit l'avenir de l'élève quand on parcourt la liste dans le bureau du directeur.
Ça permettrait selon moi de parfois mieux sélectionner de nouvelles recrues pour essayer d'obtenir un avenir précis en fonction d'un trait de caractère de l'élève ou de la classe qu'on lui attribut.

**Comment by JulienNigon** [comment]
Oui ça manque on est bien d'accord dans l'équipe. On va s'occuper de ça.

**Comment by JulienNigon** [comment]
Done
