### ISSUE TITLE
Conditions de carrières éronnées

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#375]
L'avenir Héros a pour condition Druidisme 2, devrait être héroïsme ?

L'avenir Inquisiteur a comme modificateur Assassinat 2 !
La condition Vindicte 4 et l'autre modificateur Loyal me paraissent corrects.

**Comment by JulienNigon** [comment]
Corrigé.
C'était une volonté pour l'inquisiteur, mais c'est vrai que ça passe pas très bien en fait.
Merci !
