### ISSUE TITLE
bug affichage du niveau de magie 

### ISSUE THREAD

**Issue by Neelan22** [JulienNigon/SpellcasterUniversity-Bug-Report#385]
dans mon cas : l'élève est niveau 5 en magie des portails et le numéro en bas à droite du logo portail est sur 0

**Comment by LeBanc** [comment]
Pour aider (humblement) le(s) développeur(s) : je pense que c'est le même point que #365

**Comment by JulienNigon** [comment]
Effectivement, c'est le même problème. Je ferme celui-ci.
