### ISSUE TITLE
Persos marchent sur place dans le monde Forêt

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#389]
[v0.72]
J'ai eu plusieurs persos bloqués sur place, mais avec l'annimation de la marche, dans le monde de la forêt. Ça m'est arrivé au début avec des professeurs qui se débloquaient pour aller fermer des portails ou éteindre des incendies puis se bloquaient de nouveau. Puis avec des élèves, ce qui m'a fait remarqué que ça à l'air lié à leur envie de sortir de l'école pour aller assouvir différent besoin.
J'en suis arrivé à penser que le point de sortie dans ce monde est mal défini.

**Comment by JulienNigon** [comment]
Tu en es arrivé à penser très justement !
Et c'est très bizarre que ça ai échappé aux tests. On a du le déplacer après coup...
