### ISSUE TITLE
Menu sans effet

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#390]
[v0.72]
Parfois, les boutons du menu ne font rien, à part "Options" et "Annuler". On ne peut donc ni sauvegarder, ni quitter le jeu ! Le clic est pris en compte car la couleur du bouton change mais l'action n'est pas effectuée.
Je n'ai malheureusement pas plus d'indication sur le contexte qui aurait pu amener à ce problème.

**Comment by JulienNigon** [comment]
Problème de bugs en cascade difficile à solutionner de manière certaines. Plusieurs cas de déclenchement ont été solutionnés et je ne l'ai pas reproduit. Je le ferme pour l'instant.
