### ISSUE TITLE
Barre espace fait apparaître la fenêtre de debug

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#391]
[v0.72]
J'ai voulu tester la pause, j'ai appuyé sur 'espace' et à ma grande surprise, j'ai vu apparaître un bandeau sur la droite de l'écran avec plein de boutons !
Alors c'est marrant de pouvoir créer une salle ou des élèves ex nihilo ou même de pouvoir tuer tout le monde (ce qui pose le problème du remplacement des professeurs) mais je ne pense pas que ce soit voulu, en tout cas, peut-être pas sur la même touche que pour mettre en pause :)

(Par contre pour le debug, ça pourrait parfois être bien utile si j'arrivais à mieux comprendre ce qu'on peut faire avec)

**Comment by JulienNigon** [comment]
Arf oui, c'est un outil interne normalement.
On va réfléchir à une façon peut être de l'ouvrir aux testeurs, mais dans un premier temps je vais a re-cacher.
