### ISSUE TITLE
Bug après enchainement des parties

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#392]
[v0.72]
Après avoir fini une partie (attaque des forces du mal), je suis retourné au menu principal et j'en ai lancé une autre, j'ai alors remarqué 2 choses :
- La gestion du temps avec les touches '+'/'-'/'espace' ne fonctionnait plus
- L'année restait bloquée à "Année 0 : Hiver"

Ce problème est arrivé pour toutes les parties que j'ai testé sur cette même session.

A noter que la gestion du temps avec les touches est parfois revenue lors de mes tests (notamment en tuant tout le monde grâce au bandeau de debug) puis se rebloquait sans que je sache pourquoi.

**Comment by JulienNigon** [comment]
Devrait être corrigé.
Problème à causes multiples, c'est possible qu'il réapparaisse. Mais en attendant je le clôt.
Merci !
