### ISSUE TITLE
Pas vraiment de fin de partie après attaque des forces du mal

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#393]
[v0.72]
Lors de l'attaque des forces du mal, tout le monde s'enfuit en courant et puis ... rien.
Les évènements arrivent encore, j'ai même pu faire de nouveaux recrutements d'élèves.

C'est peut-être déjà prévu mais il faudrait une fenêtre de fin qui apparaîtrait après le choix des avenirs des derniers étudiants pour pouvoir sauvegarder?, ouvrir les stats et revenir au menu principal.

**Comment by JulienNigon** [comment]
En cours de correction

**Comment by JulienNigon** [comment]
Done
