### ISSUE TITLE
Recrutement en masse après mort des étudiants

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#394]
[v0.72]
Je ne souhaite à personne que ça arrive mais si jamais tous les étudiants meurent - dans mon cas, attaque de 4 orcs avec peu d'étudiants - le jeu est très généreux en recrutement.
J'ai en effet eu le droit à plusieurs évènements de recrutement d'affilé ce qui m'a octroyé 42 nouveaux élèves alors que mon prestige était à 17.

Je précise tout de même que c'était une partie avec d'autres bugs (remontés dans d'autres topics) : le temps de l'année était figé à Année 0 : Hiver et c'était dans le monde de la forêt donc avec un problème de personnage qui ne pouvaient pas sortir de l'école (d'ailleurs les 4 premiers orcs tournaient en boucle près de ma prison).

**Comment by JulienNigon** [comment]
Ah oui c'est un peu bizarre. En tout cas ce n'est pas une volonté d'offrir autant d'étudiants. Je vais regarder.

**Comment by JulienNigon** [comment]
ça devrait être bon.
