### ISSUE TITLE
Eleve bloqué dans le monde des nuages

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#395]
[v0.72]
Cet élève a décidé de faire semblant de marcher sur place pour ne pas aller en cours !
![eleve_coince](https://user-images.githubusercontent.com/46971589/58649139-9d648400-830b-11e9-862d-ffe2bf19c718.jpg)

**Comment by JulienNigon** [comment]
Devrait mieux marcher...
