### ISSUE TITLE
Persos bloqués dans les murs

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#396]
[v0.72]
Des persos bloqués dans les murs, comme si les chemins étaient décalés.
Ça m'est arrivé une fois dans le monde Citadelle côtière mais ça n'a pas l'air d'être lié à ce monde là puisque j'ai pu tester d'autres parties sans problèmes.

![perso_bloque](https://user-images.githubusercontent.com/46971589/58649918-b110ea00-830d-11e9-888b-c0e1d5b84cd9.jpg)

![perso_bloque_dortoir_salleReposEleve](https://user-images.githubusercontent.com/46971589/58649932-bb32e880-830d-11e9-864e-a0cf4949ad4b.jpg)

**Comment by JulienNigon** [comment]
Devrait être résolu avec la dernière grosse mise à jour IA.
