### ISSUE TITLE
Eleve 'dummy' dans la forêt

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#397]
Il y a une sorte de marionnette de cire dans le monde de la forêt. Ce n'est pas très perturbant mais je ne suis pas sûr que ce soit normal
![eleve_dummy_foret](https://user-images.githubusercontent.com/46971589/58650118-24b2f700-830e-11e9-9e0c-ace1497f5a48.jpg)

**Comment by JulienNigon** [comment]
Il y en a qui vont se faire taper sur les doigts !
