### ISSUE TITLE
Salle avec toit et créneaux

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#398]
[v0.72]
Pour l'historique, j'ai placé le dortoir avant la salle à sa gauche mais je ne sais pas si le dortoir avait déjà cette configuration de toit quand il était seul
![creneaux_toit](https://user-images.githubusercontent.com/46971589/58650226-680d6580-830e-11e9-8592-fa28c9e5e125.jpg)

**Comment by JulienNigon** [comment]
Réglé ! Pfiuu... il était pas sympa celui là. Merci.
