### ISSUE TITLE
Debris fin du monde et colliders

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#399]
[v0.72]
La gestion de la fin du monde est toujours compliquée, surtout avec Unity :)
![bug_graphique_debris](https://user-images.githubusercontent.com/46971589/58650350-bd497700-830e-11e9-9d5b-72c40c460485.jpg)

![colliders_debris](https://user-images.githubusercontent.com/46971589/58650398-da7e4580-830e-11e9-9583-f41828328033.jpg)

[edit] pour un peu plus d'explications car les images sont statiques : les débris sont bloqués sur un plan invisible et continue à avoir de légers soubresauts

**Comment by JulienNigon** [comment]
Mouais mouais, bon c'est une partie qui est très work in progress :)
Je vais travailler sur ça.

**Comment by JulienNigon** [comment]
C'est bon normalement :). On retravaillera surement sur les météorites plus tard, mais ça ne devrait plus être buggé.
