### ISSUE TITLE
Erection de barbe chez les professeurs agés

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#400]
[v0.72]
Pas très pratique pour la vie quotidienne:
![erection_barbe_vieux_prof](https://user-images.githubusercontent.com/46971589/58650600-698b5d80-830f-11e9-8233-a0b745f699d3.jpg)

**Comment by JulienNigon** [comment]
Oups... les élèves restent bien calme face à ce truc :o

**Comment by JulienNigon** [comment]
C'est bon. On va arreter de perdre de la SAN.
