### ISSUE TITLE
Description des traits d'élève genrée en français

### ISSUE THREAD

**Issue by jeremy-boes** [JulienNigon/SpellcasterUniversity-Bug-Report#404]
En français dans la description des traits (appliqué, bavard, etc), le pronom "il" est systématiquement utilisé même quand il s'agit d'une fille. 

(je n'ai pas vérifié pour l'anglais)

**Comment by JulienNigon** [comment]
On a fait le choix de ne pas genrer les dialogues. C'est beaucoup trop de travaille au vu de la taille de l'équipe...

**Comment by jeremy-boes** [comment]
Du coup en anglais vous utilisez "they" ?
