### ISSUE TITLE
Monde du marais : des salles pré-existantes qui ne réagissent pas au clic

### ISSUE THREAD

**Issue by jeremy-boes** [JulienNigon/SpellcasterUniversity-Bug-Report#405]
Et par dessus lesquelles on peut installer d'autres salles, ce qui donne une architecture particulière à l'école.

![Sans titre](https://user-images.githubusercontent.com/42269011/58741040-3d5a0480-8415-11e9-9b6c-6df5d3fcbe54.png)

**Comment by JulienNigon** [comment]
Ouais. Vilain bug. Corrigé.
