### ISSUE TITLE
Changement de langue en jeu

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#406]
J'ai pu remarquer quelques comportements étrange quand on change la langue en jeu :
- Si on la change depuis le menu, les events et contacts cochonniers restent en anglais
- Si on la change depuis le jeu et qu'on relance une partie, quasiment tout reste en anglais sauf certains élements du hud

**Comment by JulienNigon** [comment]
Merci. Résolu.
