### ISSUE TITLE
bug de combat squelette vs prof

### ISSUE THREAD

**Issue by JulienNigon** [JulienNigon/SpellcasterUniversity-Bug-Report#420]

**Comment by LeBanc** [comment]
A ce sujet, j'ai eu un très très long combat entre un prof et un squelette a tel point que je le croyais infini.
Je ne sais pas si c’est ce problème là qui a été relevé.

**Comment by JulienNigon** [comment]
Si c'est ça.
Mais moi je crois qu'il était infini en effet.
