### ISSUE TITLE
Page des succes steam

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#436]
Quand on clique sur "Afficher tous les succès" dans Steam, on se retrouve sur la page de notre profil et pas sur la page des succès.
Ce n'est peut-être pas un bug puisque l'adresse à l'air bonne (https://steamcommunity.com/profiles/xxxxxxxxxxxxxxxxx/stats/appid/895620/achievements) mais je le signale au cas où.
C'est peut-être dû au fait que le jeu n'est pas officiellement sorti ?

**Comment by JulienNigon** [comment]
Effectivement, je ne suis pas bien sûr d'avoir la main sur ça.
