### ISSUE TITLE
Path dans les rochers à la plage

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#437]
[v0.73]
Le chemin d'entrée/sortie de la plage fait passer les persos à travers des rochers :
![cotier_path_dans_rochers](https://user-images.githubusercontent.com/46971589/59212345-6cf5d300-8bb2-11e9-8910-c0c9aca23e64.jpg)
(le prof bedonnant en haut à droite, le reste c'était pour un autre point)

**Comment by JulienNigon** [comment]
Done
