### ISSUE TITLE
Plantage et fermeture du jeu

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#439]
[v0.73]
Je viens de faire 2 parties qui se sont brutalement terminées au bout d'environ 1 heure.
Fermeture du jeu sans préavis, pas de possibilité d'analyser un début de piste.

Je me rappelle avoir eu un problème similaire sur la démo (mais au bout de plus longtemps) mais ça ne me l'avait pas fait sur la version précédente dispo sur Steam.

**Comment by JulienNigon** [comment]
C'est difficile d'en être sûr, mais de nombreux points d'instabilité ont été corrigés et ce phénomène ne semble plus se reproduire. Je le ferme pour l'instant, mais on garde un œil la dessus.
