### ISSUE TITLE
Perte prestige lors de l'évènement des parents

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#440]
Lors de l'évènement avec les parents qui questionnent la discipline dans l'école, je trouve la quantité de prestige perdu trop élevée en début de partie.

J'ai par exemple déjà eu l'évènement deux fois assez rapidement en début de partie et -10 de prestige, ça pique !
Je me demandais si le nombre de points de prestige perdus pourraient s'indexer sur le prestige actuel. Une perte de 10% à 20% (arrondi à l'entier supérieur) par exemple, ce qui au début du jeu fait une perte de 1 à 3 points mais peut vite monter au fil de la partie.

**Comment by JulienNigon** [comment]
Oui, ça serait surement une assez bonne façon de faire. On réfléchi aux différentes pistes.

**Comment by JulienNigon** [comment]
Adopté et implémenté. Live dans la prochaine version.
