### ISSUE TITLE
Squelette bloqué

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#443]
[v0.73]
Un squelette a apparemment décidé qu'il préférait admirer l'école depuis le champ plutôt que de l'attaquer. J'ai trouvé ça sympa de sa part mais je ne suis pas sûr que le seigneur du mal apprécie.

Monde avec le château (quand on le sélectionne sur la carte), le squelette marche sur place, indéfiniment :
![chateau_squelette_bloque](https://user-images.githubusercontent.com/46971589/59213845-1ab6b100-8bb6-11e9-90de-47442e2fa0a2.jpg)

**Comment by JulienNigon** [comment]
Le seigneur du mal n'est absolument pas content !

**Comment by JulienNigon** [comment]
Le seigneur du mal a réglé définitivement le problème de ce squelette...
