### ISSUE TITLE
Porte entre les mondes, entre les murs

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#444]
[v0.73]
Le placement de la porte entre les mondes dans une salle interdimensionnelle est spécial.
Non pas que l'objet ne soit pas vertical, mais parce qu'il traverse le mur.
D'ailleurs je n'ai pas testé avec un autre objet.
![porte_entre_les_mondes](https://user-images.githubusercontent.com/46971589/59214052-9153ae80-8bb6-11e9-8ed7-c3d8f3faa0a5.jpg)

**Comment by JulienNigon** [comment]
Enfin résolu. Le tissu même de la réalité est sauvé.
