### ISSUE TITLE
Impossible de placer équipement

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#452]
v 0.73 Stupid Kobold

Impossible de placer les équipements de type coffre alors qu'on me dit que c'est possible. J'ai pas vérifié si les salles que j'avais d'installé ont vraiment cet emplacement.

![20190702192325_1](https://user-images.githubusercontent.com/15092739/60534167-7aa9fe80-9d01-11e9-8d81-0e7eaf1d372b.jpg)
![20190702192329_1](https://user-images.githubusercontent.com/15092739/60534168-7aa9fe80-9d01-11e9-9383-3a9851eadcda.jpg)
![20190702192514_1](https://user-images.githubusercontent.com/15092739/60534169-7b429500-9d01-11e9-9b8d-5c95a056d012.jpg)
![20190702192700_1](https://user-images.githubusercontent.com/15092739/60534170-7b429500-9d01-11e9-935a-0bc2babdd894.jpg)
![20190702192726_1](https://user-images.githubusercontent.com/15092739/60534171-7b429500-9d01-11e9-89a4-14bb9956f1d1.jpg)
![20190702192728_1](https://user-images.githubusercontent.com/15092739/60534172-7b429500-9d01-11e9-83e0-e489f7d92a4f.jpg)

**Comment by JulienNigon** [comment]
Je n'arrive pas à le reproduire.

**Comment by JulienNigon** [comment]
Forte présomption de bug en cascade.
