### ISSUE TITLE
Eleves et profs bloqués

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#453]
v 0.73 Stupid Kobold
La quasi-totalité de mes élèves et professeurs sont bloqués dans les murs. C'est arrivé assez rapidement, on dirait que c'était quand j'ai construit le dolmen. J'ai essayé de faire passer du temps mais ça fait rien on dirait.

![20190702193149_1](https://user-images.githubusercontent.com/15092739/60534468-2fdcb680-9d02-11e9-8f96-b831ba768391.jpg)
![20190702193212_1](https://user-images.githubusercontent.com/15092739/60534469-2fdcb680-9d02-11e9-933b-d3cef80c74fa.jpg)
![20190702193349_1](https://user-images.githubusercontent.com/15092739/60534470-30754d00-9d02-11e9-97e2-33e3df8a5ebe.jpg)
![20190702193416_1](https://user-images.githubusercontent.com/15092739/60534472-30754d00-9d02-11e9-9dfc-2b9bb78ccbb6.jpg)

**Comment by JulienNigon** [comment]
Devrait être résolu.
N'a pas été reproduit en interne depuis d'importants correctifs d'IA.
