### ISSUE TITLE
Eleves microscopiques

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#460]
Cela est arrivé durant une attaque de squelettes (l'event "les astres sont alignés").

![20190729100638_1](https://user-images.githubusercontent.com/15092739/62033135-9793fd80-b1eb-11e9-805d-ff62286ee284.jpg)

![20190729101343_1](https://user-images.githubusercontent.com/15092739/62033156-a1b5fc00-b1eb-11e9-85a8-f7f1456833b6.jpg)

![20190729101408_1](https://user-images.githubusercontent.com/15092739/62033166-a8447380-b1eb-11e9-8d38-e843f9db45df.jpg)

Une fois réduits, ils ont l'air assez prédisposés à se coincer. Ils n'ont pas l'air de regagner leur taille :(

v 0.74 Swamp Hag

**Comment by JulienNigon** [comment]
Très très bizarre celui là...
