### ISSUE TITLE
Il est possible de jouer des cartes lors de l'event de début

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#461]
Cela met la vitesse a x1. On peut ensuite tout faire. Si on pioche une carte, la pause est remise et on ne peut plus jouer d'autres cartes avant la résolution de l'event. Je n'ai testé que sur la côte et le marais mais je pense que c'est généralisable à toutes les maps.

![20190729093822_1](https://user-images.githubusercontent.com/15092739/62033601-9e6f4000-b1ec-11e9-9cbb-2139f9c121a2.jpg)

v 0.74 Swamp Hag

**Comment by JulienNigon** [comment]
Oui. C'est généralisable.
