### ISSUE TITLE
The teachers are dissapearing

### ISSUE THREAD

**Issue by nilsbrummond** [JulienNigon/SpellcasterUniversity-Bug-Report#467]
The teachers keep leaving the map and not returning.  So no classes are being taught and my students graduate as peasants since they learned nothing.

I have found if a portal is opened then 1 teacher will return to close it and the leave again right after.

I have followed the teachers as they leave the map.  They always have high levels of hunger, Tiredness and Boredom.  The get to the edge of the map behind a hill, etc. and stay there forever it seems...  See image of the teacher just standing there:

![image](https://user-images.githubusercontent.com/1744310/62428710-599a4c00-b6b9-11e9-9407-8bd266ac2926.png)

While the teacher stands at the edge of the map, I never see the bars recover.  I can not watch for long as events will cause me to loose focus on the teacher...  So I can not tell exactly what happens after a longer period.

But this seems to happen to all of my teachers right now, on multiple games with different start locations.

**Comment by JulienNigon** [comment]
Thanks for this issue. Normally the current version no longer makes this bug. This was due to an unfortunate change in the teachers' AI. That didn't make them any smarter...
