### ISSUE TITLE
Pb recrutement salles de l'Ombre

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#475]
v 0.75 Shadow Empress

Vraiment bizarre, pour toutes les salles de l'ombre (sauf la salle des assassins) le recrutement ne montre pas les bonnes informations pour chaque prof.

![20190824204028_1](https://user-images.githubusercontent.com/15092739/63641864-7c66c180-c6b5-11e9-8734-6095abc78d8f.jpg)
![20190824204243_1](https://user-images.githubusercontent.com/15092739/63641866-838dcf80-c6b5-11e9-964b-678f848cbd22.jpg)
![20190824204612_1](https://user-images.githubusercontent.com/15092739/63641870-8e486480-c6b5-11e9-963f-6155f4f92aa5.jpg)
![20190824204628_1](https://user-images.githubusercontent.com/15092739/63641871-943e4580-c6b5-11e9-84a3-7a956d96ea08.jpg)
![20190824205226_1](https://user-images.githubusercontent.com/15092739/63641876-a324f800-c6b5-11e9-8387-f51e63c20af1.jpg)
![20190824205635_1](https://user-images.githubusercontent.com/15092739/63641877-a7e9ac00-c6b5-11e9-9277-f9635c32240c.jpg)

**Comment by JulienNigon** [comment]
Systématiquement? Ou dans une partie particulière?

**Comment by Fouindor** [comment]
Dans une seule partie, samedi j'ai commencé à tester le mode campagne et j'ai fait qu'un tableau pour l'instant, je n'ai pas eu l'occasion de vérifier si on pouvait le reproduire facilement.

**Comment by Fouindor** [comment]
Test v0.78 Mysterious Dragonborn:
Deux parties, la première OK, dans la seconde j'ai eu le soucis avec le concierge :

![20190914115908_1](https://user-images.githubusercontent.com/15092739/64906554-6d899280-d6e8-11e9-9acd-731db85c3cdc.jpg)

Absolument aucune idée de ce qui peut déclencher ça :(

EDIT : Rien à voir mais la barbe du concierge de gauche est simplement glorieuse.

**Comment by Fouindor** [comment]
v 0.82 Fat Goblin
Toujours aucune idée de ce qui déclenche ça :( 

![20191012134009_1](https://user-images.githubusercontent.com/15092739/66701233-5b583f80-ecfa-11e9-8a07-8393ecb1933b.jpg)
![20191012134028_1](https://user-images.githubusercontent.com/15092739/66701235-5c896c80-ecfa-11e9-9018-fde465f82b17.jpg)

**Comment by Fouindor** [comment]
Vu sur v0.84
![20191111125100_1](https://user-images.githubusercontent.com/15092739/68585702-4ac6f080-0483-11ea-854d-01ac7b9646eb.jpg)

**Comment by JulienNigon** [comment]
Ce bug est l'ennemi numéro 1 en ce moment. Toute info nous intéresse beaucoup.
