### ISSUE TITLE
placement du cochon dans la catapulte

### ISSUE THREAD

**Issue by FlynFlykk** [JulienNigon/SpellcasterUniversity-Bug-Report#489]
J'ai remarqué que ce n'etait plus aussi bien qu'avant, je me dit que c'est peut etre ma faute lorsque j'ai renomé le p_grochondinde messager en p_cochondinde (pour pouvoir creer le Grochondinde domestique qui marche dans les couloir) j'ai peut etre cassé un lien dans ton script? :(
![image](https://user-images.githubusercontent.com/14259450/63856891-fabbb000-c9a2-11e9-8366-27213d7dfb9b.png)

**Comment by FlynFlykk** [comment]
oh non ça a empiré :( 
![image](https://user-images.githubusercontent.com/14259450/63866721-f3e96900-c9b3-11e9-8d92-fb75dfa557e4.png)

**Comment by JulienNigon** [comment]
Pffff... :(
