### ISSUE TITLE
Chargement d'une partie

### ISSUE THREAD

**Issue by lizianna** [JulienNigon/SpellcasterUniversity-Bug-Report#527]
Bonjour/Bonsoir

Je viens signaler le fait qu'il m'est **impossible de charger ma partie de Campagne (alpha)**.
La partie se lance, la barre du bas est visible (avec les cartes, les points de magies...), le paysage également, mais aucune trace du château et de ses occupants.
Le temps semble freezer un peu également, comme s'il avait du mal à se lancer.
Puis au bout de 15-30 sec, le jeu se ferme de lui-même.

Voilà, bonne semaine !

**Comment by JulienNigon** [comment]
Bien reçu. Désolé pour ce soucis. Nous allons enquêter de ce pas.

Merci beaucoup !

**Comment by JulienNigon** [comment]
Merci beaucoup pour ce retour. Nous enquêtons sur le problème. Désolé pour le soucis...

**Comment by lizianna** [comment]
Bonne continuation !

**Comment by Fouindor** [comment]
Comportement similaire quand j'essaie de charger ma campagne débutée en v0.76 alors que je suis en v0.78, c'est peut-être du à une incompatibilité des sauvegardes entre versions ? (pas impossible vu que le bug à été reporté autour de la sortie de la v0.77)

**Comment by JulienNigon** [comment]
Le patch de ce soir devrait résoudre un certain nombre de problèmes de sauvegarde, tout en restant rétrocompatible. N'hésitez pas à essayer de recharger votre partie.
