### ISSUE TITLE
Evenement "Boite Torrefactrice" - Or non débité

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#535]
v0.78 Mysterious Dragonborn

Cet événement est maudit 😛 

Si on choisit d'acheter la machine à café, l'or n'est pas débité 👍 
![20190914111905_1](https://user-images.githubusercontent.com/15092739/64906500-b4c35380-d6e7-11e9-92be-6c1b6b8069d4.jpg)
![20190914111906_1](https://user-images.githubusercontent.com/15092739/64906501-b4c35380-d6e7-11e9-82f7-cd19cef1b5e5.jpg)

Dans le même genre dans le même event, la carte alcool n'a pas l'air d'être débitée non plus :
![20190914111412_1](https://user-images.githubusercontent.com/15092739/64906509-d02e5e80-d6e7-11e9-8edc-27b156c61ca1.jpg)

**Comment by JulienNigon** [comment]
On a fait venir un exorciste, c'est bon.
