### ISSUE TITLE
Chat bloqué

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#536]
v0.78 Mysterious Dragonborn
Une fois posé, le chat est allé se bloquer sur une table pour tout le reste de la partie :(
![bloque2](https://user-images.githubusercontent.com/15092739/64906521-f7852b80-d6e7-11e9-9359-b8c091a356c7.gif)

Je sais pas si c'est moi qui suis méfiant, mais j'ai l'impression que les NPC ont tendance à "s'accrocher" autour de cette table (j'ai pas pu capturer).

**Comment by LeBanc** [comment]
J'ai eu un problème similaire avec le chat sauf que moi il s'est bloqué au milieu d'une porte et que ça a bouché le passage pour tous les élèves et professeurs pour le reste de ma partie !
![chat_porte](https://user-images.githubusercontent.com/46971589/64924579-955f2000-d7e6-11e9-8ea0-4ea671438523.jpg)
