### ISSUE TITLE
Clef inexistante sur effet gaufre dans fiche de perso

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#538]
Tout est dans le titre !
J'ai un message "Clef inexistante" sur ce qui me semble être une gaufre (effet temporaire du gaufrier maléfique) dans la fiche de perso de mes élèves.

**Comment by JulienNigon** [comment]
C'est pour ça qu'il ne faut pas les nourrir avec des gaufres!

Merci pour tous les retours ;)
