### ISSUE TITLE
fôtes de phrapes et d'ortograf

### ISSUE THREAD

**Issue by LeBanc** [JulienNigon/SpellcasterUniversity-Bug-Report#539]
J'ai vu 2 petites coquilles en 0.78:
- Dans la quête Une spécialité pour l'école, un vilain "s" s'est glissé à la fin de "fera" dans le 3eme choix "L'alchimie feras ..."
- Le "professeur d'stronomie" a déjà la tête dans les étoiles et à maladroitement oublié la première lettre de sa matière (dans les fiches de perso et choix des professeurs)

**Comment by JulienNigon** [comment]
Jeu conprand pa pourten l'ékip et trais bone an aurtograf...
