### ISSUE TITLE
Bug bouton sauvegarde

### ISSUE THREAD

**Issue by lizianna** [JulienNigon/SpellcasterUniversity-Bug-Report#581]
Bonjour/Bonsoir,

Au moment de sauvegarder ma partie, le bouton "sauvegarder" ne réagissait pas, impossible de sauvegarder alors que ça marchait très bien jusque là.
De même, le bouton "quitter" ne réagissait pas non plus.
Les boutons "options" et "retour" marchaient.

J'en profite pour glisser que le niveau de son de la musique revient toujours à zéro quand on relance une partie, obligeant à le diminuer à chaque lancement de jeu. Je ne sais pas si c'est normal.

Amicalement

**Comment by JulienNigon** [comment]
Bonjour,

Pour l'instant notre enquête sue le premier soucis (sauvegarde / quitter) n'a encore mené à aucun résultat concluant. Nous poursuivons notre recherche.

Nous avons réglé le problème de la musique dans le prochain patch qui devrait être distribué ce soir.

Un grand merci pour vos retours !
