### ISSUE TITLE
Bug - Students and Staff getting stuck going back and forth through doors

### ISSUE THREAD

**Issue by Wonderousmilksnake** [JulienNigon/SpellcasterUniversity-Bug-Report#584]
Sorry if this is already created, can't read French. A portion of the staff and students inevitably seem to get stuck going back and forth through doors (on two different campaign levels so far), might be linked going from a small room to a large one or vice versa.

**Comment by OhrEinSof95** [comment]
Same problem here, saving, going to menu and entering the campaign again seems to solve the problem temporarily.
![error](https://user-images.githubusercontent.com/51261969/65818048-14ece600-e20e-11e9-8913-945d9357e7a4.png)

**Comment by CelastrinaLadon** [comment]
I found this problem too

**Comment by Exsadus** [comment]
It happen %100 of time when i place time hall. It sometimes happen random on random rooms. Concerning issue.

**Comment by calamityson** [comment]
![studentsstuck](https://user-images.githubusercontent.com/56685332/67013117-e36f8800-f0f2-11e9-948e-16783693c988.png)

still happening, even with special care of the room construction an no low-exit rooms next to each other.

**Comment by JulienNigon** [comment]
This bug is the most urgent problem we are dealing with at the moment. It is related to many other bugs that scatter the navigation system, and we are in the process of deploying a complete upgrade of this system. All your feedback is very useful to us. Thank you.

**Comment by JulienNigon** [comment]
And sorry.
