### ISSUE TITLE
Game gets stuck when placing building

### ISSUE THREAD

**Issue by Beacon80** [JulienNigon/SpellcasterUniversity-Bug-Report#586]
Occasionally my game will not let me place a building, despite clicking on a valid spot. This leaves me stuck, as I can't back out, either One time I was able to bring up the escape menu, quit to title screen, and quickly resume playing, but most of the time I need to alt-tab out and close the game entirely

**Comment by JulienNigon** [comment]
Should be fixed on next updates (coming next week). Thanks for your feedback.
