### ISSUE TITLE
Elementalists Dojo increasing all Arcane specialties

### ISSUE THREAD

**Issue by RADTrooper** [JulienNigon/SpellcasterUniversity-Bug-Report#587]
The teachers for the Elementalists Dojo are increasing all three Arcane magic fields instead of just the Elementalism one.  The room appears to be functioning like the Arcana classroom rather than one of the specialty rooms. 

The map where I first noticed this was on the lake in Campaign mode.

**Comment by JulienNigon** [comment]
Thanks for the feedback! Tonight update will fix that.
