### ISSUE TITLE
Teachers Stuck in Endless Loop

### ISSUE THREAD

**Issue by JPWallow** [JulienNigon/SpellcasterUniversity-Bug-Report#591]
While playing my teachers got stuck in an endless loop of entering and leaving the door between the guidance office and the teacher chamber (Light card for 7 teachers to relax between classes). They won't go back to their classrooms or sit down to rest. They are all just stuck at the door. 
![Screenshot 2019-09-30 00 01 19](https://user-images.githubusercontent.com/55968853/65848785-a72be180-e315-11e9-9828-edf2a7427b7a.png)

**Comment by JPWallow** [comment]
Here is another Screenshot. It looks like they cant use the room. 
![Screenshot 2019-09-30 00 06 03](https://user-images.githubusercontent.com/55968853/65848914-2f11eb80-e316-11e9-9c88-095262cd4096.png)

**Comment by JulienNigon** [comment]
Thanks ! This was a hard one. Next release (tomorrow) should fix that.
