### ISSUE TITLE
Réputation Inquisition à 0 mais dialogue pirate bloqué

### ISSUE THREAD

**Issue by jeremy-boes** [JulienNigon/SpellcasterUniversity-Bug-Report#594]
J'essaie de faire la quête où je dois avoir 90 de réput auprès des pirates.

J'ai toujours envoyé paître l'inquisition, j'ai -100 de réput avec eux.
Mais depuis que j'ai atteint -100, l'option de dialogue des pirates où je peux leur filer une carte des monastères à piller n'est plus dispo.

**Comment by jeremy-boes** [comment]
hmm ou alors j'ai besoin d'avoir plus que -50 en réput avec l'inquisition ?
Je comprenais qu'il fallait < à -50 en fait.

Oublie-moi.

**Comment by JulienNigon** [comment]
Compris ^^
