### ISSUE TITLE
Impossible de continuer ma partie

### ISSUE THREAD

**Issue by jeremy-boes** [JulienNigon/SpellcasterUniversity-Bug-Report#595]
Le jeu crashe quand je clique sur "Continuer [nom de mon université]" dans le menu principal et qu'il n'arrive pas à charger. 

Voilà la dernière chose que je vois :

![temp](https://user-images.githubusercontent.com/42269011/66061010-e7ba7380-e53e-11e9-8af2-28d1ed0b528a.png)

Il semble que certains assets soient littéralement décuplés (genre le faune sur la gauche et les étudiants.

Et la sauvegarde n'apparaît pas quand je clique sur charger, donc aucun moyen de récupérer cette campagne, snif.

**Comment by JulienNigon** [comment]
Devrait être corrigé. Sorry.
