### ISSUE TITLE
School names changing lanuage

### ISSUE THREAD

**Issue by WraithBAD** [JulienNigon/SpellcasterUniversity-Bug-Report#601]
When setting up a school, the discipline types are in english, and then when reviewing in the menus, a few of them change to another language.

**Comment by Nezumi72** [comment]
Also seeing language changes.
![language selection bug](https://user-images.githubusercontent.com/34515152/66250964-839ad980-e70f-11e9-90b0-f61d72e77597.png)
![language selection bug2](https://user-images.githubusercontent.com/34515152/66250965-839ad980-e70f-11e9-9067-37ff8751ceb9.png)

**Comment by JulienNigon** [comment]
Fixed psy card.

**Comment by JulienNigon** [comment]
And done with house list. Many thanks for this report. The fix will be released in a few hours.
