### ISSUE TITLE
Malédiction d'antimagie : 1% de perte de gain au lieu de 10%

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#622]
v 0.82 Fat Goblin

J'ai choisi la malédiction d'antimagie à la fin d'un tableau (réduit les gains de magie de 10% et augmente les gains d'or de 20%).

Au début du nouveau tableau, je choisis la réponse qui me fait gagner 100 de mana de nature (1er evt paysans), je devrais en gagner que 90. Or j'en ai gagné 99:

![20191012131536_1](https://user-images.githubusercontent.com/15092739/66701180-c5bcb000-ecf9-11e9-807f-24cfe0a4aa2c.jpg)

**Comment by JulienNigon** [comment]
Je l'ai testé avec succès. Peut être as tu d'autres effets en cours?
