### ISSUE TITLE
Personnages coincés au milieu des murs

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#623]
v 0.82 Fat Goblin

C'est arrivé sur un seul tableau. Ils ne se décoincent pas.

![20191012132656_1](https://user-images.githubusercontent.com/15092739/66701321-6c558080-ecfb-11e9-8326-a6c8c0fa7096.jpg)
![20191012132055_1](https://user-images.githubusercontent.com/15092739/66701324-724b6180-ecfb-11e9-8d10-e064ab1c0a53.jpg)
![20191012133128_1](https://user-images.githubusercontent.com/15092739/66701326-78414280-ecfb-11e9-9caf-9750d8653db8.jpg)
![20191012133507_1](https://user-images.githubusercontent.com/15092739/66701330-82634100-ecfb-11e9-837d-7e97ca046e0c.jpg)

**Comment by JulienNigon** [comment]
Should be fixed on next release. Thanks !
