### ISSUE TITLE
Carte alcool "inexistante"

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#640]
v 0.83 Shadow Priest
Vraiment étrange... j'ai donné 1 alcool pour faire taire les profs lors de l'évenement "Boite Torrefactrice" mais la carte n'a pas l'air de vouloir partir, je ne peux pas la mettre dans le chaudron ou la jeter, elle reste toujours à la même place et peut chevaucher une autre carte.

J'ai déjà donné de l'alcool à des profs sans problème (sorti de son contexte c'est bizarre xD)

![20191024201312_1](https://user-images.githubusercontent.com/15092739/67517861-d24eea00-f6a3-11e9-8957-146b98572056.jpg)

Au bout d'un moment j'ai pu la mettre dans le chaudron:
![20191024202958_1](https://user-images.githubusercontent.com/15092739/67517936-f4486c80-f6a3-11e9-9851-d888ed2f4de2.jpg)

**Comment by JulienNigon** [comment]
Bien vu. Et arrête de donner de l'alcool aux profs ! :)
