### ISSUE TITLE
Besoins des profs en mode Endless

### ISSUE THREAD

**Issue by Zirgantz** [JulienNigon/SpellcasterUniversity-Bug-Report#641]
Salut, j'ai remarqué qu'en mode Endless les besoins du personnel sont toujours au maximum. Si je construis une salle des profs, leurs besoins baissent normalement, et puis dès qu'ils ont terminé les besoins se remettent immédiatement au max. 

Du coup ça crée une situation assez cocasse où tout mon personnel est constamment en salle des profs et où de temps en temps il y en a un qui se lève pour se dégourdir les jambes dans la pièce d'à côté, à la limite fermer un petit portail ou éteindre un feu quelque part, et puis il se reprend deux heures de pause. C'est très réaliste, ça m'a bien fait rigoler, et je conçois que vous ayez pu prendre le parti de représenter les grèves de la fonction publique française dans votre travail, mais en vrai ça m'a plutôt l'air d'un bug et ça casse un peu le jeu.

**Comment by JulienNigon** [comment]
Bonjour. Un grand merci pour ce retour. Je vais essayer de reproduire le bug pour le corriger... car oui c'est effectivement un bug et non une satyre. Malheureusement...
