### ISSUE TITLE
Problème menu + sauvegarde 

### ISSUE THREAD

**Issue by Raelags** [JulienNigon/SpellcasterUniversity-Bug-Report#654]
Bonjour , pour commencer bravo , c'est une perle ce jeu 
Très bien pensé avec bcp de façon de jouer différente
Cependant quelque bug viennent limité le plaisir de cette expérience : le menu lorsqu'on appuis sur echap ne fonctionne pas , impossible donc de sauvegarder ou de revenir au menu ce qui est très contraignant obligeant a recommencer a chaque lancement de jeu , et ne me permettant pas d'avancer dans la campagne .

Bon courage pour le développement :)

**Comment by JulienNigon** [comment]
Navré pour les bugs. Nous sommes encore en alpha et il est vrai que chaque jours amène son lot de bugs inattendus :). Merci pour votre retour, c'est effectivement un bug très lourd... pourrais-je savoir sur quel système vous jouez?

**Comment by EnteWane** [comment]
Bonjour,
J'ai exactement le même soucis. Sur le menu en jeu, aucune des fonctionnalité ne fonctionne hormis "annuler"
De plus, je ne sais pas si cela est lié, mais à la fin de ma première mission sur la campagne, appuyer sur "Finir la partie" n'avait également aucun effet

Bon courage et merci d'avance :)

**Comment by Raelags** [comment]
> Navré pour les bugs. Nous sommes encore en alpha et il est vrai que chaque jours amène son lot de bugs inattendus :). Merci pour votre retour, c'est effectivement un bug très lourd... pourrais-je savoir sur quel système vous jouez?

Bonjour 
je suis sur window 10
Continuez comme ca :)

**Comment by LaurenceKo** [comment]
Hello!

Déjà bravo pour ce jeu il est vraiment chouette. Je rencontre le même problème, le seul bouton qui marche dans le menu de "partie normale" est "annuler". Impossible d'utiliser les autres.

Je suis sur Windows 8
