### ISSUE TITLE
Salle Directeur - Volcan

### ISSUE THREAD

**Issue by McTheFlash** [JulienNigon/SpellcasterUniversity-Bug-Report#655]
Bonjour !
Deja je voulais vous dire bravo pour votre jeu ! Il est vraiment fun a jouer et super original !

J'ai rencontré un petit probleme lors d'un debut de partie sur la carte volcan : la croix pour fermer le bureau du directeur (pour avoir acces au reglement) ne marche pas ! Du coup impossible de retourner a la gestion de l'ecole, et obligé de tout recommencer.

Merci et bravo encore !

**Comment by Kazeid** [comment]
J'ai le même problème.

**Comment by JulienNigon** [comment]
Mince. Désolé pour ce soucis, nous allons y jeter un œil.

Pour passer outre, vous pouvez faire un clique droit dans n'importe quel menu pour revenir en arrière. Cela devrait vous permettre de quitter le bureau du directeur.

**Comment by Flomelle** [comment]
J'ai également rencontré le même problème.

**Comment by Maeltra** [comment]
Vous pouvez utiliser le clique droit de la souris pour quitter n'importe quel menu et aussi fermer les fenetres de prof / élèves en attendant que ça soit patché, au moins pas besoin de tout recommencer

**Comment by JulienNigon** [comment]
Ce problème sera fixé dans le hotfix que nous sortons dans deux heures environ. Merci encore de nous l'avoir fait remonter.

Et +1 pour la solution de Maeltra en attendant.
