### ISSUE TITLE
Professeur coincé dans un mur

### ISSUE THREAD

**Issue by Lokatem** [JulienNigon/SpellcasterUniversity-Bug-Report#656]
La création d'une nouvelle salle a décalé un professeur sur le côté et l'a coincé dans le mur extérieur de la salle. Il ne peut pas en sortir. Quitter la partie et la recharger ne corrige pas le problème.

**Comment by Sansse13** [comment]
J'ai eu un problème similaire, le prof de la salle d'orientation est resté bloqué dans le mur durant toute ma partie
![bug spellcaster](https://user-images.githubusercontent.com/60476500/73461196-0bb98480-437a-11ea-961c-3751e5544bb1.png)
