### ISSUE TITLE
Besoin prof instantanément plein

### ISSUE THREAD

**Issue by Truong-Terence** [JulienNigon/SpellcasterUniversity-Bug-Report#659]
Bonjour,

A chaque partie à environ 1/4 du temps, les professeurs ne peuvent plus faire cours car dès qu'ils entrent en classe toutes leurs jauges sont instantanément remplies. Du-coup bah y a pas de cours :'(

Bon courage

**Comment by StouneB** [comment]
J'ai le même problème, j'ai remarqué que plus le temps passe plus les besoins des prof monte vite.
Je suppose que plus ils ont d'éleves plus leur besoin monte vite et que cette vitesse n'est pas remis à zéros une fois le cour terminé. 
Du coup c'est assez frustrant, les élèves arrivent à peine dans la salle que le prof est déja parti.

Du coup pro tips, sauvegarder et relancer sa sauvegarde refait avancer la barre des besoins à leur vitesse d'origine

**Comment by molinadt** [comment]
Problème similaire pour moi : une de mes prof a ses barres de faim et fatigue qui se emplissent instantanément dès qu'elle se met derrière son bureau.

**Comment by danazen30** [comment]
Bonjour j'ai le même probleme et j'ai remarqué qui commencer a partir de la difficulter sorcier, sa m'arrive aussi de voir les jauge qui se remplissent juste beaucoup trop vite merci de regler le problème rapidement parce que super jeu sinon :)

**Comment by alexolio** [comment]
Super jeu mais j'ai ce bug des profs qui ont leurs besoins qui montent instantanément dès qu'ils rentre dans leurs salle de cours (alors qu'ils sont leurs barres de besoins vide). J'essaye de jouer en difficile (mage) mais impossible avec ce bug. Merci les gars pour votre jeu !! bonne continuation !

**Comment by JulienNigon** [comment]
Merci pour tout vos retours !
C'est très étonnant et cela semble un bug répandu depuis la dernière mise à jour. Ce bug est classé prioritaire pour le prochain patch qui arrive d'ici une dizaine de jours, je vais faire ce que je peut pour le corriger d'ici là.
Navré que cela ai entaché vos parties.

**Comment by alexolio** [comment]
Cool j'ai hâte d'y rejouer avec le correctif et de voir les prochaines maj.
Merci encore pour cette expérience de jeu !

Le mar. 28 janv. 2020 à 21:21, Julien Nigon <notifications@github.com> a
écrit :

**Comment by DarkAthanor** [comment]
Bonjour,

même problème : c'est comme si les prof recevait de la fatigue et de l'ennui en fonction de l'intégralité des élèves de l'académie au lieu de se contenter des élèves en classe

**Comment by JulienNigon** [comment]
Nous allons essayer de sortir un hotfix dès ce soir pour ce problème. On vous tiens au courant.

**Comment by JulienNigon** [comment]
(c'était corrigé... j'ai oublié de fermer l'issue)
