### ISSUE TITLE
L'entiereté de la map est bloquée sur la droite de l'écran

### ISSUE THREAD

**Issue by Mikashi666** [JulienNigon/SpellcasterUniversity-Bug-Report#667]
Lorsque je lance une partie et ce, peut importe l'endroit sur la carte du monde, la map se charge et se met complètement à droite, impossible de voir l'école et de placer quoique ce soit où que ce soit. J'ai redémarré le jeu, essayé en mode campagne ou non et rien ne change.

**Comment by Neelan22** [comment]
Bonjour,
Désolé pour le bug, nous enquêtons dessus...

**Comment by Drakeonis** [comment]
Hello
Exactement le même bug que toi ! Si on peut faire remonter ça car pour l'instant je ne peux pas tester le jeu ni faire remonter d'autres bugs ^^
Merci !

**Comment by JulienNigon** [comment]
Normalement corrigé. N'hésitez pas à nous signaler le contraire. Merci et encore navré.
