### ISSUE TITLE
Une petite faute d'orthographe ^^'

### ISSUE THREAD

**Issue by Mahiighan** [JulienNigon/SpellcasterUniversity-Bug-Report#670]
Bonjour les développeurs ! 
Rien de grave, rassurez-vous ! 
J'ai juste remarqué une petite faute d'orthographe dans le tutoriel. 
Lorsque le jeu nous montre les différents menus à notre disposition et notamment celui du bureau du directeur. Dans la fenêtre pop-up qui nous présente l'onglet "Bureau du directeur", la faute se trouve à "son" : il est écrit "sonT niveau d'étude", or il n'y a pas de "T". 
Voilà voilà :)
Bien cordialement ! 
(Sinon, le concept et les graphismes du jeu sont top (hormis quels bugs mais ça n'engage pas beaucoup l'expérience du jeu pour le moment) 
Mahiighan ;)

**Comment by JulienNigon** [comment]
Ahh ! Un tout petit bug ! Cela fait plaisir à lire :)
Merci pour le retour et pour le soutien, c'est cool.
