### ISSUE TITLE
Bug <fin de campagne>

### ISSUE THREAD

**Issue by Mineacid3** [JulienNigon/SpellcasterUniversity-Bug-Report#677]
Bonjour 
J'ai eu un bug : en relançant une nouvelle campagne après avoir fini une campagne complète, à la fin du premier monde de ma seconde campagne ça affiche l’échec de la campagne, rien n'y fais, obligé de recommencer une nouvelle campagne. Voilà si cela peu vous aider ;)

**Comment by Mineacid3** [comment]
De plus je voulais ajouter le fait qu'aucune de mes cartes objets ( ailes, bâton magique, auréole etc n'a d'effet ) Apres plusieurs vérifications sur les élèves concernés , cela n'affiche nul part les effet décrit sur les cartes objets, a moins que je ne sais pas m'en servir ou les utiliser ? j'ai constater aussi plusieurs autres bug déjà décrit sur ce bug-report  que je ne vais pas détaillé ;) 
En tout cas bon courage a toute l'équipe car ce jeu est vraiment super et promet d'être encore meilleur, bravo a tous <3

**Comment by Neelan22** [comment]
Bonjour,
ok merci pour ces retours, nous allons enquêter...
merci pour ton soutien !

**Comment by JulienNigon** [comment]
Le bug de la campagne est corrigé. Nous allons réfléchir à donner un mmeilleur feedback aux artefacts. Merci beaucoup !
