### ISSUE TITLE
bug au demarrage

### ISSUE THREAD

**Issue by rebma13** [JulienNigon/SpellcasterUniversity-Bug-Report#682]
bonjour,
Je viens d’acheter ce jeu, j’ai pu l’installer, il se lance sans problème, j’arrive à l écran titre, je choisis "nouvelle campagne" jusque là aucun pb.
Je choisi le nom et le blason de mon école et quand j’appuie sur "OK" rien ne se passe. Le jeu ne se lance pas.
Pouvez vous me dire si ce pb peut etre corrigé?
Merci

**Comment by Neelan22** [comment]
Bonjour,
désolé d'apprendre ça :(
As tu essayé de lancer une autre partie? Est ce que toutes les parties ne démarrent pas? Si oui, peux tu nous partager les config de ton ordi stp?
Nous allons investiguer.

**Comment by rebma13** [comment]
Bonjour 
Jai essayé le jeu sur un autre ordi ce we et ça marche parfaitement. Cest mon ordi qui doit avoir un soucis.
Merci de votre réponse en tout cas
Bonne journée
