### ISSUE TITLE
[Filtre] Niveaux des salles

### ISSUE THREAD

**Issue by LeHamegeon** [JulienNigon/SpellcasterUniversity-Bug-Report#684]
Seulement testé en mode Campagne. 
Le Filtre "Niveau des Salles" ne semble pas fonctionner : 

- Pas d'overlay sur les salles existantes
- Pas de mises en surbrillance de l'icône comme lors de l'activation des autres filtres
(Top le jeu, courage pour l'avancement !)

**Comment by JulienNigon** [comment]
C'est noté. Effectivement ce filtre a un soucis actuellement. Nous corrigerons ça. Merci beaucoup !

**Comment by JulienNigon** [comment]
Corrigé dans la prochaine mise à jour (vendredi).
