### ISSUE TITLE
Port to GNU/Linux ?

### ISSUE THREAD

**Issue by remipannequin** [JulienNigon/SpellcasterUniversity-Bug-Report#687]
Any plan to have the game ported to GNU/Linux ?

**Comment by JulienNigon** [comment]
It will be ported to Linux, but at the time of the final release. It is indeed very complicated for a mini-team like ours to maintain several versions during early access...

**Comment by remipannequin** [comment]
Thank Julien, this is great to hear ! 

I 've added the game to my steam wishlist, will certainly buy it when its available...

Cheers,
