### ISSUE TITLE
Fiche personnage

### ISSUE THREAD

**Issue by azari21** [JulienNigon/SpellcasterUniversity-Bug-Report#691]
Bonjour (Bonsoir),

Je viens de commencer votre jeu (à peine 20 minutes), donc je n'ai pas fait gaffe à tout mais à l'heure actuel je peux vous dire qu'il y a un problème quand on clique sur un personnage car sa fiche ne veux pas ce fermer à moins de retourner sur le menu du jeu (et je trouve la croix pour fermer la fiche personnage un peu petite) .

Voilà le seul peu truc trouver pour ma part (, je vais continuer de jouer et si je vois autre chose je vous le signalerais.

Bonne continuation

**Comment by Donnla** [comment]
Salut !

clic gauche sur l'ecran pour sortir de la fiche perso

Mais on est d'accord ce n'est pas ergonomique

**Comment by Neelan22** [comment]
Bonjour,
Oui, un clic droit permet de fermer toutes les interfaces (fiches, bureau du proviseur, livres de menu).
Et effectivement, les croix ne sont pas très accessible. C'est noté et en réflexion.
Merci pour vos retours !

**Comment by JulienNigon** [comment]
On a agrandi la croix. On va voir à l'usage si ça vous convient. N'hésitez par à réouvrir l'issue dans le cas contraire ;)
