### ISSUE TITLE
[BUG] Choix professeur

### ISSUE THREAD

**Issue by MerguezHalal** [JulienNigon/SpellcasterUniversity-Bug-Report#697]
Bonjour !

Je pense qu'on vous l'a déjà fais remarquer mais j'ajouterai à nouveau qu'aléatoirement il arrive que, lors du choix du professeur, on se retrouve avec un texte en anglais et deux professeurs ayant exactement les mêmes caractéristiques ! 

Bon courage, continuez comme ça le jeu est génial !

**Comment by UnMecLambada** [comment]
oui j'ai la même. Je pense que se sont les fiches de personnage qui bug. Car même celle de nouveaux élèves me le fond ! En plus celles des élèves peuvent rester bloquer en petit si je les déplace.

**Comment by jeanyves-b** [comment]
Bonjour,
Je confirme le bug des professeurs égaux. De plus ces professeurs sont systématiquement les mêmes
![spellcaster académy](https://user-images.githubusercontent.com/4696914/73447437-ff73fe00-435e-11ea-82de-5c8720af8b94.png)
On voit sur l'image que le prof demandé est un prof d'herborisme et qu'il propose 2 profs d'ombre.

Je me demande si ce n'est pas un problème lié aux bibliothécaires qui font 1% de chance que les profs soient plus pédagogues.

En tout cas c'est un super jeux, merci beaucoup pour tout le travail

**Comment by Neelan22** [comment]
Bonjour,
Il s'agit effectivement d'un bug qui nous mène la vie dure. Cela fait des mois qu'on le traque... Pour info, il s'agit d'un bug purement visuel qui empêche de voir la vraie fiche des profs. Une fois recrutés, les profs et élèves ont leurs propres caractéristiques, différentes de celles qui se sont affichées juste avant. Cela reste contraignant car le choix se fait à l'aveugle :/
merci pour vos retours.

**Comment by jeanyves-b** [comment]
J'ai fait un peu de dev, et en y repensant je me demandait si ça ne pourrait pas venir d'un problème de thread.
Si la thread générant les profils et la threads les affichant ne sont pas les même, il est probable que la thread graphique prenne de l'avance et veuille afficher avant que les profils n'aient pu être généré par la thread CPU. Elle affiche du coup un profil de base.
Mon autre option était que les bibliothécaires génère 1% de chance d'augmenter la pédagogie des professeurs. suivant la façon dont est traiter cette augmentation, elle pourrait générer un event mal traité par la partie graphique.

En tout cas bon courage pour résoudre ça...

**Comment by LeHamegeon** [comment]
Je me suis habitué à cette coquille ce serait amusant d'en gardé une trace quand vous l'aurez enfin éliminé avec un nom de prof comme "Chattycowardy" ^^

**Comment by JulienNigon** [comment]
Merci pour les pistes. Ce pourrait effectivement être lié au CPU, d'où la difficulté de le résoudre sur certaines machines... Mais... pour l'instant ça ne donne rien.

+1 pour Chattycowardy, on l'ajoutera quand on étoffera la liste de noms ^^

**Comment by Neelan22** [comment]
Bug enfin trouvé !
merci pour votre aide
