### ISSUE TITLE
Alignement étudiants

### ISSUE THREAD

**Issue by GhalesBootlegger** [JulienNigon/SpellcasterUniversity-Bug-Report#704]
Bonjour !

J'ai relevé le bug suivant : dans le livre permettant d'accéder à "Classes et étudiants", après avoir sélectionné un étudiant, l'infobulle de l'alignement de certains d'entre eux (pas tous) ne correspond pas à l'alignement donné. Par exemple, j'ai un étudiant annoncé "Loyal / Mauvais", mais l'infobulle va donner les détails "Loyal / Bon".

Merci pour ce jeu et bonne continuation ! :)

**Comment by Neelan22** [comment]
Bonjour,
humm... Il fallait le remarquer. C'est noté!
Merci pour tes retours !

**Comment by JulienNigon** [comment]
Corrigé. Encore merci pour le retour.
