### ISSUE TITLE
Quelques coquilles dans le texte

### ISSUE THREAD

**Issue by GhalesBootlegger** [JulienNigon/SpellcasterUniversity-Bug-Report#707]
Re-bonjour ! :D

Tout se passe dans cet écran, quand on arrive sur la map Volcan pour la première fois en mode Campagne :
![image](https://user-images.githubusercontent.com/60486699/73505278-5535be00-43d2-11ea-8e53-50f290ecce21.png)

1) Idéalement, il faudrait une majuscule en début de phrase à "Il devrait..."
2) Un oubli de mot : "Espérons que les étudiants feront attention à ne pas tomber DANS la lave..."
2.bis) Profitons de l'élan, s'il est possible de rajouter l'accent à "Espérons"
3) Dans la première réponse possible : "plus à ça près" au lieu de "plus à ça prêt"
4) Double oubli du pluriel dans la seconde réponse possible : "des habitats naturels" et "des dragons rouges"

Voilà, à la prochaine !

**Comment by Neelan22** [comment]
Bonjour GhalesBootlegger,
Merci beaucoup pour ces retours :)

**Comment by ArielGamelle** [comment]
Bonjour !

Puisque ce thread est ouvert j'en profite pour rajouter mon grain de sel.

Toujours sur le niveau volcanique, toutes les occurrences de "Cité" (la Cité des nains, que ce soit sur la carte ou dans les dialogues) sont écrites "citée", avec un "e" indésirable donc.

Pour le niveau dans les nuages, premier panneau : il ne faut pas de "s" à "abri" dans "un abri de choix" et il faut un "t" à la place du "s" pour "ils ne mourront pas".

Dans le tuto, sur le panneau explicatif du bureau du directeur, il faut enlever le "t" de "son" dans "en fonction de son niveau d'étude" (et si vous pouviez rajouter un accent sur le "à" majuscule du début de la phrase, ce serait la cerise sur le gâteau, mais j'ai conscience que c'est plus qu'un détail lorsqu'on développe un jeu).

En tout cas merci pour l'expérience et l'idée : j'ai vraiment passé un bon moment !

**Comment by Florane88** [comment]
Bonsoir,
je me permets de rajouter une autre petite faute d'orthographe : 
dans le tutoriel, dans la présentation de la main de cartes : "sur l'air de jeu" => sur l'air**e**

**Comment by Deskones** [comment]
Il y a également quelques erreurs, notamment des "s" en trop dans les textes lorsqu'on remporte la campagne.

**Comment by ArielGamelle** [comment]
Après avoir rapidement jeté un oeil par-ci par-là dans le forum, et en réaction à la correction justifiée de Florane, je vous conseille de toujours vérifier les corrections qu'on vous propose.
Tout le monde est de très bonne volonté et c'est génial, mais certaines remarques vous ont fait rajouter des fautes ;)
(par exemple, il me semble que "aire de jeu" était bien écrit au départ mais qu'un commentaire vous l'a fait changer, ou alors je suis complètement folle)

**Comment by Neelan22** [comment]
merci pour tout !

**Comment by StephaneLeleu** [comment]
J'ajoute / note

"Une citadelle au milieu des champs"
=> les terres agricoles **près** des grandes villes et non "pas prêt des grandes villes..".

L'air**E** de jeu (notée ci dessus).. il y a bien un E

Dans la présentation de Postumus, 1ere box du tutoriel:
Bonjour, je suis l'archimage..... , a du prendre **SA** retraite lors...  (et pas MA)

**Comment by Salvador1312** [comment]
Cooool! A moi, à moi!
Niveau des nuages: "Que notre université vol!" => vole
Niveau du marais; "La vie et la santé mentale [...] diminue" => diminuent

**Comment by Neelan22** [comment]
merci :)

**Comment by Salvador1312** [comment]
Ah oui, une autre: texte d'embargo des paysans "prennent DE temps pour se nourrir" => du

**Comment by Florane88** [comment]
> 
> 
> Ah oui, une autre: texte d'embargo des paysans "prennent DE temps pour se nourrir" => du

Quel était le début de la phrase ?
Car par exemple (_je dis n'importe quoi hein_), si c'était "Plus il fait froid, plus il prennent **de** temps pour se nourrir", c'est parfaitement correct.

**Comment by StephaneLeleu** [comment]
Final / loose :

Le monde **a** encore besoin de magie.  (pas d'accent)

**Comment by Salvador1312** [comment]
Ah oui Florane88 pas bête, mais ce n'est pas comme ça que c'est tourné. Ceci dit peut-être que l'erreur est aillleurs: de mémoire la phrase était "Les étudiant prennent de temps pour se nourrir", donc soit c'est "du", soit il manque "plus" avant le "de" (ce qui serait plus logique en fait).

Sinon autre coquille, dans les options pour la mission de spécialisation: "certain trouvent ça ringard" => certainS

**Comment by JulienNigon** [comment]
Et voilà, normalement j'ai pris en compte toutes ces corrections, et les ai vérifié à chaque fois ! C'était horrible, je me suis senti très mal pour "sont" et "à"... Un grand merci à tous !
