### ISSUE TITLE
Liste dans le bureau des futures

### ISSUE THREAD

**Issue by shlikam** [JulienNigon/SpellcasterUniversity-Bug-Report#709]
Très bon jeu , j'ai passé beaucoup de temps, on ne se lasse pas.

Par contre j'ai remarqué que certains métiers comme : horloger, sbire, diablotin, et d'autres ne s'affiche pas dans les futures. j'ai compter 7 métiers en tout ne s'affichant pas alors que je les avais découvert.

**Comment by Neelan22** [comment]
Bonjour,
ah? ok, nous notons ce bug, merci !
merci pour les compliments :)

**Comment by Hyslyne** [comment]
Bonjour, personnellement j'ai bien sbire dans le bureau des futures mais pas diablotin, goule, horloger et fossoyeur ( peut-être d'autres mais je m'en suis pas encore rendue compte )

**Comment by Hyslyne** [comment]
Maintenant que j'ai débloqué Moine du Temps, je peux voir qu'il y a un futur en-dessous mais je vois que le haut des lettres et je peux pas descendre plus. Peut-être que les futurs manquants sont tous là-dessous

**Comment by JulienNigon** [comment]
Normalement c'est corrigé depuis la dernière mise à jour. Encore merci :)
