### ISSUE TITLE
objectif perdu

### ISSUE THREAD

**Issue by UnMecLambada** [JulienNigon/SpellcasterUniversity-Bug-Report#715]
les objectifs de relations sont bugé dans la campagne sont bugé, voila la situation de base et le déclenchement du bug : 

j'avais trois objectifs, le premier relation 90 avec pirate le second relation 90 orcs (et le troisième 6000 de mana d'alchimie mais ici on s'en fiche).
Lors de la partie j'ai eu 90 avec les orcs et mon objectif c'est validé.
J'ai ensuite validé le 90 de relation avec les pirates.
Ma relation avec les orcs s'est dégradé car je les envoyais contre le mal. Elle est tombé à 45 après avoir validé l'objectif.
Le niveau c'est terminé j'ai choisi mes grimoires avec 2 objectifs réussi, je choisi la map puis quitte le jeu. Quelques heures plus tard je rejoue et charge la sauvegarde de campagne.
La partie reprend au texte d'arrivé du mal de la map précédente et mon objectif des orcs n'est plus validé ...

Je pense qu'il faudrait donc rajouter quelques lignes de code pour que lorsque l'on charge une partie le test des objectifs ne test pas si on rempli l'objectif au moment précis du chargement mais si il a été rempli durant la partie. En ajoutant une constante d'objectif validé par exemple ou par un autre code, de manière à ce qu'un objectif validé le reste.

hors sujet : ho et d'ailleurs, si la valeur de réduction de progression du mal pouvais s'afficher en % plutot qu'en chiffre car 0.05 ou 0.03 n'est pas très instinctif et on ne sais pas forcement que la barre est rempli à une valeur de 1 sans faire l'expérience (elle pourrais être de 2/10/25 etc et on ne le sais pas à l'avance). Alors que 3% et 5% sont plus évocateur et plus congrès.

**Comment by Neelan22** [comment]
Bonjour,
Bien vu pour les quêtes, nous allons voir ça.
Oui, le % dans la barre de progression est dans la todo list, mais pas prioritaire. Ça devrait se faire.

**Comment by nuniv3k** [comment]
Bonjour,
Je confirme le souci sur les objectifs, même si dans mon cas c'était un peu différent (dans le doute je préfère ne pas ouvrir d'issue à part, l'origine du bug est probablement la même) :
1. j'ai validé l'objectif de 90 de relation avec les orcs, puis je suis retombé sous les 90 (mais l'objectif était toujours validé)
2. j'ai sauvegardé ma partie, puis quitté le jeu
3. lorsque j'ai rechargé ma partie, l'objectif n'était plus validé (et il n'a pas compté en fin de partie, à ma plus grande tristesse 😢)

**Comment by Neelan22** [comment]
Oui ce bug est noté dans une autre issue. Désolé pour ta partie :(

**Comment by JulienNigon** [comment]
Le bug est réglé (la mise à jours sera déployée vendredi). J'ai noté par ailleurs vos autres retours (% plutôt que valeur). Un grand merci :)
