### ISSUE TITLE
Bug Archimage

### ISSUE THREAD

**Issue by Donnla** [JulienNigon/SpellcasterUniversity-Bug-Report#716]
Salut les Devs !

j'ai rencontré un problème pour obtenir un/des Archimage dans le jeu : 

Lorsque certains de mes étudiants on "trop" de lvl en magie, il y a tellement d'option de carrière  que le jeu ne calcule pas les chance de devenir archimage (ou du moins ne les affiche pas). 

C'est comme ça que des étudiants avec 5 ou 6 domaines de magie au max ne peuvent pas devenir Archimage.

Merci pour vos retours et vos efforts, le jeu est toujours aussi bien !

Ps : d'autres petits Bugs : 
- certains élèves continues a étudier des matières qu'ils ont déjà au max, et y retourne même par la suite. Cela semble aussi concerner le travail à la bibliothèque
- le jeu n'enregistre pas la validation des quêtes lors de la sauvegarde : exemple : je finis la quête des Orc, j'utilise ma réputation pour ralentir le Mal, je sauvegarde et relance ma partie, et la quête n'est plus validée (l'étoile est vide). Par contre si je revalide l'objectif je n'ai pas la boite de dialogue avec l'orc (donc le bug est peut être seulement graphique)

**Comment by LeHamegeon** [comment]
+1 pour les étudiants qui continuent de cravacher dans les domaines déjà au max.
+1 Pour les quêtes. J'avais pas pensé à l'origine seulement graphique je peux tester avec ma save.

**Comment by Donnla** [comment]
sans vouloir insister sur ce topic, voilà un petit screen sur mon record de spécialisation : 8 domaines au max et l’élève ne pouvais pas devenir archimage 

![1](https://user-images.githubusercontent.com/60445854/73627701-a258a080-461b-11ea-8629-f2ec683caaa4.png)
![2](https://user-images.githubusercontent.com/60445854/73627702-a2f13700-461b-11ea-920a-dfc87b361260.png)

**Comment by Neelan22** [comment]
Ok, le bug d'archimage est noté.
Pour ce qui est des étudiants très bien formés, le sujet est en réflexion : si l'étudiant ne bosse plus cette magie, il ne génèrera plus de mana. Est-ce que cela sera gênant? Nous n'avons pas encore pris de décision...

**Comment by Donnla** [comment]
Merci !

**Comment by kaori01** [comment]
mêmes bugs remarqués (ne JAMAIS prendre la quête visant à former un archimage ;) ).
Petite précision, lors d'une sauvegarde, la réussite de quête n'est plus prise en compte si jamais la condition n'est plus remplie (comme la faction orc, qui peut varier si on leur a demandé un coup de main...) y compris pour le niveau du bonus pour le niveau suivant, ce n'est pas qu'un bug graphique...

**Comment by Salvador1312** [comment]
Mh je pense qu'il serait préférable que l'élève arrête en effet de plancher sur un domaine qu'il maîtrise: cela prend une place en cours juste pour que môssieur ou madame se la pète devant ses ptits camarades! De toute manière, je pense que quand on peut max un élève, ça veut dire que notre génération de mana est plutôt en forme, donc on ne perdrait pas grand chose. 
Perso, je n'avais pas capté ce problème et d'ailleurs j'ai l'impression qu'en présence d'une bibliothèque l'élève allait de lui même "approfondir" une matière random (parfois même pas enseignée dans l'établissement). C'est pas gênant, il prend des initiatives ^^ (mais infos à vérifier)
Peut-être que pour éviter qu'il ne se tourne le pouces, vous pourriez ajouter un feed back visuel pour indiquer que tel ou tel perso ne peut plus évoluer dans les matières lui étant autorisées (histoire qu'on le change d'école): une surbrillance, voire même un "évènement" sur la gauche type "siou plaît donnez-moi de nouveaux livres à manger".

**Comment by Neelan22** [comment]
c'est noté ;)

**Comment by JulienNigon** [comment]
Problème de l'archimage corrigé pour le prochain patch. Merci encore.

**Comment by JulienNigon** [comment]
Je ferme l'issue. Les points soulevés sur l'approfondissement des matières et la validation des quêtes sont notés par ailleurs. Un grand merci !
