### ISSUE TITLE
Chaudron et barre d'espace

### ISSUE THREAD

**Issue by GarlandNic** [JulienNigon/SpellcasterUniversity-Bug-Report#720]
Je me sert de la barre d'espace pour basculer entre "en pause" et "hors-pause".
Lorsque je viens d'utiliser le chaudron, la barre d'espace fait aussi la bascule entre chaudron ouvert et chaudron fermé. (les deux bascules se font en même temps)

**Comment by Neelan22** [comment]
Il fallait le remarque celui là ^^
Merci pour le retour !

**Comment by JulienNigon** [comment]
Corrigé pour la prochaine maj.
