### ISSUE TITLE
Bugs fiches professeurs et autres remarques

### ISSUE THREAD

**Issue by ArielGamelle** [JulienNigon/SpellcasterUniversity-Bug-Report#730]
Bonjour,

Déjà, merci pour le jeu, j'ai terminé la campagne et je sens que je vais y passer encore des heures.

Voici quelques remarques suite à cette petite partie en mode Sorcier : 

- Il arrive assez régulièrement que lors du recrutement de nouveaux professeurs, les deux fiches soient identiques et en anglais. Seuls l'avatar et le nom du professeur changent. J'ai supposé que c'était un placeholder qui traînait car ce sont toujours les mêmes caractéristiques (pédagogie excellente, syndiqué, bavard, etc.)

- Truc bête : je n'ai pas son. Je ne sais pas s'il est censé en y avoir.

- Au niveau des traits de caractères, il arrive relativement souvent qu'un personnage ait des qualités et des défauts qui s'annulent (exemple : sympathique et prétentieux).

Et des remarques plus générales sur les mécaniques de jeu : 

- Une fois que l'armée des ombres attaque et que l'on a diplômé tous nos élèves, quel intérêt de retourner sur l'écran de l'école alors qu'on ne peut plus agir dessus ? A part voir tout le monde paniquer, bien sûr.

- Dans la continuité directe de ma première remarque, et uniquement en mode campagne, est-ce qu'il ne pourrait y avoir un impact plus important du résultat de notre partie sur la partie suivante ? Il y a bien les histoires de grimoires, mais j'avoue que c'est particulièrement frustrant de diplômer 80 élèves d'un coup, récoltant au passage des monceaux d'or et de mana, pour repartir à zéro juste après. Sans transférer la totalité des gains à la partie d'après, bien sûr. J'ai bien conscience que cette remarque est particulièrement subjective.

- J'ai supposé qu'il était intéressant de "fusionner" des salles qu'on achète en double/triple/etc., mais ce serait appréciable d'avoir un feedback graphique (permanent pour connaître le niveau de la salle et au moment de la "fusion" pour voir concrètement ce que ça ajoute) sur cette action, qui permettrait aussi de s'y retrouver un peu plus au moment d'acheter de nouvelles salles.

- Pour le confort des têtes de linotte comme moi qui adorent mettre des noms obscurs à leurs maisons, ce serait pratique de pouvoir consulter les matières priorisées par chacune lors du recrutement des élèves.

C'est tout pour moi ! Encore merci pour le jeu :)

Et bon courage !

**Comment by Florane88** [comment]
Bonsoir,

je me permets d'intervenir dans ce topic récent car il me parle...

Pour reprendre les éléments ci-dessus :

- idem pour les fiches "buguées", ça m'est arrivé pas mal de fois sur la campagne.

- @ArielGamelle Ah, le souci semble venir de ton PC ou de la confirguration du jeu (paramètres) car aucun souci de mon côté, il y a bien la musique générale + des bruitages par salle + des sons "d'effet"

- (pour les caractères, c'est vrai, mais je ne pense pas que ce soit un bug et finalement ce n'est pas gênant)

- > à part voir tout le monde paniquer 

=> Exactement !! Ça me semble volontaire, pour bien nous mettre dans l'ambiance "fin de ce monde", non ?

- > est-ce qu'il ne pourrait y avoir un impact plus important du résultat de notre partie sur la partie suivante ?

Alors là, +1000 ! C'est hyper frustrant de gagner plein de choses en fin de partie sur une campagne et de ne rien en retirer, que ce soient uniquement les réussites de quêtes qui aient une influence !!

- D'accord aussi pour le niveau des salles. D'ailleurs j'ai essayé d'utiliser le filtre spécifique mais soit il y a un bug, soit l'affichage n'est vraiment pas clair car je n'ai vu aucun changement avec / sans filtre sur le niveau des salles ! Après, pas besoin d'un graphisme différent avec "remplissage" de la salle par des éléments de décor comme je l'ai vu évoqué à un autre endroit, car à mon avis ça ne serait plus très lisible, mais surtout pas assez explicite. Un petit chiffre en bas au milieu de la salle indiquant son niveau serait parfait.

- @ArielGamelle On peut voir les spécialités choisies par maison ;-) Il faut cliquer sur le 2ème livre en partant de la gauche, tout en bas à gauche une fois en jeu (je ne sais plus son nom mais il est dans les tons de marrons avec une forme de blason dessus)


- - - - - - - - - - -
Après avoir bien profité de tout ce qu' @ArielGamelle a dit, j'aurais juste 2 autres remarque _(oui, seulement 2 parce que je suis aussi une tête de linotte et que je n'ai pas noté au fur et à mesure où j'y pensais...)_ :
Je trouve le système d'indication sur les constructions vraiment pas intuitif.
Savoir si oui ou non on pourra mettre quelque chose au-dessus, si il faut que ce soit directement construit au sol ou pas...
Je ne suis peut-être pas maline, mais le Belvédère notamment, je n'ai réussi à le construire qu'une fois et "par hasard" ; les autres fois je l'ai gardé en main, gardé en main... En espérant pouvoir enfin le poser à un moment, pour finalement le jeter : rageant !!
Pour la serre également, j'ai eu du mal : elle ne peut pas être construite entre 2 bâtiments, c'est ça ??
Bref, les indications en bleu sont bien mais il faudrait par exemple aussi des zones / traits en rouge pour les côtés où on ne pourra pas construire de manière adjacente à ce bâtiment.

Et pour la dernière partie de la campagne, j'aurais bien aimé avoir un "compteur d'étapes" (1/x, puis 2/x...). Premièrement ça motiverait, parce qu'honnêtement, au bout de 5 j'étais découragée.
Deuxièmement ça permettrait de comparer 2 campagnes entre elles, voir si on a fait mieux ou moins bien que la fois précédente.


Ah, finalement j'ai une 3ème remarque :
Pourquoi le concierge ou le psychologue par exemple, ont des modificateurs "d'enseignement" ? (exemples : Inspirant ou Sagesse des anciens) Il ne sont pas censés avoir d'influence sur les élèves, si ?


Sinon vraiment très sympa comme jeu !
Pas évident au début, ça fait vraiment beaucoup d'informations à intégrer entre tous les caractères, l'alignement, le fonctionnement des relations avec les autres sur la carte...

**Comment by ArielGamelle** [comment]
Ravie de t'avoir autant inspirée haha

Pour mon histoire de maison à consulter, bien sûr qu'on peut passer par le livre... mais pas PENDANT le recrutement des élèves (si c'est possible, c'était buggué chez moi dans ce cas). Oui je sais, je suis pénible ;)

**Comment by Neelan22** [comment]
Bonjour,
et merci pour tous ces retours.
Le bug des fiches devrait être corrigé.
Pour le belvédère, on a un joueur qui a fait un beau schéma, voir PJ
Les avenirs des élèves se cumulent de tableau en tableau (hors gain de mana ou or immédiat. Mais pour les "+x% de chance d'avoir ...", ça marche
Oui on va ajouter de la visibilité, je note tous ces retours.
Le concierge et le psychologue sont créés de la même manière que les profs. Il y a du peaufinage à faire.

![73610794-8b925980-45db-11ea-9d41-fe654c43eb9c](https://user-images.githubusercontent.com/47151033/73644643-0d36c580-4676-11ea-8a1c-2b5961389ab5.PNG)

**Comment by zerah54** [comment]
@Florane88 pour ce qui est des filtres j'ai rencontré le même "problème" mais en fait certains filtres marchent bien en "Pause" et certains ne semblent fonctionner que lorsque le temps tourne, c'est peut être le cas que tu as rencontré ?

**Comment by Florane88** [comment]
> Pour le belvédère, on a un joueur qui a fait un beau schéma, voir PJ
> ![73610794-8b925980-45db-11ea-9d41-fe654c43eb9c](https://user-images.githubusercontent.com/47151033/73644643-0d36c580-4676-11ea-8a1c-2b5961389ab5.PNG)

Je ne sais pas de qui il s'agit, mais... MERCIII à ce joueur !! Ce schéma est parfait, j'ai enfin pu construire un beau belvédère en prévoyant sa disposition ! 


@helenegodart Ahh, je n'avais pas pensé à mettre en pause ; je regarderai, merci beaucoup pour cette info

**Comment by Neelan22** [comment]
Le filtre des salles n'est pas encore implémenté ;)

**Comment by kaori01** [comment]
Bonjour, j'ai moi aussi le bug des profs qui par moments sont identiques (et en anglais) 
![image](https://user-images.githubusercontent.com/60629516/73867290-b6341a80-4846-11ea-8a8e-a4be3ac04d38.png)

**Comment by Neelan22** [comment]
bug des profs corrigé dans la dernière maJ :)
