### ISSUE TITLE
Problème avec la Serre

### ISSUE THREAD

**Issue by Nelphemoth** [JulienNigon/SpellcasterUniversity-Bug-Report#731]
Lorsqu'on achète une serre et qu'on la place, les professeurs proposés sont toujours les mêmes avec les mêmes attributs/caractéristiques/statistiques.

**Comment by Florane88** [comment]
En fait ce problème n'est pas lié à la serre car il m'est arrivé de nombreuses fois, ainsi qu'à d'autres joueurs : voir issue #730

**Comment by Neelan22** [comment]
Oui c'est un bug visuel qui nous donne du fil à retordre...
Les profs ont bien des fiches différentes, mais seulement visibles quand on les sélectionne après les avoir recrutés.

**Comment by JulienNigon** [comment]
Je ferme l'issue. La #730 fait référence. Merci pour le feedback !
