### ISSUE TITLE
Foyer des élèves relié sur les côtés

### ISSUE THREAD

**Issue by Aubhisamme** [JulienNigon/SpellcasterUniversity-Bug-Report#732]
Le foyer des élèves n'est censé être relié que de haut en bas, et la texture des côtés montre bien une porte emmurée la reliant sur ces parties.

Or, mes élèves passent sans problème à travers cette texture.
![spellcaster foyer des élèves bug](https://user-images.githubusercontent.com/60467502/73652944-61e33c00-4688-11ea-876b-5043d60c03f4.jpg)

**Comment by Neelan22** [comment]
Nous ne les avons pas formé à passer à travers les murs... Des mesures seront prises >:-(
Merci pour le retour !

**Comment by JulienNigon** [comment]
Corrigé dans la prochaine mise à jour.
