### ISSUE TITLE
Cartes artefacts disparaissent au chargement

### ISSUE THREAD

**Issue by GarlandNic** [JulienNigon/SpellcasterUniversity-Bug-Report#737]
Dans le Lumineux réfectoire du personnel, les artefacts de nourriture disparaissent quand on charge la partie.
De même, dans le cochonier, l'artefact de créature disparaît.

**Comment by Neelan22** [comment]
ok, bien vu. Merci

**Comment by JulienNigon** [comment]
Corrigé dans la prochaine mise à jour. Encore merci du retour.
