### ISSUE TITLE
Résolution manquante dans le menu options

### ISSUE THREAD

**Issue by jeremy-boes** [JulienNigon/SpellcasterUniversity-Bug-Report#74]
![su_options](https://user-images.githubusercontent.com/42269011/50784434-e3ae3d80-12ad-11e9-9c95-20c05ac88bcc.png)

À l'installation j'ai spécifié 1920x1080, proposé par l'installer par défaut. Mais je ne retrouve pas cette possibilité dans le menu.

Pire, si je passe en 800x600, l'affichage est tout borké :
![su_options](https://user-images.githubusercontent.com/42269011/50784620-6df6a180-12ae-11e9-841e-3c7b5d56a4e0.png)

Aussi, quand je reviens dans une des deux autres résolutions disponibles, le menu déroulant ne se met pas à jour est reste sur 800x600 (et reste là-dessus même si je quitte le menu et y revient).

**Comment by JulienNigon** [comment]
Oui le menu option est en wip. Merci des retours :)
