### ISSUE TITLE
bug avec une sixième maison

### ISSUE THREAD

**Issue by kaori01** [JulienNigon/SpellcasterUniversity-Bug-Report#740]
sur la page des recrutements, impossible de mettre les nouveaux étudiants dans une sixième maison, la fenêtre de la sixième maison est pourtant réactive (elle s'éclaire quand on passe dessus) mais rien ne se produit quand on clic dessus...

**Comment by Neelan22** [comment]
humm, ok c'est noté, merci.

**Comment by Neelan22** [comment]
#674

**Comment by JulienNigon** [comment]
Corrigé dans la prochaine mise à jour (vendredi 7). Merci pour le retour !
