### ISSUE TITLE
Petits bugs et quelques suggestions

### ISSUE THREAD

**Issue by PierreAndre87** [JulienNigon/SpellcasterUniversity-Bug-Report#742]
Bonjour, 
et tout d'abord bravo pour ce jeu bien sympathique.
Quelques petits bugs, tout d'abord : 
- l'avenir "Fossoyeur" n'est pas listé dans les avenirs obtenus (je ne pense pas qu'il soit actif non plus)
- les filtres ne marchent pas (sans doute plus une feature non finie qu'un bug)
- au chargement de la partie, un bruit assez moche survient (bruit de "placement" de tous les items ?)
Bref, rien de gamebreaker jusqu'à présent.

Suggestions d'améliorations : (vous en faite ce que vous voulez)
- Faire que le belvédère soit une pièce et non plus un animal contrainte étrange et non intuitive...(déjà que le placement est difficile)
- Ajouter une indication comme quoi il est possible de changer les étudiants de maison. (j'ai trouvé ça totalement par hasard, et ça change totalement le jeu)
- Ajouter une indication de ce que fait le changement de difficulté
- Ajouter la possibilité d'augmenter le niveau des artefacts si j'mais on tire plusieurs fois le même artefact
- Changer le texte de la carte d'équipement lors du tirage pour correspondre au nouvel effet en fonction du nombre de même équipement déjà possédé
- Ajouter la possibilité de détruire une salle / un artefact
- Niveau potions, je proposerai une interface un peu plus user-friendly : 
        . Ne plus creer la potion automatiquement au troisième ingrédient
        . Lors du troisième ingredient, afficher l'image de la potion résultat sur le chaudron si la recette est connue, un ? sinon
        . Ne créer la potion que quand le joueur clic su le chaudron
        . Laisser l'occasion au jouer de reprendre ses composants tant qu'il n'a pas créé la potion

Bon courage ! Vous êtes clairemement sur une bonne voie.

**Comment by Neelan22** [comment]
Bonjour,
merci pour tes retours !
Le bug des avenirs est corrigés, les autres sont sur la todo list, mais pas urgent
Le belvédère est une salle, mais je n'ai peut etre pas compris la question.
![image](https://user-images.githubusercontent.com/47151033/73744610-72131e00-4751-11ea-84a3-4029a031c130.png)
Les artefacts ne s'améliorent pas si on les joue plusieurs fois, cela diminue les conditions pour que les élèves s'en équipent (mais ok, ça manque d'explication)
Nous avons des retours sur l'interface de la potion qui suggéraient moins d'actions (contrairement à ta proposition qui ajoute un clic). Nous n'avons pas encore rediscuté entre nous du sujet de cette interface. Pour le moment nous avons énormément de travail ailleurs :/
La question de la destruction de salle est en cours de réflexion, nous n'avons pas encore pris de décision.
Et nous rajouterons + d'explications dans les différents menus, oui

Merci pour ton soutien !

**Comment by Neelan22** [comment]
#709 
#307

**Comment by PierreAndre87** [comment]
Milles excuses pour le belvédère, mon cerveau avait juste buggé.
C'est une pièce, tout va bien...
Bon courage !
