### ISSUE TITLE
impossible de zoomer sur les salles hautes

### ISSUE THREAD

**Issue by kaori01** [JulienNigon/SpellcasterUniversity-Bug-Report#744]
l'écran limite le zooming des salles les plus hautes, rendant difficile voire impossible l'équipement de ces dernières...

**Comment by kaori01** [comment]
En fait, on ne peut tout simplement pas monter la caméra plus haut, et ce même si l'on peut encore construire... je l'ai constaté sur plusieurs cartes, là j'ai testé sur la forêt (celle avec le troll endormi) et ça bloque bien avant d'arriver au maximum constructible.

**Comment by Neelan22** [comment]
On a volontairement bloqué la caméra pour empêcher les joueurs de monter trop haut (sinon la carte graphique fond...)
C'est une solution à court terme qui sera peaufinée plus tard.

**Comment by kaori01** [comment]
haha! D'accord! Merci d'avoir éclairé ma journée par l'éclat de rire que je n'ai pu réprimer en lisant votre réponse ce matin (Moi, tant qu'on me laisse empiler, j'empile... :D ).

**Comment by JulienNigon** [comment]
Bon c'est un peu plus subtil que ce que m'on estimée collègue a répondu. On a limité, mais pas avec la caméra ! (On est des indés, mais quand même ^^). Donc c'est bien un bug, et il sera corrigé dans la mise à jour de demain. Je ferme l'issue. Merci !
