### ISSUE TITLE
Résolution non suportée

### ISSUE THREAD

**Issue by nverstaevel** [JulienNigon/SpellcasterUniversity-Bug-Report#75]
Hello,

J'essaie de lancer le jeu en résolution 1360x768 mais la résolution ne semble pas supportée car certains élements de l'interface sont masquées:

![20190108085804_1](https://user-images.githubusercontent.com/17766516/50795959-172baf00-1324-11e9-9214-ae3853d8830d.jpg)
![20190108085842_1](https://user-images.githubusercontent.com/17766516/50795960-172baf00-1324-11e9-85d6-6f63f8fa5c48.jpg)
![20190108085022_1](https://user-images.githubusercontent.com/17766516/50795962-172baf00-1324-11e9-8433-4d42f71ee745.jpg)

**Comment by JulienNigon** [comment]
Pour l'instant la seule résolution supportée c'est : 1920 x 1080
L'ajout de résolutions sera pour plus tard (mais en théorie ne devrait pas poser trop de problèmes). Merci du retour :)

**Comment by JulienNigon** [comment]
Les autres résolutions sont désormais supportées MAIS il y aura peut être quelques surprises.
