### ISSUE TITLE
Réserve à composants qui ne fonctionne pas

### ISSUE THREAD

**Issue by Florane88** [JulienNigon/SpellcasterUniversity-Bug-Report#757]
Bonjour,
je viens d'avoir un petit bug sur la dernière partie de ma campagne : 

J'avais 2 **réserves à composants** installées dans mon école (1 dans une salle des arcanes + 1 dans une salle de la nature), donc l'une quasiment depuis le début de partie, qui a duré jusqu'à "11 Automne" (pour vous donner une idée de la durée) et...
à part 3 fromages issus de l'appareil à raclette et 4 chapeaux de parkofites _(je crois que c'est le nom, désolée si j'ai fait une erreur...)_ parce que j'avais mis un pot de champignons dans une salle, je n'ai eu **AUCUN composant de toute la partie** :(

Par contre je suis vraiment désolée mais je n'ai absolument pas noté dans quel ordre j'avais placé ces réserves par rapport à des salles ou autres pour vous aider à trouver d'où vient ce bug...

**Comment by Neelan22** [comment]
Bonjour,
Bien relevé, on va regarder ça.

**Comment by JulienNigon** [comment]
Merci beaucoup. Le correctif sera déployé avec la mise à jour de vendredi. je note comme fermé :)

**Comment by Florane88** [comment]
(on dirait que je peux encore poster même si fermé...)

Pour info, le même souci m'est de nouveau arrivé, toujours sur la carte "tortue". Cette fois-ci je n'avais qu'une seule réserve, mais aussi en salle des arcanes. C'était une des premières salles de cours que j'avais, du coup bien active en début de partie...
