### ISSUE TITLE
Cannot place items suddenly

### ISSUE THREAD

**Issue by Jozukozu** [JulienNigon/SpellcasterUniversity-Bug-Report#762]
After some gametime, I stopped being able to place items to their designated places in rooms.

**Comment by Salvador1312** [comment]
Did you try to zoom and change the angle of the camera?

**Comment by Jozukozu** [comment]
I did not, does that help?

**Comment by Salvador1312** [comment]
Yes sometimes I have to move the camera and zoom in with the cursor (with item) on the designated place to trigger the blue icon. I think they are fixing it with the enhancement of UI (not sure). For example, I have this issue with private room.

**Comment by Neelan22** [comment]
Does the spot of the item turn blue or stay white? Or doesn't appear at all?

**Comment by Jozukozu** [comment]
Ok, if I zoom right in then it let's me place stuff again. I guess after some point it just gets a bit fidgety.

**Comment by Neelan22** [comment]
yes, we have to improve this point :/
