### ISSUE TITLE
Plusieurs problèmes et suggestions.

### ISSUE THREAD

**Issue by HibalB** [JulienNigon/SpellcasterUniversity-Bug-Report#763]
Tout d'abord, très bon jeu. Je l'ai découvert grâce à Fred sur sa chaîne le Bazard du Grenier, si vous connaissez (apparemment oui).
J'ai lu sur quelques autres "issues" ce qui avait déjà été signalé ou suggéré pour éviter de répéter ce qui a déjà été report, et que vous aviez déjà énormément de travail.
J'ai voulu vous informer de quelques problèmes, dont vous avez probablement déjà connaissance, et faire quelques suggestions, car après tout, même si vous en aviez d'ores et déjà connaissance, ou que vous ne soyez pas intéressés, on ne sait jamais ^^. By the way, j'aime utiliser le mot "parfois".

Problèmes:
  -parfois, le clic de molette pour modifier l'angle de la caméra, comme le ferait "a" et "d" (ou autre)  ne marche pas, seul le fait de piocher une carte (et non de changer de menu) réussi à le faire  fonctionner de nouveau;
  -parfois, lorsque l'on appui sur l'info-bulle pour avoir de nouveaux élèves, il est affiché "0" en nombre de candidatures si il n'y a qu'un seul élève. La plupart du temps, lorsqu'il n'y a qu'un seul élève, le chiffre "1" est affiché;
  -parfois, la musique s'interpose. Cela arrive généralement lorsque l'on passe de la nuit à la journée;
  -parfois, je n'en connais pas la raison, mais le volume de la musique diminue de beaucoup en un court moment, avant de remonter au niveau précédent au bout de quelques secondes.

Suggestions:
  -même si c'est un jeu, je le vois, qui ne vise pas un but graphique sérieux tels les Dark Souls ou autre, je trouve que rajouter des emblèmes de maison, ou d'université, plus sérieux, comme un terrifiant (^^) dragon, serait plaisant;
  -une option dans les paramètres pour désactiver l'intro, même si au final c'est presque inutile, vu qu'on peut la passer rien qu'avec un simple clic ou, peut-être (n'ayant pas testé), un appui de touche de clavier;
  -un événement, une fois la quête de spécialisation de l'université terminée, qui change le style graphique de l'établissement en accord avec le domaine de spécialisation choisi (en vrai, stylé, mais très demandant en temps ou budget envers les graphistes je le sais);
  -ajouter une salle, une potion ou/et une carte qui, contre un coût, permet de pouvoir détruire une salle/artefact, mais sans pouvoir regagner la carte de cet(te) salle/artefact, ou alors ajouter un événement aléatoire, qui lui permettrait de regagner la carte en question, après avoir détruit un(e) salle/artefact par un moyen quelconque (possiblement déjà dans le jeu); 
  -un menu pour changer les touches dans le menu options (et du coup pouvoir savoir les raccourcis clavier), et, aussi, ajouter un raccourci, si pas présent, pour effectuer une sauvegarde rapide;
  -ajouter au marchant le choix de jouer au dés ou à un jeu de sorciers (je ne m'y connais pas trop mais dans un autre jeu c'était un jeu de carte avec des sorciers connus et des monstres) en misant de l'argent, pour ainsi gagner une somme prenant en compte la somme misée;
  -la possibilité de modifier les emblèmes et spécialités (pas les traits) des maisons.

Voilà, j'espère ne pas trop vous avoir fait soupirer ^^, c'est juste que cela me tiraillais de faire part de ces bugs, même si pas embêtant, et de mes suggestions probablement inutiles... (vous en faite ce que vous voulez).
Surtout, je vous souhaite une bonne continuation dans vôtre projet.

**Comment by Florane88** [comment]
> parfois, la musique s'interpose.

Heu, c'est à dire ??
_(s'interposer = "se mettre entre")_

**Comment by HibalB** [comment]
> > parfois, la musique s'interpose.
> 
> Heu, c'est à dire ??
> _(s'interposer = "se mettre entre")_

Désolé pour ma mauvaise utilisation du mot. Je voulais dire qu'il arrivait que deux musiques se jouent en même temps.

**Comment by Florane88** [comment]
Ah, d'accord, merci pour l'explication ! 
Promis, c'était vraiment pour essayer de comprendre car chez moi parfois elle se coupe (_tiens, aussi un "parfois" ;)_ ) mais je n'ai jamais constaté 2 musiques en même temps.

**Comment by Neelan22** [comment]
HibalB,
Merci pour tous tes retours. Les problèmes que tu cites sont des "détails" auxquels nous nous attarderons plus tard.
Tes suggestions nous ont bien plu :)
Actuellement le dev est en PLS au sol et la graphiste a sauté de la falaise la plus proche. Mais on note quand même tes idées :)
bon jeu !

**Comment by HibalB** [comment]
Merci ! ^^ Force à vous !
