### ISSUE TITLE
Candidatures multiples

### ISSUE THREAD

**Issue by Salvador1312** [JulienNigon/SpellcasterUniversity-Bug-Report#766]
Désolé d'avance si le bug des fiches étudiants minuscules/invisibles/impossibles à ouvrir dans le menu classes a été corrigé par la dernière maj (pas eu l'occaz de revérifier), mais durant ce bug (je pense que c'est lié), j'ai eu 20-30% du temps les candidatures trimestrielles qui ne se fermaient pas après avoir fait la sélection des étudiants ce qui me permettait de recruter deux, trois voire quatre fois en une saison. Perso, j'ai eu ce bug général trois fois sur trois missions volcan, et une fois sur cinq en forêt (en première mission).

**Comment by Neelan22** [comment]
Arf, le coup des candidatures multiples est très certainement une conséquence de la dernière maj... :/
Merci !

**Comment by Salvador1312** [comment]
Non non justement ça m'est arrivé avant la maj: à chaque fois c'était en doublon avec le bug des fiches persos minuscules. Du coup je ne sais pas si ce bug est toujours d'actualité mais comme personne n'avait fait la remarque, j'ai posté ça au cas où.

**Comment by Neelan22** [comment]
ok, je ferme l'issue alors. Si le bug revient je te laisse refaire un post stp.
merci,
