### ISSUE TITLE
Etudiant ayant deux fois le même debuff

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#77]
Test le 09/01/2019 au soir

Un étudiant a deux fois le même debuff

https://drive.google.com/open?id=1bpp4Npbs9cS_d2fBvXGvmghkeGl-qIuD

**Comment by JulienNigon** [comment]
Je pense que c'est solutionné mais je n'ai pas réussi à la reproduire. A guetter donc.
