### ISSUE TITLE
Barbare

### ISSUE THREAD

**Issue by Eredkindjal** [JulienNigon/SpellcasterUniversity-Bug-Report#776]
Dans le bureau du directeur
Dans le tableau d'honneur
Dans la description de la "recette" du Barbare :
"définition barbare Modificateurs clef incorrecte"

**Comment by Neelan22** [comment]
Bien vu, merci

**Comment by JulienNigon** [comment]
Corrigé pour la mise à jour de demain. Merci beaucoup !

**Comment by Eredkindjal** [comment]
Ça fait super plaisir de voir une pareille réactivité !
Ça donne envie de recommander spellcaster à tous mes amis !
Bonne continuation à vous et continuez à nous faire un superbe travail !

Le jeu. 20 févr. 2020 à 16:40, Julien Nigon <notifications@github.com> a
écrit :
