### ISSUE TITLE
bug avec le faune

### ISSUE THREAD

**Issue by cb1504** [JulienNigon/SpellcasterUniversity-Bug-Report#786]
bonjour,
j'ai ici un faune placé dans le belvédère qui n'arrive pas à en sortir...
![Image1](https://user-images.githubusercontent.com/60439859/74112720-5c618680-4b9f-11ea-9c1e-ce18fa004906.png)
bonne continuation !
cb

**Comment by Florane88** [comment]
Ah tiens, même bug que pour le pégase... #782

**Comment by Neelan22** [comment]
Je pensais que le pégase était trop gros pour passer la porte mais le problème semble venir du belvédère !

**Comment by cb1504** [comment]
problem solved :)
