### ISSUE TITLE
Bug dans les règlements de l'école

### ISSUE THREAD

**Issue by kaori01** [JulienNigon/SpellcasterUniversity-Bug-Report#787]
Après avoir quitté le jeu, lorsqu'on recharge sa partie, certaines option se décochent : le concours annuel, et le mécénat... je n'ai pas tout testé, il y en a peut être d'autres...

**Comment by Neelan22** [comment]
oui, apparemment la sauvegarde ne retient pas les choix faits dans le règlement. #772 
merci

**Comment by JulienNigon** [comment]
Les options mentionnées étaient effectivement mal sauvegardées. Merci beaucoup et désolé. Le patch de vendredi réglera ce soucis. Je ferme l'issue.

Encore merci pour vos (nombreux) retour Kaori01 :)
