### ISSUE TITLE
Professeur bloqué par des éléments du décor

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#79]
Test le 09/01/2019 au soir

Un de mes professeurs reste bloqué dans des éléments du décor:

Au début, il est coincé dans un encadrement de porte:
https://drive.google.com/open?id=1Cc4CAmdbFT3dj6awfSPAgYrQVSO6JTI5
https://drive.google.com/open?id=1iGa5N7MvuBlGGHdSnNnZcmXomNYwow4R (vue plus globale avec la salle où il est attribué en bas à droite)

Rien n'y fait (2 ans), jusqu'à ce qu'il y aie un feu dans la pièce d’à côté. Il va combattre le feu
https://drive.google.com/open?id=1SNjpOHpOeR7wXahDLDDd4LR6aJGD0XUC

Puis rebelote, il reste coincé dans la table de la salle...
https://drive.google.com/open?id=1rvhlr-9wPFTw2dFDuI-CVqIiL7LA35it

... jusqu'à ce qu'un portail s'ouvre dans une autre pièce (tout en haut à gauche de l'école), j'ai pas réussi a prendre de capture mais il reste encore une fois bloqué dans cette pièce : https://drive.google.com/open?id=14Lfx7-8zs6WdgyzPC6gn_pEIHbsESih3

(j'ai pas pensé a tester les commandes de débug pour voir sa réaction)

**Comment by JulienNigon** [comment]
Ok. bien reçu. Je vais regarder si ce n'est pas lié à sa salle de cours. Tu l'as déjà vu donner un cours ce professeur?

**Comment by Fouindor** [comment]
Je ne pense pas mais j'ai pas fait gaffe, j'ai pas sauvegardé la partie pour vérifier :(

Edit : C'est un professeur de magie sacrée (donc cloitre), ça n'aurait pas un lien avec #82 ?

**Comment by JulienNigon** [comment]
Ah, ça se pourrait en effet. Je regarderai. Merci.

**Comment by Fouindor** [comment]
https://drive.google.com/open?id=1iD6WIyET9tiVk-1gpFmnZmFbT-b8yk51

ça a bien l'air d'être lié au cloitre. (ça me semblerait bizarre que ça tombe deux fois sur le professeur du cloitre sur deux parties différentes)

**Comment by Fouindor** [comment]
Bug également présent dans la v0.62.
Faire "TP back" sur le professeur affligé ne le débloque pas (il reste coincé dans la zone de départ)
A chaque fois mes cloitres sont au sol, je réessaierai de le construire dans un étage la prochaine fois.

**Comment by Fouindor** [comment]
Testé hier, construire un cloitre dans sur un étage ne change rien. Chose bizarre, j'ai vu des élèves y aller alors qu'il n'y avait pas de professeur.

**Comment by JulienNigon** [comment]
Le cloître fait des choses très bizarre. Je pense qu'il y aura un correctif vendredi.

**Comment by Fouindor** [comment]
Edit : https://drive.google.com/open?id=1hunTjEFuHC7PP2-ZYxYqqAPoIcbJ54wT

Je crois que cette pièce est maudite :'( 
https://www.youtube.com/watch?v=aCbfMkh940Q

**Comment by JulienNigon** [comment]
Normalement la malédiction du cloître est levée
