### ISSUE TITLE
Bug : Les pirates n'aident pas

### ISSUE THREAD

**Issue by CherryWingNLR** [JulienNigon/SpellcasterUniversity-Bug-Report#792]
Coucou ! Un dernier bug recensé lors de la mission finale.

J'ai rencontré et accomplit la quête des pirates, lorsque l'option impliquant les pirates est arrivée, je ne pouvais pas la sélectionner, alors que j'avais remplis les conditions et rencontré les pirates au cours de la campagne

**Comment by Neelan22** [comment]
Ok, ce n'est pas la première fois que c'est annoncé ici. Il y a donc un souci. Merci !

**Comment by MerguezHalal** [comment]
Même problème ici !

**Comment by kaori01** [comment]
idem ici.
Je me pose une question, ne seraient-ce pas les prérequis qui ne seraient tout bêtement pas annoncés? Du coup je vais faire l'expérience en montant à 2000 tous mes decks... on verra bien!

![image](https://user-images.githubusercontent.com/60629516/74548650-8d9ad780-4f4e-11ea-9282-98fa5c20897b.png)

**Comment by kaori01** [comment]
Bon ben j'aurais essayé... soit ça n'est pas activable du tout, soit il y a un prérequis (salle, objet) que je n'ai toujours pas... tant pis, du coup, j'ai filé le commandement aux deux endives... ^^

![image](https://user-images.githubusercontent.com/60629516/74550903-7cec6080-4f52-11ea-9aa1-85d96beacf76.png)

**Comment by Neelan22** [comment]
Oui il y a un bug sur cette quête, on est dessus, merci.

**Comment by JulienNigon** [comment]
Corrigé pour la mise à jour de demain. Désolé pour ceux qui en ont fait les frais...
Merci !

**Comment by Florane88** [comment]
J'ai été trop pressée, j'ai fini ma campagne tout à l'heure, avant la mise à jour, du coup j'ai de nouveau eu ce bug. 
Hâte de charger la MAJ !! :)
