### ISSUE TITLE
nom des maisons

### ISSUE THREAD

**Issue by cb1504** [JulienNigon/SpellcasterUniversity-Bug-Report#794]
bonjour,
lorsque je ferme le jeu et que j'y reviens plus tard, le nom des maisons est alors suivi d'un point d'interrogation. il n'y a pas de lettre qui saute, juste ce "?" qui s'ajoute.
bonne continuation,
cb

**Comment by CherryWingNLR** [comment]
Tu m'as devancé ! J'allais aussi report ce bug. Tu n'es pas le seul dans ce cas là !

**Comment by Neelan22** [comment]
Bonjour,
ok c'est noté, merci.

**Comment by Neelan22** [comment]
Nous fermerons l'issue quand le bug sera corrigé, merci :)

**Comment by JulienNigon** [comment]
Corrigé pour la futur mise à jour (vendredi prochain). Merci encore !
