### ISSUE TITLE
Event - Réapparition régulière des conséquences de l'expédition

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#80]
Test le 09/01/2019 au soir

Une fois que j'ai lancé l'expédition avec mes 50 gold, j'ai quelques temps après les conséquences (normal jusque là), mais elles réapparaissent de manière régulière :

https://drive.google.com/open?id=1aeVWi9GgJjX1xG1MgjVTX8OZD123wxhC
https://drive.google.com/open?id=1W9StncrEvfW6oL-1aWpWbibrvpff93fp

(j'ai pris que deux captures mais c'est apparu plus de fois)

**Comment by JulienNigon** [comment]
Effectivement, il y avait un problème dans le moteur d’événement. Il est corrigé maintenant.
