### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Jeremy-Duval** [JulienNigon/SpellcasterUniversity-Bug-Report#807]
Le destin fossoyeur ne donne pas de carte de l'ombre.

**Comment by kaori01** [comment]
fossoyeur ne donne pas de carte d'ombre, il te donne des points de mana quand tu pioches une carte ombre... ;)

**Comment by JulienNigon** [comment]
C'est exactement ça ! Merci pour le retour quand même, je vais voir si il y a moyen d'éclaircir l'effet de cet avenir :)
