### ISSUE TITLE
bug mineur: Un squelette apparait direct à l'intérieur

### ISSUE THREAD

**Issue by Salvador1312** [JulienNigon/SpellcasterUniversity-Bug-Report#809]
Lors d'une attaque de squelette du Seigneur du Mal, j'ai capté deux fois en une game qu'un squelette sortait du sol de l'escalier au premier étage. C'était en forêt et je vérifierai sur les autres zones si c'est aussi le cas.

![20200209144133_1](https://user-images.githubusercontent.com/60800668/74335128-c21a6200-4d9b-11ea-96bd-e543dec1e02c.jpg)

**Comment by Neelan22** [comment]
Oui, les squelettes sortent du sol sur la carte du marais. Si tu as construit une salle sur un de ces emplacements, il apparaitra directement dans le château. Ce n'est pas un bug.
