### ISSUE TITLE
Impossible de fermer la fiche des professeurs

### ISSUE THREAD

**Issue by Fouindor** [JulienNigon/SpellcasterUniversity-Bug-Report#81]
Test le 09/01/2019 au soir

Quand je clique sur la croix, ça ne ferme pas la fiche des profs (mais ça marche pour les fiches d’élèves !)

edit : par contre, quand je clique sur un élève, ça ouvre sa fiche et quand je la ferme, il n'y a plus rien

**Comment by Sachalandis** [comment]
Le problème est revenu : impossible de fermer les fiches des professeurs.
