### ISSUE TITLE
Potentiel bug: Le mécénat fonctionne-t-il?

### ISSUE THREAD

**Issue by Salvador1312** [JulienNigon/SpellcasterUniversity-Bug-Report#811]
Comme je n'avais rien capté de flagrant durant ma première game, j'ai fait le test sur celle en cours: je n'arrive pas à tirer parti du mécénat.

Si j'ai bien compris, lorsqu'il est activé on est censé gagner des thunes (combien?) contre une perte de prestige chaque saison. Mais je ne vois rien du genre (que ce soit niveau finances ou niveau prestige) quand je le tente. J'ai donc regardé si c'était l'explication qui n'était pas bonne et donc tenté de vérifier si ce n'était pas chaque année (en prenant soin de le laisser actif toute une année), mais rien non plus. Donc je pense que cette option n'est pas fonctionnelle, si ce n'est pas moi qui me goure quelque part. J'ai fait des screenshots pour appuyer ce post.

(Pour préciser, je suis en train de retenter une partie avec tout gratis, mais cette fois-ci en tentant de respecter le fait d'avoir assez de thunes pour payer les profs afin de voir si c'est viable sans jouer sur l'absence de déficit: pour l'instant c'est faisable, on va voir pour la fin de campagne et les malédictions que je vais chopper entre deux. Mais je précise ça surtout pour dire qu'on peut mieux suivre les évolutions financières)

Début de game: après les achats de base avec le deck principal, il me reste 150 po. Le mécénat est activé depuis le début, mais pas d'autre évolution que le coût de l'entretien et du salaire (plus des petites décimales cachées je pense, qui me tirent une po surprise)
![20200208230118_1](https://user-images.githubusercontent.com/60800668/74336934-9bf6c100-4d9f-11ea-8521-9b42d569a339.jpg)

Idem ici
![20200208231010_1](https://user-images.githubusercontent.com/60800668/74337034-d1031380-4d9f-11ea-9ecb-356fcd06791b.jpg)

Idem
![20200208232231_1](https://user-images.githubusercontent.com/60800668/74337155-0dcf0a80-4da0-11ea-8dec-dcc59216f3ad.jpg)

Ici, précisons que je suis allé quémander des thunes chez les aventuriers: 72+250=322, 322-32(charges)=290
![20200208232841_1](https://user-images.githubusercontent.com/60800668/74337473-a49bc700-4da0-11ea-9234-46c9c97fcd48.jpg)

Ici que les charges
![20200208233600_1](https://user-images.githubusercontent.com/60800668/74337571-d3b23880-4da0-11ea-9ade-dd3c95c90e6c.jpg)

Idem
![20200208234020_1](https://user-images.githubusercontent.com/60800668/74337656-fba19c00-4da0-11ea-9948-fe79580983fd.jpg)

Etc. A noter qu'aucune évolution négative du prestige n'est visible non plus.

**Comment by kaori01** [comment]
La gratuité, avec les sources de revenu externes, c'est tout à fait viable (et ne parlons pas de l'almanach des sports ;) ). Je plussoie ton impression concernant le mécénat, je joue en tout gratis depuis un bon moment et je n'arrive pas à voir où est l'argent du mécénat, ni d'ailleurs le malus de prestige (ceci dit l'absence de descriptifs précis pour tout ne facilite pas les choses). D'ailleurs en prime attention quand on sauve/load, ça se désactive, le mécénat, il faut les cocher de nouveau (en fait les deux autres options de la section aussi).

**Comment by Neelan22** [comment]
ok, on va regarder ça, merci !

**Comment by Juliusmagnus1986** [comment]
Oui, jamais vu aucun changement de pépètes ni de prestige avec cette option non plus.

**Comment by JulienNigon** [comment]
Bien vu ! Navré pour ces soucis (sauvegarde + effet inactif). Ils seront corrigés dans la mise à jour de vendredi. Par ailleurs c'est vrai que l'effet du mécénat n'est pas très détaillé, mais nous allons peut être le modifier avant de réécrire la description.
