### ISSUE TITLE
Incohérence: La surdité qui empêche de lire

### ISSUE THREAD

**Issue by Salvador1312** [JulienNigon/SpellcasterUniversity-Bug-Report#812]
Tout est dans le titre: soit vous avez un humour plus tordu que le mien et j'ai pas capté le truc, soit il y a incohérence avec la description de la surdité: "ça ne sert à rien d'écrire ce que ça fait, il ne pourra pas le lire de toute façon"; on n'a pas dit "sourd et aveugle" pourtant.

![20200208231354_1](https://user-images.githubusercontent.com/60800668/74339215-ebd78700-4da3-11ea-950a-dc7e27c00beb.jpg)

Et ptite réflexion bonus: du coup la surdité c'est muable? Parce que techniquement ici ça peut disparaître avec un lit de la repentance ou un prof  inspirant: donc en fait l'étudiant fait du chiqué. Mais là-dessus vous êtes tout a fait disposés à vous défendre avec la phrase bien connue des rôlistes: "Ta gueule, c'est magique." Ce serait raccord.

**Comment by kaori01** [comment]
héhé en même temps un lit à piques dans lequel tu dors comme une masse, et qui te supprime net ton racisme ou ton allergie au pollen... TGCM de base ;)

**Comment by Neelan22** [comment]
J'ai confirmation dans l'oreillette que celui qui a fait cette blague était en pleine possession de ces moyens et ne semble pas vouloir s'excuser pour sa blague ^^

**Comment by JulienNigon** [comment]
Cette description est vraiment perchée, c'est vrai... certains membres de l'équipe ont vraiment des problèmes !
