### ISSUE TITLE
archimage?

### ISSUE THREAD

**Issue by kaori01** [JulienNigon/SpellcasterUniversity-Bug-Report#817]
coucou, on m'a dit que le problème était résolu, mais je n'ai pas l'impression qu'il le soit totalement... voici la fiche d'un de mes élèves...

![image](https://user-images.githubusercontent.com/60629516/74531491-0f7a0900-4f2d-11ea-9a12-fb9d007ae445.png)

**Comment by kaori01** [comment]
et voilà ce qu'on lui propose...

![image](https://user-images.githubusercontent.com/60629516/74531504-1e60bb80-4f2d-11ea-90ff-2e839a58d407.png)

On m'avait dit que pour un archimage il fallait 4 compétences à 5... il en a 6....

**Comment by Crampolo** [comment]
Même avec les quatres compétences level 5, il y a une part de chance pour que l'avenir apparaisse dans les possibilités

**Comment by Juliusmagnus1986** [comment]
Oui pareil, même avec 5-6 compétences lvl 5, parfois archimage apparaît dans la liste avec 21% de chances, parfois même pas :p c'est vrai que c'est frustrant. Le mec a les capacités mais finit aubergiste ! Sans offense pour les aubergistes.

**Comment by CherryWingNLR** [comment]
Je n'ai pas compté si le total des pourcentages donne 100, mais peut-être que l'archimage est dans la liste, mais comme pour les caractéristiques des élèves, il n'est pas affiché. Ou alors, ton étudiant est trop polyvalent et à un choix beaucoup trop large. Je te conseil de faire des classes spécialisées avec deux ou 3 type de cours. Ça évite que tes étudiants se dispersent, et seulement deux types de cours autorisés suffisent pour avoir un archimage.

**Comment by kaori01** [comment]
Ça rend la quête de l'archimage trop aléatoire pour être intéressante... tant pis je continuerai à la refuser et faire les autres... Ça aura eu le mérite de me forcer à mieux "minimaxer", mes étudiants sont tous mieux instruits qu'à mes débuts... ;)

**Comment by CherryWingNLR** [comment]
Moi, je prends jamais cette quête, à moins d'être en marathon. Et puis bon, 10 de prestige, c'est pas cher payer pour éviter un tas d'ennui et faire plaisir à cet imbécile

**Comment by kaori01** [comment]
Oh que oui... d'ailleurs, j'ai beaucoup ri la première fois que j'ai choisi l'option de détourner les forces du mal sur une université concurrente (à faire au moins une fois pour lire les dialogues 😆  ). Un juste retour de bâton pour ce prétentieux avec ses élèves archimages en deux jours et son gluten dans mes carottes... 😛

**Comment by Lakalache** [comment]
J'ai attaqué ma 2e campagne en vitesse marathon et je fais des archimages à chaque école.

Je ne sais plus combien de temps j'ai passé sur l'école que je joue en ce moment mais les ténèbres n'ont avancé que de 20% et j'ai déjà sorti 2 archimages.
Voici quelques paramètres qui ont pu jouer (ou pas... étant un joueur, les calculs de probabilité me sont inconnus. Ca a un côté marrant quand même de ne pas avoir accès à tous les rouages.)
-> salles améliorées (mais pas tant que ça !)
-> marche mieux avec des élèves autorisés à faire que 2 types de magie
-> vu le pourcentage de réussite, les élèves étaient surement très intelligents (brillant) et/ou travailleur et/ou initié...
-> je venais de régler un problème d'ennui. Globalement tous les besoins étaient satisfaits : les élèves partaient beaucoup moins pour aller au village
-> j'ai des conseillers d'orientation
-> j'ai des élèves diplômés qui ont donné des bonus "sage", "travailleur", etc.
-> je relance le destin quand je vois archimage dans les probas.
-> j'ai des dragons et des artefacts un peu partout

Je crois que dans ma première partie à vitesse moyenne, j'ai réussi à avoir une fois ou 2 un archimage sur la totalité des écoles. Pas facile en effet.

Je trouve que la récompense des marchands est un peu plus intéressante... au tout début de partie mais c'est tout. L'archimage est plus gratifiant quand même.

PS : je viens de voir tes screenshots Kaori. J'avais pas relevé que c'était possible ce cas là. Les hypothèses possibles (d'après ce que j'ai dit plus haut) sont qu'il faille un trait de personnalité (exemple : ambitieux) ou un alignement particulier (exemple : je sais pas :p ) ou une séance avec un conseiller d'orientation pour débloquer la proba d'un archimage. Après, qu'elle est la solution entre les 3... Je ne sais pas.

**Comment by kaori01** [comment]
Si tu refuses la quête des marchands, tu en obtiens une un peu plus "morale", où tu dois former plus de cent étudiants avant la fin ;)
Je n'ai pas limité le nombre d'écoles, je vais tester... ^^

**Comment by CherryWingNLR** [comment]
Je sais. Sauf que j'adore l'argent

**Comment by JulienNigon** [comment]
Désolé pour ce bug, et merci de l'avoir repéré... la mise à jour du vendredi 21 corrigera ce problème. Pour la petite histoire, c'est une grossière erreur de l'équipe de développement (aka moi) qui retirait tous les avenirs les PLUS probables au lieu des moins probables quand l'étudiant avait plus de 18 options. Incidemment, cela devrait permettre d'accéder à des avenirs rares pratiquement inaccessibles jusqu'à aujourd'hui.

**Comment by JulienNigon** [comment]
Je note comme réglé même si la correction n'est pas encore déployée.
