### ISSUE TITLE
Plus de sauvegarde possible, de retour au menu ou de "quitter"

### ISSUE THREAD

**Issue by choumagna** [JulienNigon/SpellcasterUniversity-Bug-Report#819]
Bonsoir !

Il y a 3 jours, le jeu fonctionnait très bien sur mon pc. Puis j'ai dû faire une mise à jour de Windows et depuis.... Impossible de sauvegarder, de retourner au menu, ou de quitter le jeu. Tout ce que je peux sélectionner dans le menu, c'est "annuler" et "options".

J'ai essayé ces trois derniers jours, et perdu mes dernières parties, faute de sauvegarde.... Je suppose que le souci est lié à cette mise à jour car auparavant, il n'y avait pas de souci. Quelqu'un rencontre-t-il le même problème ou saurait le régler ?

Merci d'avance :-)

**Comment by Lakalache** [comment]
Windows 10? pas de problème. Je ne me souviens plus de l'ordre entre update w10 et update du jeu qui sont intervenues la même semaine mais ca roule de mon côté

**Comment by choumagna** [comment]
Hello, oui c'est Windows 10. Je crois que la mise à jour du jeu était Samedi dernier et la mise à jour de Windows Mercredi (je crois...). Mince, ce serait dû à autre chose alors ? J'ai retenté en me levant ce matin, mais en vain.

    Le vendredi 14 février 2020 à 22:09:29 UTC+1, Lakalache <notifications@github.com> a écrit :  
 
 
Windows 10? pas de problème. Je ne me souviens plus de l'ordre entre update w10 et update du jeu qui sont intervenues la même semaine mais ca roule de mon côté

**Comment by Neelan22** [comment]
C'est pas bon signe ça... Je vais voir si on a d'autres issues comme ça. Si il n'y a pas d'amélioration d'ici là et si la mise à jour de vendredi n'améliore rien non plus, peux tu nous le dire ici stp? Si tout revient dans l'ordre, tu pourras fermer l'issue.
désolée pour ce bug :/

**Comment by choumagna** [comment]
Bonsoir,
Pas de souci, je verrai Vendredi. C'est pas très grave, je suis en pleins partiels en ce moment, ça m'oblige à ne pas jouer. Je fermerai si ça revient à la normale.
Bonne soirée

    Le mardi 18 février 2020 à 14:07:28 UTC+1, Neelan22 <notifications@github.com> a écrit :  
 
 
C'est pas bon signe ça... Je vais voir si on a d'autres issues comme ça. Si il n'y a pas d'amélioration d'ici là et si la mise à jour de vendredi n'améliore rien non plus, peux tu nous le dire ici stp? Si tout revient dans l'ordre, tu pourras fermer l'issue.
désolée pour ce bug :/

**Comment by choumagna** [comment]
Bonjour ! 

Après test aujourd'hui, le jeu refonctionne très bien :-).
Je peux de nouveau sauvegarder, charger ma partie, revenir au menu... Merci beaucoup.

Je ferme l'issue.
