### ISSUE TITLE
L'or n'augmente plus

### ISSUE THREAD

**Issue by Dauphinkivol** [JulienNigon/SpellcasterUniversity-Bug-Report#822]
C'est la première fois que ça m'arrive en une vingtaine de parties. J'en suis à ma quatrième partie de la campagne, sur le biome de la plage, et mon or a arrêté de monter, il ne fait que descendre les jours de salaire, et n'est remonté que par les recrutements et le grimoire qui donne 700 chaque année.

**Comment by MlleMau** [comment]
Bonjour Dauphinkivol,

Question bête mais... tu n'as pas mis le réfectoire et les dortoirs gratuits ?

**Comment by Dauphinkivol** [comment]
Effectivement... Je pensais que les élèves généraient de l'or en dehors de ces deux activités, de manière passive. Merci
