### ISSUE TITLE
Cloitre des justes

### ISSUE THREAD

**Issue by MetyNapa** [JulienNigon/SpellcasterUniversity-Bug-Report#826]
Impossible de construire au-dessus d'un cloitre des justes alors que les flèches bleues apparaissent bien au moment de la construction.

**Comment by Florane88** [comment]
Ah oui, tiens, je l'avais oublié dans ma liste de choses à signaler !

Encore une carte à éclaircir au niveau indications de construction car effectivement, il est indiqué que le cloitre peut communiquer avec des salles directement au-dessus mais en fait il fonctionne comme la serre en "occupant" un étage au-dessus, sur lequel on ne peut rien construire.

**Comment by JulienNigon** [comment]
Bien vu ! Merci à vous, le correctif sera disponible dans le patch du vendredi 21. Je note comme résolu.
