### ISSUE TITLE
Citadelle Lacustre - Evenement Créature du Lac + Orcs - Clef Inexistante

### ISSUE THREAD

**Issue by Hyslyne** [JulienNigon/SpellcasterUniversity-Bug-Report#828]
Bonjour,
J'ai dit que je ne voulais pas de la créature du lac, du coup les orcs sont venus en demandant à la manger...
Je fais donc les évènements des orcs et pour le dernier, ça me dit que j'ai reçu un modificateur global mais je ne peux pas savoir quoi exactement parce qu'il y a marqué "Clef Inexistante" et je ne vois pas le modificateur sur les élèves ou professeurs donc je ne peux pas voir si c'est pas marqué ailleurs.
Je l'ai refait dans une autre partie et toujours le même problème.
![20200216202445_1](https://user-images.githubusercontent.com/60525061/74611634-e066c180-50fd-11ea-9cdb-55edeb106aab.jpg)

**Comment by JulienNigon** [comment]
Merci beaucoup pour le retour et navré pour ce soucis avec le monstre du lac. C'est corrigé mais le patch ne sera déployé que vendredi. Pour info, l'effet boost tout vos personnages en les immunisant à la faim jusqu'à la fin de la partie. Je ferme l'issue.
