### ISSUE TITLE
Bug cartes artefacts guilde des Aventuriers

### ISSUE THREAD

**Issue by KesneyTorras** [JulienNigon/SpellcasterUniversity-Bug-Report#831]
Bonjour,

Durant ma dernière partie en mode normal, j'ai contacté la guilde des aventuriers pour leur demander un artefacts. Au lieu d'avoir le choix entre trois cartes, une seule est apparue à l'écran.

C'était le dernier quart de la partie, en mode Wizard, marathon, réputation au-delà de 70 uniquement obtenue avec la bannière.
C'est la seule fois que je les ai contacté lors de cette partie.

**Comment by JulienNigon** [comment]
C'est noté, merci pour le retour et navré pour le bug... nous allons essayer de le reproduire.

**Comment by JulienNigon** [comment]
Corrigé depuis la dernière mise à jour. Merci beaucoup !
