### ISSUE TITLE
Une faute lors du tuto

### ISSUE THREAD

**Issue by Karcad001** [JulienNigon/SpellcasterUniversity-Bug-Report#834]
Bonjour,

En ouvrant le tuto j'ai remarqué une petite faute dans la première phrase. Vous utilisez "prêt" au lieu de "près".
J'ai aussi au le cas d'un crane que je ne pouvais attribuer à aucune salles (dsl je ne me souviens plus du nom du crane).
![image](https://user-images.githubusercontent.com/61183446/74720125-91bc4300-5235-11ea-8f2e-ce83d85865d9.png)

**Comment by Neelan22** [comment]
Ok, merci :)
#619 #670 #827
