### ISSUE TITLE
Perte objectif final après recharge sauvegarde

### ISSUE THREAD

**Issue by WasabiJack** [JulienNigon/SpellcasterUniversity-Bug-Report#835]
Je suis arrivé à la fin des objectifs multiples de la dernière mission (la tortue), et ne voulant pas m’arrêter tout de suite (mode marathon début de cycle), j'ai quitté via le menu. Mais en rechargeant, les objectifs restaient validés. Je suis donc incapable de débloquer le trophée "fin difficile" (et accessoirement "finir la campagne") via cette sauvegarde. Les autres objectifs, secondaires continus d'apparaitre. Juste l'objectif principal est manquant.

**Comment by Neelan22** [comment]
Les objectifs n'étaient pas validés avant la sauvegarde?

**Comment by WasabiJack** [comment]
Si. J'ai validé tout les objectifs (y compris le choix de désigner le prof meneur de grève à la tête de l'armée :D) et ainsi accédé à la fin de la campagne (ou je vois tout les étudiants et profs sortir en courant de l'école). Voulant continuer ma partie car je voulais maximiser les avenirs des élèves (et atteindre archimage), j'ai reload la partie, mais elle semble reprendre APRES la validation du dernier objectif, pourtant je peux toujours jouer (pas de "fin de campagne"), avoir des évènements aléatoires et ceux cycliques, mais je ne peux plus re-choisir qui accompagnera l'armée. Je ne peux donc plus, sur cette partie, obtenir "terminer une campagne" ni "terminer en mode difficile". C'est embêtant, car étant ma 3ème campagne, je voudrais plutôt retenter l'autre mode.
En espérant être clair dans ma description.

**Comment by Neelan22** [comment]
AAhh, ok, je pense avoir compris. On va voir si c'est possible de corriger ça d'ici demain.

**Comment by WasabiJack** [comment]
Cool. La solution que je visualise la plus aisée, serait de ne pas faire de sauvegarde auto juste après la validation du dernier objectif.
Bon courage.

**Comment by Neelan22** [comment]
corrigé pour la prochaine mise à jour
