### ISSUE TITLE
Bug de l'interface lors du choix d'un artefact depuis la guilde

### ISSUE THREAD

**Issue by Karcad001** [JulienNigon/SpellcasterUniversity-Bug-Report#836]
J'ai eu deux fois d'affilée le même bug lors du choix d'un artefact auprès de la guilde des aventuriers.
Le choix des cartes ne s'affiche pas et bloque l'écran : je peux toujours "bouger" en approchant la souris des bords et lorsque je survole les menus et objets je vois leur description mais rien ne se passe si je clique. En appuyant sur echap, le menu ne s'affiche pas donc j'ai du tuer le jeu via le gestionnaire des taches.

**Comment by Neelan22** [comment]
ah mince c'est un vilain bug ça. C'est au moment ou les cartes apparaissent?

**Comment by Karcad001** [comment]
C'est au moment où elles devraient apparaître oui. Cependant elles n'apparaissant pas.

**Comment by JulienNigon** [comment]
Corrigé. le patch sera disponible dans quelques heures. Merci beaucoup et désolé pour le soucis.
