### ISSUE TITLE
concièrge bloqué dans l'étable...

### ISSUE THREAD

**Issue by kaori01** [JulienNigon/SpellcasterUniversity-Bug-Report#838]
recharger ne change rien, il fait toujours son moonwalk... 🕺 

![image](https://user-images.githubusercontent.com/60629516/74812899-9a278300-52f4-11ea-9fbd-449799c469b1.png)

**Comment by Neelan22** [comment]
Oui, on a vu que certains personnages aimaient bien aller dans l'enclos :/

**Comment by JulienNigon** [comment]
Corrigé. Disponible dans la mise à jours de demain !
