### ISSUE TITLE
Impossible de poser le belvédère

### ISSUE THREAD

**Issue by jean-luc22** [JulienNigon/SpellcasterUniversity-Bug-Report#856]
J'ai pioché la carte belvédère, sauf que je ne peux pas l'installer dans mon université. 
La preuve en image. 
Ou sinon, y-a-t-il des conditions spécifiques pour installer un belvédère ? Si oui, il serait sage de l'expliquer. 

Bonne journée et merci pour ce jeu
![250220-01](https://user-images.githubusercontent.com/61394857/75279357-c0c14e80-580b-11ea-94ad-6630aaef6be9.png)

**Comment by jean-luc22** [comment]
Bonjour, 
plus loin dans la partie, j'ai réussit à installer le belvédère. Il est positionné sur le niveau 3 et 4 de l'université (le RDC est conté comme le niveau zéro). 

Bonne journée

**Comment by Neelan22** [comment]
Bonjour,
oui il est compliqué à poser, on doit ajouter plus d'explications. Je ferme cette issue, il y a en une autre ouverte si il y a d'autres soucis.
