### ISSUE TITLE
Cumul de mana sans école de magie correspondante bugg

### ISSUE THREAD

**Issue by jean-luc22** [JulienNigon/SpellcasterUniversity-Bug-Report#858]
Bonjour, 

J'ai cumulé 11 mana de Lumière, sauf que je n'ai aucune salle d'apprentissage correspondante à l'école de magie de la Lumière dans mon université. 
Je vous transmet cette information qui pour moi est un bugg. 

Merci pour ce jeu et continuez comme ça, c'est cool !!!
![250220-03](https://user-images.githubusercontent.com/61394857/75281292-4b577d00-580f-11ea-99bb-a45c9eb2baa9.png)

**Comment by Neelan22** [comment]
Bonjour,
Cela peut être dû à un artefact qui génère de la lumière (comme un vitrail dans le réfectoire) ou à un avenir avec un malus (mage de campagne qui donne 15 de chaque mana) combiné au malus "malédiction d'antimagie". Cela semble possible?

**Comment by jean-luc22** [comment]
Bonjour, 
Je viens de vérifier attentivement la photo lorsque j'ai signalé le bugg. Il n'y a pas de vitrail dans aucune des pièces. 
La quantité de mana cumulé dans l'école de la lumière est de 11, cela ne peut donc pas être dût au bonus de l'avenir mage de campagne. 
Cela ne peut non plus dût à une combinaison du malus "malédiction d'antimagie" parce que à ce stade de la partie, je n'avais pas encore d'étudiant qui finissait leurs études. 

Bonne journée

**Comment by Florane88** [comment]
> La quantité de mana cumulé dans l'école de la lumière est de 11, cela ne peut donc pas être dût au bonus de l'avenir **mage de campagne**.

Effectivement, si tu en avais déjà formés, ne cherches pas plus loin, ça doit venir de là !

**Comment by MlleMau** [comment]
Bonjour jean-luc22,

Va t'en comprendre mais... certains élèves font des expérimentations dans la bibliothèque et apprennent n'importe quoi pour leur petit plaisir, ce qui nous donne du mana dans des magies que l'on n'utilise pas ! :laughing:

**Comment by jean-luc22** [comment]
ok, merci pour ces explication

**Comment by Neelan22** [comment]
oui bien vu MlleMau, le mana vient de la bibliothèque :)
Je ferme l'issue !
