### ISSUE TITLE
Potion du Vide Erreure ? 

### ISSUE THREAD

**Issue by jean-luc22** [JulienNigon/SpellcasterUniversity-Bug-Report#860]
Bonjour, 

Je viens de créer une potion du vide avec chapeau de je ne sais plus quoi, âme du dormeur et corne de licorne. De mémoire dans cet ordre là. J'obtiens une potion avec le texte suivant : "Ferme tous les portails vers le vide et éteint tous les incendies magiques" 
Est-ce que le texte correspond à la dite carte dans le jeu ? Si oui, tant mieux. 
Deuxième chose, les ingrédients que j'ai utilisé pour réaliser cette potion n'apparaisse pas dans mon livre de recette du chaudron. J'en ai bien une, pour la potion du vide, mais elle ne correspond pas au ingrédients que j'ai mis. 

Merci de faire tous les efforts que vous faites pour améliorer le jeu, bon courage. 
![250220-06](https://user-images.githubusercontent.com/61394857/75288175-130a6b80-581c-11ea-8f33-d76f6ea829d9.png)

**Comment by jean-luc22** [comment]
Re, je viens d'utiliser le chaudron avec un Chapeau, une plume et une âme de dormeur (dans cet ordre). J'obtiens une Potion du Vide.

**Comment by jean-luc22** [comment]
Re, je viens de comprendre que maintenant que l'âme de dormeur remplacait aléatoirement un troisième ingrédient. Désolé pour le dérangement.

**Comment by Neelan22** [comment]
C'est cela! On doit revoir sa description ;)
