### ISSUE TITLE
no needs increase after visiting psychologist 

### ISSUE THREAD

**Issue by calamityson** [JulienNigon/SpellcasterUniversity-Bug-Report#861]
All Students that have visited the psychologist don't have increase in hunger, boredom or tiredness any more.

**Comment by calamityson** [comment]
![psychatristnoneeds5](https://user-images.githubusercontent.com/56685332/75342892-95844100-5897-11ea-896e-247e68e23226.png)

These no-needs-students visit the same classes again and again, even with Level 5. They will not stop till the teacher leaves and return to same classes again later.

**Comment by calamityson** [comment]
The student in the picture became a gardener. New futures needed.

**Comment by Neelan22** [comment]
ok thank you for this issue !
we are currently working on new futures ;)

**Comment by JulienNigon** [comment]
Yes. We are writing more futures. And thanks for the bug, it will be patched in next release (next week).
