### ISSUE TITLE
Potions chitées

### ISSUE THREAD

**Issue by Ubblak** [JulienNigon/SpellcasterUniversity-Bug-Report#874]
Dès lors que l'on a accès aux composants, il devient très facile de faire une bonne run.

Parfois on en tire aucun de toute une run et c'est la misère...

n'y a t-il pas comme un déséquilibre ?

**Comment by Florane88** [comment]
_(désolée, hors sujet et mini coup-de-gueule, mais cette anglicisation à tout va m'exaspère !)_

Quand on ne sait pas écrire en anglais, on peut aussi utiliser des mots de sa langue "principale", à savoir le français, et mettre en titre "Potions trop puissantes ?" par exemple... 
De même qu'écrire "partie", avec ses 3 lettres de plus, n'a jamais tué personne et est compréhensible par tous les francophones.
_(sinon c'est "cheat")_


Bon, pour revenir au sujet, c'est vrai que ça change vraiment tout de pouvoir faire des potions ou pas, particulièrement quand on rencontre une faction qui en voudrait, ou sur la dernière carte !

D'une manière générale, le hasard est quand même très présent, surtout sur les parties courtes où on pioche au final bien moins de fois que sur des parties longues.

J'ai par exemple fait une partie où je n'ai réussi à piocher une salle pour les profs seulement à la touuuute fin de partie (je n'avais pas non plus de réfectoire lumineux), ben c'était vraiment galère vu qu'ils repartaient sans arrêt pour satisfaire leurs besoins ; l'enseignement et la production de mana n'avançaient paaaas !!

Après ce n'est pas un jeu où on est en concurrence avec les autres joueurs donc ce n'est pas bien grave de subir le hasard, et surtout c'est probablement une volonté des développeurs, sinon ils auraient proposé une dizaine de choix à chaque pioche par exemple.

**Comment by Ubblak** [comment]
Ah non Je m'insurge ! J'utilise deux fois le terme "run" et je ne suis repris QUE sur le terme "chité" (qui devrait s'écrire "cheaté").

Il n'en reste pas moins que Florane met le doigt sur quelque chose. L'algorithme de tirage aléatoire devrait être un peu rééquilibré.

**Comment by Ubblak** [comment]
Pardon, je vois que je suis aussi repris sur le terme "run".
Mais une run n'est pas une partie. La partie c'est l'ensemble des runs. La run c'est à la fois un style de jeu et une manière de jouer. 

Je ne crois pas qu'il existe un équivalent francophone pour un termesi spécifique.

**Comment by Neelan22** [comment]
pour la prochaine mise à jour nous allons rééquilibrer la génération de composants. Les composants rituels génèreront moins de cartes, entre autres.
