### ISSUE TITLE
Faute d'orthographe

### ISSUE THREAD

**Issue by Otiernagh** [JulienNigon/SpellcasterUniversity-Bug-Report#881]
Bonjour!
Merci pour votre travail avant tout!
Je souhaitais signaler une faute d'orthographe sur la scène de fin, au niveau de la phrase des aventuriers qui disparaissent du jour au lendemain, il n'y a pas de s à jour!
Cordialement,
OTIERNAGH

**Comment by Neelan22** [comment]
Ok, merci ! #619 #576 #670 #348

**Comment by JulienNigon** [comment]
Merci ! Corrigé dans la release de ce soir :)
