### ISSUE TITLE
Lits spéciaux dans les Appartements Privés

### ISSUE THREAD

**Issue by MlleMau** [JulienNigon/SpellcasterUniversity-Bug-Report#882]
Bonjour,

Dans les appartements privés des professeurs, il y a un lit qui peut être modifié. Le lit de base est à la bonne place et les professeurs se couchent parfaitement dessus. Cependant, il y a un bug graphique avec les lits spéciaux : ils sont placés plus en hauteur, mais les professeurs continuent de s'allonger comme s'il y avait le lit de base, plus bas.

Les screens seront plus parlants, je pense : 
![bug lit spécial appartements privés](https://user-images.githubusercontent.com/60859116/75988962-b3365380-5ef2-11ea-969e-b635647467f7.jpg)
![bug lit spécial appartements privés2](https://user-images.githubusercontent.com/60859116/75988991-c21d0600-5ef2-11ea-83a0-746e081e31fd.jpg)

Néanmoins, l'effet des lits spéciaux fonctionnent parfaitement : mon lit médical les soigne, et mon lit de la repentance leur fait bien perdre un trait négatif.

Bonne journée à vous,
Maureen.

P.S. pour Florane : J'ai trouvé comment mettre une image déjà enregistrée ! Il faut cliquer sur l'encadré "Attach files by dragging & dropping, selecting or pasting them" juste en dessous de la zone de texte.

**Comment by Florane88** [comment]
> P.S. pour Florane : J'ai trouvé comment mettre une image déjà enregistrée ! Il faut cliquer sur l'encadré "Attach files by dragging & dropping, selecting or pasting them" juste en dessous de la zone de texte.

Bien vu, merci d'avoir pensé à moi !! :D

**Comment by Neelan22** [comment]
peut etre qu'ils veulent juste regarder ce qu'il y a sous le lit !
Bug corrigé pour la release de ce soir ;)
