### ISSUE TITLE
Belvédère : impossible de le poser dans la forêt et de lac

### ISSUE THREAD

**Issue by Jesst89** [JulienNigon/SpellcasterUniversity-Bug-Report#896]

**Comment by Neelan22** [comment]
voici les conditions pour poser un belvédère : 
![image](https://user-images.githubusercontent.com/47151033/76100524-0aa8f200-5fcd-11ea-9fb6-4fb5ae6c7c71.png)

**Comment by Jesst89** [comment]
Merci de ta réponse et de ta réactivité :)
