### ISSUE TITLE
Impossible de se déplacer à la souris vers la direction du deuxième écran

### ISSUE THREAD

**Issue by jeremy-boes** [JulienNigon/SpellcasterUniversity-Bug-Report#90]
J'ai deux écrans. Je joue avec le jeu sur l'écran de gauche.

Si je veux me déplacer vers la droite à la souris, mon curseur passe sur mon deuxième écran et rien ne se passe.

**Comment by JulienNigon** [comment]
La souris est désormais confinée au jeu. On verra à l'usage si ça convient aux testeurs.
