### ISSUE TITLE
(Avenir - conditions non remplies) => A FERMER ?

### ISSUE THREAD

**Issue by Florane88** [JulienNigon/SpellcasterUniversity-Bug-Report#903]
_(pas évident de trouver un titre...)_

Parmi les avenirs obtenus en version 0.91, j'ai eu "Démoniste". Par curiosité, j'ai regardé si les conditions avaient changé depuis la version précédente, et là je découvre : 
"Modificateurs : Possède le trait Brute"
or l'élève en question qui pouvait devenir démoniste n'était PAS brute (juste Procrastinateur).

Je me suis dit qu'il avait peut-être par hasard perdu son trait (étant donné que j'avais un unique lit de la repentance), mais : 

1.  ça ne me semble pas logique car l'avenir en sortie d'école devrait s'appuyer sur les caractéristiques des élèves au moment de l'obtention de leur diplôme
2.  ça ne me semble pas du tout probable car je n'aime pas les brutes et normalement je les refuse (mais bon, un défaut d'attention peut arriver)

**Comment by MlleMau** [comment]
Coucou Florane88,

J'ai déjà remarqué cela également. En vérité, il y a des "Conditions" et des "Modificateurs", cela signifie que tu as plus de chance d'obtenir cet avenir si ton élève possède ce modificateur (qui peut être un trait de caractère ou une autre magie). Ainsi, tu peux avoir un démoniste tout gentil, il aura simplement moins de chance de l'être.
N'hésitez pas à me dire si j'ai mal interprété le texte et que je fais fausse route !

**Comment by Florane88** [comment]
> il y a des "Conditions" et des "Modificateurs", cela signifie que tu as plus de chance d'obtenir cet avenir si ton élève possède ce modificateur 

Ahhhh, mais bien sûr !! Une fois expliqué ça semble tout à faire logique !
Je pense donc qu'on peut clôturer le sujet ^^

**Comment by Neelan22** [comment]
Alors, il y a effectivement des modificateurs qui permettent de faire pencher la balance vers certains avenirs. Exemple : un ménestrel aura un plus grand % d'avenir possible si l'élève est chaotique.
Toutefois, cela reste différent des conditions, qui elles sont indispensables pour obtenir certains avenirs. Exemple : un Zombie DOIT avoir le trait amorphe.
Je laisse l'issue ouverte le temps qu'on vérifie si le bon terme (condition ou modificateur) a été utilisé pour le démoniste.
merci pour le retour

**Comment by Florane88** [comment]
> Je laisse l'issue ouverte le temps qu'on vérifie si le bon terme (condition ou modificateur) a été utilisé pour le démoniste.

C'est sûr, c'était un "modificateur" :  je n'ai pas fait d'aperçu écran mais je l'ai noté sur papier au moment où je l'ai vu.
Du coup désolée de vous avoir dérangés pour rien avec ce sujet...

**Comment by Neelan22** [comment]
pas de souci ;)
