### ISSUE TITLE
Souci bloquant lors du démarrage des tableaux désert et marais depuis v0.91

### ISSUE THREAD

**Issue by Simon-Lessard** [JulienNigon/SpellcasterUniversity-Bug-Report#904]
Lorsque les tableaux marais ou désert sont lancés (peut-être d'autres également, mais les volcans fonctionnent donc ce n'est pas pour tous) le tableau s'ouvre avec un écran de sélection d'avenir pour un certain Leonard Ray . Il est impossible de sélectionner un avenir et l'écran reste donc toujorus disponible cachant l'écran principal et empêchant la sélection des items du menu Settings (impossible de quitter sans tuer le jeu). À noter que le dit menu settings s'affiche tout de m^me au dessu de l'écran de sélection de l'avenir, mais les boutons sont incliquables.

Sans le menu settings :
![leonard-ray](https://user-images.githubusercontent.com/23580881/76143132-d983fc80-6074-11ea-9fef-d24ba98b3e1c.png)

En ouvrant le menu Settings (qui n'est pas utilisble) : 
![leonard-ray-menu](https://user-images.githubusercontent.com/23580881/76143136-e7398200-6074-11ea-873a-05af8bde028f.png)

**Comment by Simon-Lessard** [comment]
Les pics montagneux fonctionnent bien aussi, je n'ai pas essayé le ciel. Avant ce souci j'ai correctement pu faire la plaine, le lac et celui des vikings/pirates (rivage?), ces derniers fonctionnent correctement.

**Comment by Neelan22** [comment]
Ah ben mince alors ! et donc la campagne n'est plus du tout jouable??
C'est possible d'avoir la sauvegarde stp?
PC :
C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster University
Mac :
~/Library/Application Support/Sneaky Yak Studio/Spellcaster University/Saves

**Comment by Simon-Lessard** [comment]
Voici un save, il faut jsute terminer le tableau et sélectionner le marais pour reproduire à tout coup.
[save.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/4308550/save.zip)

La campagne reste jouable sur d'autres tableau, mais je veux vraiment faire le marais là :(

**Comment by Neelan22** [comment]
Nous avons fait un hot fix hier soir. Est ce que cela a résolu le problème?

**Comment by Simon-Lessard** [comment]
C'est effectivement corrigé.
