### ISSUE TITLE
Lenteurs et maintenant je ne peux plus lancer la partie

### ISSUE THREAD

**Issue by Hyslyne** [JulienNigon/SpellcasterUniversity-Bug-Report#908]
Bonsoir.
Je suis sur une partie sans fin sur le lac. ça fait une petite heure que le jeu était ralentit, particulièrement au moment du recrutement des nouveaux élèves. Je ne sais pas si ça a avoir avec le nombre d'élèves dans mon école ( j'étais proche des 100 ) ? Les cartes des nouveaux élèves n'apparaissaient pas toutes, j'étais obligée de cliquer sur une classe pour passer à la suite ( du coup je ne savais pas ce que j'étais en train d'accepter dans mon école ). Et après avoir cliqué, y'avait une petite attente.
Je coupe le jeu et je relance pour voir si ça va mieux... c'est pire ! Quand je lance la partie en question, tous les personnages sont multipliés par 10, le jeu tente de faire bouger tout ça puis finit par freeze complètement et je suis obligée de faire crash l'application pour réussir à la fermer.
J'ai essayé de relancer avec tous les graphismes au plus bas et le mode fenêtré, même problème.

**Comment by Hyslyne** [comment]
![20200307_225512](https://user-images.githubusercontent.com/60525061/76153049-d9ace800-60c6-11ea-81cf-ab6ba3e273c0.jpg)

**Comment by Hyslyne** [comment]
D'ailleurs maintenant que j'y repense, le livre des statistiques était super lent et ça me montrait plus tous mes accessoires ( ça en montrait que certains et les cadres étaient comme dézoomés ). Pareil, là je me demande si c'est pas parce que j'ai rajouté énormément de niveaux aux accessoires^^ ( je devais approcher des niveaux 20 )

**Comment by Simon-Lessard** [comment]
Je me demande si c'est pas le même souci que j'ai eu sur #897, ton screenshot en haut au centre me fait penser que oui.

**Comment by Neelan22** [comment]
Hyslyne, je suis désolée pour ta partie. Pour le moment, nous ne conseillons pas aux joueurs de jouer en mode infini. Le jeu comporte des bugs malheureusement, et un mode infini ne peut que permettre de les accumuler :(
Si tu pouvais nous envoyer ta sauvegarde, ça nous aiderait beaucoup pour corriger ce bug car nous n'arrivons pas à le reproduire de notre coté.
Pour trouver la sauvegarde : 
PC :
C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster University
Mac :
~/Library/Application Support/Sneaky Yak Studio/Spellcaster University/Saves

**Comment by Hyslyne** [comment]
Comment je vous l'envoie ?
" We don’t support that file type. Try again with a GIF, JPEG, JPG, PNG, DOCX, GZ, LOG, PDF, PPTX, TXT, XLSX or ZIP. "

**Comment by Hyslyne** [comment]
[save.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/4308043/save.zip) Voilà voilà

**Comment by Neelan22** [comment]
Merci beaucoup pour ta sauvegarde, nous avons pu corriger ton problème dans le hot fix d'hier soir
