### ISSUE TITLE
Molette souris zoome et scroll à la fois

### ISSUE THREAD

**Issue by jeremy-boes** [JulienNigon/SpellcasterUniversity-Bug-Report#91]
Dans le menu où je regarde ma classe, il y a un ascenseur sur la droite. Si je scrolle avec la molette souris, ça scrolle un peu, mais surtout ça zoome sur le décor derrière.

![screen](https://user-images.githubusercontent.com/42269011/51088810-c2919500-1764-11e9-8593-ee5f1d1cb45a.png)

**Comment by jeremy-boes** [comment]
Tiens d'ailleurs je remarque que le curseur de la souris n'apparaît pas sur le screenshot (il était positionné sur un des élèves).

**Comment by JulienNigon** [comment]
Tu as fait le screenshot via steam?

**Comment by jeremy-boes** [comment]
> Tu as fait le screenshot via steam?

Nope, je l'ai fait à l'ancienne : print screen + paint.

**Comment by JulienNigon** [comment]
Et voilà. On peut dire au revoir à un des plus vieux bugs de Spellcaster University. Cela fait un moment qu'il m'accompagne. Il me manquera.
