### ISSUE TITLE
Musique qui s'arrête ne redémarre pas lorsqu'on est dans un menu

### ISSUE THREAD

**Issue by jeremy-boes** [JulienNigon/SpellcasterUniversity-Bug-Report#92]
Le temps que je fasse le ticket précédent, la musique s'est arrêtée et n'a pas redémarré tant que je n'ai pas fermé le menu.

**Comment by JulienNigon** [comment]
Ce point est désormais considéré comme une fonction normale du jeu :). Chaque jour/nuit joue une musique et si elle fini avant la fin on garde un blanc pour souffler.
