### ISSUE TITLE
problème d'étudiant bloqué à cause de la santé mentale

### ISSUE THREAD

**Issue by fbarthe** [JulienNigon/SpellcasterUniversity-Bug-Report#929]
Bonjour!

![image](https://user-images.githubusercontent.com/13238808/76689520-0452ef80-6637-11ea-9f6b-74008356c41f.png)

Mes étudiants tournent en rond à l'infini avec leur santé mentale vidée :-(

**Comment by Neelan22** [comment]
arg #722 #747 #752 #777
merci pour le retour
Est il possible de nous envoyer la sauvegarde stp?
Pour la trouver :
PC : C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster University
Mac : ~/Library/Application Support/Sneaky Yak Studio/Spellcaster University/Saves

**Comment by fbarthe** [comment]
Bonjour,

la voici! bon courage
[save.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/4342133/save.zip)

**Comment by Neelan22** [comment]
merci beaucoup ! Le bug reste après un rechargement de jeu?

**Comment by fbarthe** [comment]
oui malheureusement , c'est la première action que j'ai essayé :(

**Comment by Neelan22** [comment]
mince :/
merci pour la sauvegarde, ça va bien nous aider.

**Comment by JulienNigon** [comment]
La correction est faite. Elle sera déployée dans la prochaine mise à jour.
Un grand merci pour cette sauvegarde qui fut instrumentale dans la correction !
