### ISSUE TITLE
Divers problème lorsqu'on déplace la vue vers les extrémités

### ISSUE THREAD

**Issue by jeremy-boes** [JulienNigon/SpellcasterUniversity-Bug-Report#93]
Plusieurs cas :  
- la vue est bloquée par un élément, par exemple en allant tout à gauche et dézoomé à fond 
![screen](https://user-images.githubusercontent.com/42269011/51088902-ddb0d480-1765-11e9-8b9b-5222c6d8b7d2.png)
- glitch graphique (en maintenant flèche de gauche et flèche du bas depuis le screen précédent)
![screen](https://user-images.githubusercontent.com/42269011/51088934-0cc74600-1766-11e9-9bf0-22b9567fa957.png)
- on voit le bord du décor et des morceaux de "vide" dans le fond en allant vers le haut, par exemple sur le screenshot suivant, la coupure verticale à gauche de la montagne. Et on voit aussi que le décor flotte dans le vide et qu'il n'y a rien entre les montagnes de l'arrière-plan et le lac (et aussi j'ai ouvert le menu cheat mode sans faire exprès je ne sais pas trop comment, ni comment le fermer)
![screen](https://user-images.githubusercontent.com/42269011/51088972-79dadb80-1766-11e9-8164-b123a952f98a.png)

**Comment by FlynFlykk** [comment]
rectification de la box de la camera et du terrain pour ne plus voir l'envers du decors
