### ISSUE TITLE
Bug affichage graphique sur map falaise

### ISSUE THREAD

**Issue by axelexi** [JulienNigon/SpellcasterUniversity-Bug-Report#930]
La map falaise ne s'affiche pas correctement (texture non chargée et éléments non visibles (cartes, école,...).

**Comment by Neelan22** [comment]
mince!
ça reste même après un redémarrage d'ordinateur (système D)?
Si oui, peux tu nous envoyer la sauvegarde stp?
Pour la trouver :
PC : C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster University
Mac : ~/Library/Application Support/Sneaky Yak Studio/Spellcaster University/Saves

**Comment by axelexi** [comment]
> La map falaise ne s'affiche pas correctement (texture non chargée et éléments non visibles (cartes, école,...).

Erratum de ma part. En fait il s'agit de ma carte graphique ou ma RAM qui est en PLS même en qualité "fastest"...

**Comment by Neelan22** [comment]
ok :/
