### ISSUE TITLE
Problème avec l'infirmerie/Elèves et professeurs parfois bloqués

### ISSUE THREAD

**Issue by Saunyk** [JulienNigon/SpellcasterUniversity-Bug-Report#957]
Bonjour

D'abord,je tiens à vous dire que ce jeu est super.

En ce qui concerne l'infirmerie,les élèves semblent l’utiliser plutôt pour dormir,pire encore elle ne remonte pas les points de vie des élèves (mais étrangement remonte leur santé mentale).J'ai suivi un élève à la santé basse juste pour voir la vitesse de récupération de PV avec un prof de pédagogie correcte et j'ai été très surpris.Cela rend la carte des montagnes assez dur car les élèves quittent constamment l'université.

Ensuite j'ai déjà vu des professeurs marcher sur place sans avancer ce qui rend la salle inutilisable puisque le prof essaye constamment de se rendre à la salle des profs pour réduire les barres de fatigue et autres (il me semble).Cela s'est réglée tout seul une fois lorsque le prof voulait d'abord refermer le portail ouvert par un élève. Assez rare

Enfin de manière général,

*Premièrement un groupe entier d'élèves et de profs (5 à 8 personnes) se sont retrouvés bloqués mais en dirait que le problème venait du pégase qui se baladait et bloquait l'entrée d'une salle alors que plusieurs élèves voulait en sortir (l'entrée/sortie était trop petite je pense). Une seule fois dans la carte désert car je n'ai jamais eu de pégase sauf avec les djinns.

*Deuxièmement,ils arrivent que les personnages se bloquent sans raison comme s'il y avait un mur invisible. Très rare mais cela gâche mes campagnes surtout que cela arrive souvent au début des tableaux ce qui empêche donc la génération d'or et de mana et les forces du mal n'attendent pas.

Il y a d'autres bugs divers donc je ne me souviens plus mais on est encore en alpha alors je suppose que ce sera réglée à la sortie officiel du jeu.

Encore une fois,je tiens à vous remercier pour ce super jeu.J'attends avec impatience la version libre des bugs et si cela est prévu du nouveau contenu.

**Comment by Neelan22** [comment]
Bonjour Saunyk,
Nous avons travaillé sur l'infirmerie cette semaine, ses bugs sont corrigés et son rôle sera plus important. On sait qu'il y a un problème avec les profs qui se bloquent. On cherche le bug mais malheureusement (coté dev) il ne se conserve pas si on recharge le jeu, donc les joueurs ne peuvent pas nous envoyer la sauvegarde. Mais coté joueur c'est bien, car un rechargement suffit à corriger ça. Évidement, ça devra être corrigé pour la release officielle. Les "bouchons" entre les portes font un peu parti du jeu : il faut optimiser les passages dans le château pour éviter d'avoir tous les passages dans un même couloir. Le pégase comme le chienorc ne sont pas encore tout à fait implémentés. Quand ils seront prêts nous les ajouterons dans les decks. On n'aurait pas du les laisser dispo chez le djinn.
Merci beaucoup pour tes retours et ton soutien !
