### ISSUE TITLE
On peut zoomer à travers l'université

### ISSUE THREAD

**Issue by jeremy-boes** [JulienNigon/SpellcasterUniversity-Bug-Report#96]
Et en passant à travers ça fait des trucs bizarres, genre ça : 
![screen](https://user-images.githubusercontent.com/42269011/51089087-a2afa080-1767-11e9-8377-81c07739ec39.png)

Et ensuite c'est un peu fastidieux de dézoomer à la molette jusqu'à revenir à une vue normale (c'est lent).

En fait, en relation avec #93 aussi, peut-être qu'il faut une fonction "réinitialiser la vue".

**Comment by JulienNigon** [comment]
Pour l'instant je supprime la possibilité de passer à travers le mur du fond. Eviter d'entrer dans les objets 3D par contre ça soulève des questions d'ergonomies (passer d'une salle à une autre lorsque l'on zoom beaucoup deviens impossible à cause des murs).

Je fait une issue avec la possibilité de réinitialiser la vue, et je vais recalibrer la molette.
