### ISSUE TITLE
Unable to start the game anymore

### ISSUE THREAD

**Issue by fcaron68** [JulienNigon/SpellcasterUniversity-Bug-Report#965]
Hello,

I started playing this game last week and I was able to start and play.
But today, I tried to launch it with Steam but it didn't work : my computer display briefly this window. 
![image](https://user-images.githubusercontent.com/19267878/77783936-fd29d980-7059-11ea-8929-5c4e1562da35.png)

Here is the logfile created by the crash : 
-------------------------START OF LOG

Initialize engine version: 2018.1.0f2 (d4d99f31acba)
GfxDevice: creating device client; threaded=1
Crash!!!
SymInit: Symbol-SearchPath: '.;C:\Program Files (x86)\Steam\steamapps\common\Spellcaster University;C:\Program Files (x86)\Steam\steamapps\common\Spellcaster University;C:\WINDOWS;C:\WINDOWS\system32;SRV*C:\websymbols*http://msdl.microsoft.com/download/symbols;', symOptions: 530, UserName: 'MyUser'
OS-Version: 10.0.0
C:\Program Files (x86)\Steam\steamapps\common\Spellcaster University\Spellcaster University.exe:Spellcaster University.exe (00007FF6EB3F0000), size: 671744 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\steamapps\common\Spellcaster University\Spellcaster University.exe', fileVersion: 2018.1.0.55711
C:\WINDOWS\SYSTEM32\ntdll.dll:ntdll.dll (00007FF9776E0000), size: 2031616 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\ntdll.dll', fileVersion: 10.0.18362.719
C:\WINDOWS\System32\KERNEL32.DLL:KERNEL32.DLL (00007FF9774A0000), size: 729088 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\KERNEL32.DLL', fileVersion: 10.0.18362.329
C:\WINDOWS\System32\KERNELBASE.dll:KERNELBASE.dll (00007FF974F00000), size: 2764800 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\KERNELBASE.dll', fileVersion: 10.0.18362.719
C:\Program Files (x86)\Steam\steamapps\common\Spellcaster University\UnityPlayer.dll:UnityPlayer.dll (00007FF906E60000), size: 23281664 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\steamapps\common\Spellcaster University\UnityPlayer.dll', fileVersion: 2018.1.0.55711
C:\WINDOWS\System32\USER32.dll:USER32.dll (00007FF9757C0000), size: 1654784 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\USER32.dll', fileVersion: 10.0.18362.719
C:\WINDOWS\System32\win32u.dll:win32u.dll (00007FF974ED0000), size: 135168 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\win32u.dll', fileVersion: 10.0.18362.719
C:\WINDOWS\System32\GDI32.dll:GDI32.dll (00007FF9759E0000), size: 155648 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\GDI32.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\SYSTEM32\HID.DLL:HID.DLL (00007FF9731B0000), size: 57344 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\HID.DLL', fileVersion: 10.0.18362.1
C:\WINDOWS\System32\gdi32full.dll:gdi32full.dll (00007FF975450000), size: 1654784 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\gdi32full.dll', fileVersion: 10.0.18362.719
C:\WINDOWS\System32\msvcrt.dll:msvcrt.dll (00007FF9764B0000), size: 647168 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\msvcrt.dll', fileVersion: 7.0.18362.1
C:\WINDOWS\System32\msvcp_win.dll:msvcp_win.dll (00007FF975210000), size: 647168 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\msvcp_win.dll', fileVersion: 10.0.18362.387
C:\WINDOWS\System32\ucrtbase.dll:ucrtbase.dll (00007FF975330000), size: 1024000 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\ucrtbase.dll', fileVersion: 10.0.18362.387
C:\WINDOWS\System32\ole32.dll:ole32.dll (00007FF9765D0000), size: 1404928 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\ole32.dll', fileVersion: 10.0.18362.693
C:\WINDOWS\System32\combase.dll:combase.dll (00007FF975CA0000), size: 3366912 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\combase.dll', fileVersion: 10.0.18362.693
C:\WINDOWS\System32\RPCRT4.dll:RPCRT4.dll (00007FF976730000), size: 1179648 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\RPCRT4.dll', fileVersion: 10.0.18362.628
C:\WINDOWS\System32\bcryptPrimitives.dll:bcryptPrimitives.dll (00007FF9752B0000), size: 524288 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\bcryptPrimitives.dll', fileVersion: 10.0.18362.295
C:\WINDOWS\SYSTEM32\VERSION.dll:VERSION.dll (00007FF96FAA0000), size: 40960 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\VERSION.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\System32\advapi32.dll:advapi32.dll (00007FF976A20000), size: 667648 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\advapi32.dll', fileVersion: 10.0.18362.329
C:\WINDOWS\System32\sechost.dll:sechost.dll (00007FF975A10000), size: 618496 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\sechost.dll', fileVersion: 10.0.18362.693
C:\WINDOWS\System32\SHLWAPI.dll:SHLWAPI.dll (00007FF975B90000), size: 335872 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\SHLWAPI.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\System32\SETUPAPI.dll:SETUPAPI.dll (00007FF975FE0000), size: 4653056 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\SETUPAPI.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\System32\cfgmgr32.dll:cfgmgr32.dll (00007FF975740000), size: 303104 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\cfgmgr32.dll', fileVersion: 10.0.18362.387
C:\WINDOWS\System32\bcrypt.dll:bcrypt.dll (00007FF974670000), size: 155648 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\bcrypt.dll', fileVersion: 10.0.18362.267
C:\WINDOWS\System32\SHELL32.dll:SHELL32.dll (00007FF976C10000), size: 7229440 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\SHELL32.dll', fileVersion: 10.0.18362.719
C:\WINDOWS\System32\shcore.dll:shcore.dll (00007FF975BF0000), size: 692224 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\shcore.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\System32\windows.storage.dll:windows.storage.dll (00007FF9746A0000), size: 7864320 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\windows.storage.dll', fileVersion: 10.0.18362.719
C:\WINDOWS\System32\profapi.dll:profapi.dll (00007FF974640000), size: 143360 (result: 0), SymType: '-nosymbols-', PDB: 'C:\WINDOWS\System32\profapi.dll', fileVersion: 10.0.18362.693
C:\WINDOWS\System32\powrprof.dll:powrprof.dll (00007FF9745F0000), size: 303104 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\powrprof.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\System32\UMPDC.dll:UMPDC.dll (00007FF9745A0000), size: 65536 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\UMPDC.dll'
C:\WINDOWS\System32\kernel.appcore.dll:kernel.appcore.dll (00007FF9745B0000), size: 69632 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\kernel.appcore.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\System32\cryptsp.dll:cryptsp.dll (00007FF975430000), size: 94208 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\cryptsp.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\System32\WS2_32.dll:WS2_32.dll (00007FF977300000), size: 454656 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\WS2_32.dll', fileVersion: 10.0.18362.387
C:\WINDOWS\System32\OLEAUT32.dll:OLEAUT32.dll (00007FF975AC0000), size: 802816 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\OLEAUT32.dll', fileVersion: 10.0.18362.693
C:\WINDOWS\System32\IMM32.dll:IMM32.dll (00007FF975790000), size: 188416 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\IMM32.dll', fileVersion: 10.0.18362.387
C:\WINDOWS\SYSTEM32\OPENGL32.dll:OPENGL32.dll (00007FF9476D0000), size: 1400832 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\OPENGL32.dll', fileVersion: 10.0.18362.387
C:\WINDOWS\SYSTEM32\WINMM.dll:WINMM.dll (00007FF971DB0000), size: 147456 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINMM.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\SYSTEM32\DNSAPI.dll:DNSAPI.dll (00007FF973B60000), size: 827392 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\DNSAPI.dll', fileVersion: 10.0.18362.267
C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL:IPHLPAPI.DLL (00007FF973B20000), size: 237568 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL', fileVersion: 10.0.18362.1
C:\WINDOWS\SYSTEM32\WINHTTP.dll:WINHTTP.dll (00007FF96E7F0000), size: 987136 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINHTTP.dll', fileVersion: 10.0.18362.693
C:\WINDOWS\System32\NSI.dll:NSI.dll (00007FF975AB0000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\NSI.dll', fileVersion: 10.0.18362.449
C:\WINDOWS\SYSTEM32\GLU32.dll:GLU32.dll (00007FF949180000), size: 180224 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\GLU32.dll', fileVersion: 10.0.18362.387
C:\WINDOWS\SYSTEM32\WINMMBASE.dll:WINMMBASE.dll (00007FF971C80000), size: 184320 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\WINMMBASE.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\SYSTEM32\dxcore.dll:dxcore.dll (00007FF973210000), size: 131072 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\dxcore.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\system32\uxtheme.dll:uxtheme.dll (00007FF972590000), size: 626688 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\uxtheme.dll', fileVersion: 10.0.18362.449
C:\Program Files (x86)\Steam\steamapps\common\Spellcaster University\Mono\EmbedRuntime\mono.dll:mono.dll (00007FF92F7D0000), size: 3014656 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files (x86)\Steam\steamapps\common\Spellcaster University\Mono\EmbedRuntime\mono.dll', fileVersion: 1.0.0.1
C:\WINDOWS\System32\PSAPI.DLL:PSAPI.DLL (00007FF9759D0000), size: 32768 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\PSAPI.DLL', fileVersion: 10.0.18362.1
C:\WINDOWS\SYSTEM32\MSWSOCK.dll:MSWSOCK.dll (00007FF973E10000), size: 421888 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\MSWSOCK.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\System32\MSCTF.dll:MSCTF.dll (00007FF977560000), size: 1269760 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\MSCTF.dll', fileVersion: 10.0.18362.693
C:\WINDOWS\SYSTEM32\d3d11.dll:d3d11.dll (00007FF971F90000), size: 2469888 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\d3d11.dll', fileVersion: 10.0.18362.387
C:\WINDOWS\SYSTEM32\dxgi.dll:dxgi.dll (00007FF9732A0000), size: 962560 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\dxgi.dll', fileVersion: 10.0.18362.693
C:\WINDOWS\System32\DriverStore\FileRepository\nvam.inf_amd64_2dd4c250764257ac\nvldumdx.dll:nvldumdx.dll (00007FF919F80000), size: 974848 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\DriverStore\FileRepository\nvam.inf_amd64_2dd4c250764257ac\nvldumdx.dll', fileVersion: 25.21.14.2546
C:\WINDOWS\System32\crypt32.dll:crypt32.dll (00007FF9755F0000), size: 1347584 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\crypt32.dll', fileVersion: 10.0.18362.592
C:\WINDOWS\System32\MSASN1.dll:MSASN1.dll (00007FF9745D0000), size: 73728 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\MSASN1.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\System32\WINTRUST.DLL:WINTRUST.DLL (00007FF9751B0000), size: 376832 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\WINTRUST.DLL', fileVersion: 10.0.18362.387
C:\WINDOWS\System32\imagehlp.dll:imagehlp.dll (00007FF976850000), size: 118784 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\imagehlp.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\system32\rsaenh.dll:rsaenh.dll (00007FF973980000), size: 208896 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\rsaenh.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\SYSTEM32\CRYPTBASE.dll:CRYPTBASE.dll (00007FF973FE0000), size: 49152 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\CRYPTBASE.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\System32\DriverStore\FileRepository\nvam.inf_amd64_2dd4c250764257ac\nvwgf2umx.dll:nvwgf2umx.dll (00007FF917AB0000), size: 38547456 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\DriverStore\FileRepository\nvam.inf_amd64_2dd4c250764257ac\nvwgf2umx.dll', fileVersion: 25.21.14.2546
C:\WINDOWS\system32\nvspcap64.dll:nvspcap64.dll (00007FF9349F0000), size: 2887680 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\nvspcap64.dll', fileVersion: 3.20.0.105
C:\WINDOWS\SYSTEM32\ntmarta.dll:ntmarta.dll (00007FF973600000), size: 200704 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\ntmarta.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\System32\clbcatq.dll:clbcatq.dll (00007FF9773F0000), size: 663552 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\System32\clbcatq.dll', fileVersion: 2001.12.10941.16384
C:\WINDOWS\system32\wbem\wbemprox.dll:wbemprox.dll (00007FF960170000), size: 69632 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\wbem\wbemprox.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\SYSTEM32\wbemcomn.dll:wbemcomn.dll (00007FF9632C0000), size: 540672 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\wbemcomn.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\system32\wbem\wbemsvc.dll:wbemsvc.dll (00007FF960220000), size: 81920 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\wbem\wbemsvc.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\system32\wbem\fastprox.dll:fastprox.dll (00007FF95F910000), size: 1052672 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\system32\wbem\fastprox.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\SYSTEM32\amsi.dll:amsi.dll (00007FF961AF0000), size: 86016 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\amsi.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\SYSTEM32\USERENV.dll:USERENV.dll (00007FF9744C0000), size: 151552 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\USERENV.dll', fileVersion: 10.0.18362.387
C:\Program Files\McAfee\MfeAV\AMSIExt.dll:AMSIExt.dll (00007FF960510000), size: 606208 (result: 0), SymType: '-exported-', PDB: 'C:\Program Files\McAfee\MfeAV\AMSIExt.dll', fileVersion: 23.0.139.0
C:\WINDOWS\SYSTEM32\dbghelp.dll:dbghelp.dll (00007FF972ED0000), size: 2048000 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\dbghelp.dll', fileVersion: 10.0.18362.1
C:\WINDOWS\SYSTEM32\SspiCli.dll:SspiCli.dll (00007FF974490000), size: 192512 (result: 0), SymType: '-exported-', PDB: 'C:\WINDOWS\SYSTEM32\SspiCli.dll', fileVersion: 10.0.18362.1

========== OUTPUTTING STACK TRACE ==================

0x00007FF907F2013E (UnityPlayer) UnityMain
0x00007FF907F2CE39 (UnityPlayer) UnityMain
  ERROR: SymGetSymFromAddr64, GetLastError: 'Tentative d’accès à une adresse non valide.' (Address: 00007FF90792DF69)
0x00007FF90792DF69 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Tentative d’accès à une adresse non valide.' (Address: 00007FF90792E1F2)
0x00007FF90792E1F2 (UnityPlayer) (function-name not available)
0x00007FF90794F156 (UnityPlayer) UnityMain
0x00007FF90794AB06 (UnityPlayer) UnityMain
0x00007FF90796185C (UnityPlayer) UnityMain
  ERROR: SymGetSymFromAddr64, GetLastError: 'Tentative d’accès à une adresse non valide.' (Address: 00007FF9073CEBB0)
0x00007FF9073CEBB0 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Tentative d’accès à une adresse non valide.' (Address: 00007FF9073D0465)
0x00007FF9073D0465 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Tentative d’accès à une adresse non valide.' (Address: 00007FF90730642A)
0x00007FF90730642A (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Tentative d’accès à une adresse non valide.' (Address: 00007FF9072F76D9)
0x00007FF9072F76D9 (UnityPlayer) (function-name not available)
  ERROR: SymGetSymFromAddr64, GetLastError: 'Tentative d’accès à une adresse non valide.' (Address: 00007FF90793DCFA)
0x00007FF90793DCFA (UnityPlayer) (function-name not available)
0x00007FF90793E60B (UnityPlayer) UnityMain
  ERROR: SymGetSymFromAddr64, GetLastError: 'Tentative d’accès à une adresse non valide.' (Address: 00007FF6EB3F1207)
0x00007FF6EB3F1207 (Spellcaster University) (function-name not available)
0x00007FF9774B7BD4 (KERNEL32) BaseThreadInitThunk
0x00007FF97774CED1 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

A crash has been intercepted by the crash handler. For call stack and other details, see the latest crash report generated in:
 * C:/Users/MyUser/AppData/Local/Temp/Sneaky Yak Studio/Spellcaster University/Crashes
Could not load symbol mono_unity_lock_dynamic_function_access_tables64 : La procédure spécifiée est introuvable.

 
(Filename:  Line: 213)

Could not load symbol mono_unity_unlock_dynamic_function_access_tables64 : La procédure spécifiée est introuvable.

 
(Filename:  Line: 213)

-------------------------END OF LOG

More informations : 
- I didn't change anything in Steam between the two dates (when it was working and when it wasn't anymore)
- No software were installed

Thank you.

**Comment by Neelan22** [comment]
Thank you for the log, it will help us
and sorry for the bug, we will investigate

**Comment by fcaron68** [comment]
I tried to launch the game today and the game started ! An update was downloaded by Steam a few days ago : maybe it is this update that solved the problem.

Thank you for your support. I'm closing this issue.
