### ISSUE TITLE
Mélange anglais/français

### ISSUE THREAD

**Issue by jeremy-boes** [JulienNigon/SpellcasterUniversity-Bug-Report#97]
Il y a pas mal de texte français qui traîne, je reviendrai éditer au fur et à mesure que j'en trouve.
Pour l'instant ;
- le texte d'intro de la démo
- le statut "unionized" des profs

**Comment by JulienNigon** [comment]
Le texte d'introduction doit être changé de toute façon (je refait une issue en ce sens), et la syndicalisation est corrigée. Je ferme en attendant d'autres éventuels mélanges.
