### ISSUE TITLE
Elève qui se bloque en groupe

### ISSUE THREAD

**Issue by Fyndries** [JulienNigon/SpellcasterUniversity-Bug-Report#970]
Bonjour,

J'ai un petit bug sur quelques map, (souvent sur la tortue).
Des groupe d'élèves se forment et les élèves tournent en rond et sont bloqués dans cette boucle
![Sans titre](https://user-images.githubusercontent.com/62842823/77851770-26be3e80-71db-11ea-8ee5-5f9f0433ad17.png) 

comme sur la photo

**Comment by Neelan22** [comment]
merci, ce bug est corrigé, il sera effectif lors de la prochaine mise à jour :)
