### ISSUE TITLE
Quelques bugs trouvé ça et là au fil de mes parties

### ISSUE THREAD

**Issue by DrMerdock** [JulienNigon/SpellcasterUniversity-Bug-Report#972]
Bonjour,

Tout d'abord, je tenais à vous féliciter pour la réalisation de Spellcaster University, étant un amateur de jeux de gestion de ce type, j'ai vraiment adoré ce jeu et je dois tourner aux alentours de 70h dessus en une quinzaine de jours. Je me permet donc de vous contacter pour vous apporter un petit retour concernant quelques soucis rencontrés au cours de mes différentes parties :

- **Musiques chaotiques :** les musiques du jeu sont pour le moins chaotiques, se coupant/redémarrant assez aléatoirement, et à volume assez variable (parfois même au milieu d'une boucle).

- **Les fiches étudiantes miniatures :** Régulièrement, j'ai eu ce petit souci avec les fiches de nouveaux étudiants qui apparaissaient en miniature, il devient dès lors très compliqué de lire les caractéristiques des élèves pour les répartir dans les différentes maisons. La seule solution pour palier à ça que j'ai pu trouver, c'est de relancer le jeu, ce qui amène un autre petit souci dont je vous parle juste en dessous.

- **Caméra capricieuse au chargement d'une partie :** Lors d'un chargement de partie depuis le menu, ou simplement en cliquant sur le bouton "continuer [nom de l'école]", la caméra est figée sur place sur le centre de l'école et il est impossible de la déplacer avec la souris et je suis obligé d'utiliser le clavier pour déplacer la caméra où je le souhaite. Impossible également de zoomer/dézoomer la vue, ce qui enchaîne un autre petit problème que j'exposerai dans le point en dessous. Solution trouvée à ce jour en jeu : piocher des cartes dans les decks ou attendre qu'un événement pope pour l'activer et récupérer les mouvements de camera avec la souris.

- **Problème de placement pour les items du jeu :** Régulièrement (pour ne pas dire à chaque partie), quand la taille de l'école commence à devenir conséquente et que la camera est dézoomée au maximum, j'éprouve des soucis pour placer les différents items du jeu sur les emplacements adéquats. Je vois les zones s'afficher, mais pas devenir bleues pour valider la pose de l'objet, et de fait, je ne peux pas poser les objets, j'ai beau essayer de quadriller toute la zone de pose, impossible d'y arriver sans zoomer à mort sur la zone en question, et encore, régulièrement, ça ne passe pas. Comme pour d'autres soucis, j'ai parfois réussi à "solutionner" le problème en piochant des cartes/activant des événements/redémarrant le jeu, ce qui pose certains soucis, de nouveau, cf. le problème de camera.

- **Blocage du jeu :** Alors ici le problème ne m'est arrivé qu'une seule fois, mais j'avoue que j'ai eu peur pour la sauvegarde de ma campagne. J'avais sauvegardé et quitté le jeu en fin de partie, juste après la remise des diplômes, et lorsque je suis revenu sur le jeu, j'étais de nouveau à la remise des diplômes. Bon, en soi ce n'était pas vraiment un problème, juste un peu agaçant, quand on a 60/70 destins à valider, ça prend un peu de temps, mais une fois que j'avais terminé de valider tous les diplômes pour la seconde fois, donc, j'avais juste l'écran animé de l'école se faisant attaquer, mais plus aucun menu/bouton ou autre, tout avait disparu, et plus aucune touche ne fonctionnait, bouton escape compris, ce qui m'a obligé à quitter le jeu via windows et le relancer pour me retrouver une nouvelle fois juste avant la remise des diplômes de fin d'année. Pour éviter de me retrouver dans la même situation (et parce que j'en avais un peu marre, j'avoue), j'ai utilisé l'option "destin auto", ce qui n'est pas très optimisé en fin d'année dans une partie en plein milieu de campagne.

- **Élèves bloqués dans une pièce :** Le problème ne m'est arrivé qu'une seule fois jusqu'à présent, ou en tout cas je ne l'ai relevé qu'une seule fois, mais ça avait été assez handicapant dans ma partie pour vous le signaler. En gros, j'ai une bonne partie de mes élèves, et professeurs, qui se sont retrouvés à  tourner en rond dans une conciergerie. j'ai regardé quelques statuts et pensées des élèves, ça disait un truc du genre "où est le haut, où est le bas, ..." je n'ai plus la phrase exacte en tête. Du coup, avec tous ces élèves et profs bloqués là, ma génération de mana/argent était très fortement diminuée, pour ne pas dire quasi nulle.

- **Quelques fautes d'orthographe/de français :** Alors ici je ne pourrais plus dire précisément où je les ai croisé dans le jeu, mais j'avais relevé lors de plusieurs parties, quelques fautes dans les différents textes du jeu. Je ne suis clairement pas prof de français, mais si je peux vous proposer mon aide pour la correction de textes, ce serait avec plaisir. Au vu de la quantité de texte que comporte le jeu, c'est assez dérisoire, mais je me souviens qu'une ou deux fautes ainsi trouvées m'avaient sauté aux yeux quand je les ai croisé en lisant en diagonale.

Voilà voilà, ne vous méprenez pas, j'adore ce jeu et ces petits soucis, bien qu'assez rageants, ne m'empêchent pas de revenir très régulièrement sur celui-ci. Maintenant j'avoue qu'ils sont assez contraignants quand on veut streamer ou faire des vidéos sur le jeu, je m'éclate (et mes quelques viewers avec moi) sur ce jeu, mais j'ai parfois l'impression de passer mon temps à râler sur le jeu en live lorsque ces petits bugs se déclarent (le placement des objets en particulier), et ça m'attriste un peu parce que je trouve Spellcaster University tellement bien foutu et pensé que je ne voudrais pas lui faire une mauvaise com au lieu de convaincre les gens d'y jouer ! :)

D'avance, je vous remercie de votre attention, et vous souhaite une excellente fin de journée, je reste à votre disposition si vous avez des questions, ou besoin de précisions. Continuez comme ça, ce jeu est vraiment cool ! :)

Dr. Merdock

**Comment by Neelan22** [comment]
Bonjour Dr Merdock et merci pour tous ces retours
Nous savons que la musique est mal gérée, nous retravaillerons dessus quand nous aurons un peu de temps (il n'y a qu'un seul dev qui travaille sur le jeu).
Le bug des fiches est réglé dans la dernière MaJ, on attend les retours tous nos joueurs pour en être complètement sûrs.
Le bug de la caméra est un problème, nous avons eu d'autres retour sur ça. Nous essayons de le corriger. Des fois cela est du à d'autres appareils branchés (manettes par ex).
Jouer des items quand on est très dezoomé est inconfortable, nous essayons de trouver une solution à cela.
Pour le blocage du jeu j'ai une question : est ce que relancer le jeu a fait réapparaître les boutons pour continuer la partie? Pour info, nous avons un glitch à ce niveau là : tous les avenirs ont été re-comptabilisés. C'est comme si tu avais validé 2x plus d'avenirs à la fin de ce tableau.
Les élèves bloqués dans une classe ont aussi été corrigé dans la dernière mise à jour.
Malgré les relectures, nous trouvons encore des fautes... Nous avons deux joueurs qui se sont bien investis et qui nous ont beaucoup aidé. Normalement, avec la dernière mise à jour il y en a beaucoup moins.
Merci énormément pour ton soutien !

**Comment by DrMerdock** [comment]
Ok ok, j'imagine bien que ça doit être assez complexe, pas de souci, c'est pour ça que si je peux aider à mon niveau, c'est avec plaisir ! :)

Alors personnellement, je n'ai rien de branché, juste clavier/souris (bon, micro, casque, écrans, etc), et jusqu'à maintenant, c'est systématique quand on continue une partie/campagne, je vérifierai ça dans les prochains jours.

Alors j'ai alt/F4 pour pouvoir redémarrer le jeu, et une fois revenu sur le menu, j'ai refait "continuer l'école", et je me suis retrouvé au même moment où il fallait que je redistribue les avenirs. Alors oui, les boutons étaient revenus, mais aucune idée de si le glitch que tu m'as communiqué avait été actif, j'avoue que j'ai vite fait "avenirs automatiques" pour éviter de me retrouver dans une boucle, je pourrai peut-être essayer de retester ça à l'occase pour vous envoyer les infos si j'arrive à le reproduire.
Toujours au niveau du Glitch de fin d'année, je m'étais posé la question de si ça cumulait les deux répartitions d'élèves ou pas, du coup j'ai confirmation que ça cumule effectivement.

Voilà voilà, si je trouve d'autres petits trucs à l'avenir je reviens vers vous, et si vous avez d'autres questions, n'hésitez pas, si je peux aider à mon niveau, c'est avec grand plaisir, j'adore ce jeu ! :)

**Comment by Neelan22** [comment]
super, merci bcp !

**Comment by Neelan22** [comment]
Je vais fermer cette issue pour plus de lisibilité sur le github, car il y a certains points qu'on a corrigé, d'autres qui évoluent avec les mises à jour. J'ai noté sur un autre document les points qu'ils nous restent à traiter. Merci beaucoup pour ton aide et n'hésites pas à réouvrir une autre issue si tu as de nouveaux bug.
