### ISSUE TITLE
Qui m'a piqué mon scriptorium runique (dialogue roi)

### ISSUE THREAD

**Issue by Sheitale** [JulienNigon/SpellcasterUniversity-Bug-Report#974]
Bonjour à vous,

Je début sur la mise à jour et j'adore ! Ce loup garou avec son petit museau et sa queue qui dandine quand il mange, c'est troooop mignon. Les nouveaux dialogues sur la cartes sont top et redonnent de l'intérêt alors que je commençais à me lasser. 
Bravo pour les idées, il me tarde de retourner à ma partie pour continuer mes découvertes.

Pour en venir au bug, lors du dialogue avec le roi, à un moment il demande le formulaire à la Astérix. Dans les propositions ensuite, il y en a une avec le scriptorium runique. J'en avais bien un, seulement, la proposition était grisée.

![image](https://user-images.githubusercontent.com/61354340/78173467-1961b800-7458-11ea-9d61-e24b8f9ff0cd.png)

Encore bravo pour toutes ces idées !!!

**Comment by Neelan22** [comment]
ah, merci pour le retour, on va regarder ça

**Comment by Neelan22** [comment]
corrigé pour la prochaine mise à jour :)
