### ISSUE TITLE
Ils ont menti dans leur dossier (recrutement Vampire, Loup)

### ISSUE THREAD

**Issue by Sheitale** [JulienNigon/SpellcasterUniversity-Bug-Report#975]
J'ai pioché une carte 5 nouveaux étudiants Loups (idem pour les Vampires). 

Tout en trépignant de contentement, je faisais mon marché parmi les étudiants lorsque j'en ai refusé un (avoir la truffe frétillante ne suffit pas à excuser la stupidité) et là... plus de loup ! Retour aux étudiants normaux... 

J'ai réessayé avec les Vampires en refusant le premier pour voir : même observation.

**Comment by Neelan22** [comment]
Bien vu. Oui, refuser un CV entraîne un bug qui retire le trait "loup garou" ou "vampire" sur les fiches suivantes. Nous corrigerons ça dans la prochaine maj.

**Comment by Sheitale** [comment]
Heu... Vous l'avez déjà changé ?!

Je me faisais violence pour accepter tous les premiers étudiants pour ne pas "gâcher" les trois ou quatre suivants et... j'ai sursauté de surprise en voyant que... après avoir refusé à regret un étudiant vampire stupide brute et bavard... le suivant été quand même un vampire !

Merci !!!

**Comment by JulienNigon** [comment]
Oui désolé on a oublié de prévenir, mais on a sorti un correctif.  C'était
quand même embêtant comme bug :)
