### ISSUE TITLE
Bug augmentation besoins profs

### ISSUE THREAD

**Issue by ParentPa** [JulienNigon/SpellcasterUniversity-Bug-Report#976]
Bonjour, 
Lors de ma dernière partie il y a eu un bug sur la prof de druidisme: dès qu'elle se mettait à son poste ses besoins augmentaient soudainement et en quelques secondes elle devait déjà retourner en salle des profs. Il n'y avait pas ce problème sur les autres profs donc c'est peut-être lié à la salle. 
J'avais mis un calendrier lunaire dans la salle mais je n'ai pas vu le bug assez tôt, donc je ne sais pas s'il est apparu avant ou après l'avoir mis.

Merci pour tout votre travail, votre jeu est super beau et très agréable à jouer!

**Comment by Neelan22** [comment]
Ah ! merci beaucoup. C'est probablement le bug qu'on a remarqué hier. On en sait un plus maintenant (on soupçonnait le calendrier lunaire, sans avoir beaucoup plus d'info)
