### ISSUE TITLE
Etudiant bloqué dans une pièce (foyer des élèves)

### ISSUE THREAD

**Issue by Kelepok** [JulienNigon/SpellcasterUniversity-Bug-Report#978]
Bonjour,

J'ai un étudiant qui reste bloqué dans le foyer des élèves (premier étage, juste au dessus de l'entrée dans la Forêt - voir [screen](https://zupimages.net/viewer.php?id=20/14/a7yu.png)).

Comme certains parlaient d'un save/load j'ai aussi tenté le coup mais il s'est juste retourné.

Je vois un balcon sur le côté, un bug car il tente d'y accéder ?

Cordialement,
Kelepok.

**Comment by Neelan22** [comment]
Bonjour,
si tu peux nous envoyer ta sauvegarde, ça nous aiderait grandement !
Pour la trouver c'est :
PC : C:\Users\user\AppData\LocalLow\Sneaky Yak Studio\Spellcaster University
Mac : ~/Library/Application Support/Sneaky Yak Studio/Spellcaster University/Saves
merci beaucoup !

**Comment by Kelepok** [comment]
Bonjour,

Je m'en doutais, la voilà.

[Saves.zip](https://github.com/JulienNigon/SpellcasterUniversity-Bug-Report/files/4475424/Saves.zip)

**Comment by Neelan22** [comment]
merci beaucoup !

**Comment by Neelan22** [comment]
ça nous a bien aidé, merci !
