### ISSUE TITLE
Éditer les classes

### ISSUE THREAD

**Issue by jeremy-boes** [JulienNigon/SpellcasterUniversity-Bug-Report#98]
Ce serait cool de pouvoir éditer ses classes (nom, blason, robe, etc) après leur création. Voire de pouvoir les supprimer aussi (après en avoir viré tous les élèves)

**Comment by JulienNigon** [comment]
Noms et robes modifiables. Le blason n'est pas à l'ordre du jour, mais conservé de côté. La suppression des salles hors celle de base est pour l'instant mis de côté.
