### ISSUE TITLE
Libellé "todo" monastère

### ISSUE THREAD

**Issue by alhuo-smile** [JulienNigon/SpellcasterUniversity-Bug-Report#981]
Dans le niveau du monastère, quand je vais parler au moine, le 3e choix est "T[le choix]ODO". Un "todo" oublié :)

Screenshot attaché
![todo](https://user-images.githubusercontent.com/24453667/78458513-48736600-76b2-11ea-8579-f2cbb5820300.png)

Version : 0.911 Singing Raccoon.

**Comment by Neelan22** [comment]
effectivement xD
merci !
