### ISSUE TITLE
Quelques petits bugs

### ISSUE THREAD

**Issue by ZobiTheBee** [JulienNigon/SpellcasterUniversity-Bug-Report#984]
Bonjour,

Top comme jeu ! Je viens de finir la campagne ^^
J'ai eu quelques petits bugs :
- Les perso qui se bloquent dans les murs (salle d'ombre et psychologue). Ca peut être un prof, des élèves ou des dragons. Ou même les 3 au même endroit :P
Un bouton "renvoyer au début de la carte" pourrait debugger en attendant que ceci ne survienne  plus.
- Payer les frais mensuels (profs) se fait instantanément, vant de cliquer dessus, mais on ne peut pas avoir de dette. Du coup ca peut avoir du bon.
- Quand on met des ingrédients dans le chaudron... Celui-ci se ferme en auto à chaque ajout. Ce n'est pas top de devoir l'ouvrir 3 fois pour ajouter les 3 ingrédients. **Fixed/Je n'avais pas vu**,  Si tu drag un ingrédient, ca ouvre le chaudron
- Si je laisse le jeu en alt+tab pendant longtemps (>30min), le jeu ram à mort. Il faut save / quit / load.
- De temps en temps et reprenant une partie le clique droit pour se déplacer le fonctionne pas, les avancés des missions peuvent aussi bugger (l'affichage de l'étoile).
- **Add** Quand tu choisis une carte, en la gardant cliquée, tu peux la jouer directement => Sauf si tu as rempli l'espace std des cartes et que tu dois scroll.
- **Add** Un prof s'est fait tué par les Orcs (dommage :( ), il a repop après un save/load
- **Add** Lors de la fin d'étude d'un élève, l'affichage des avenirs se fait mal si la liste est trop longue.

Petites notes :
- Ajouter un téléporteur, afin que les profs et élèves puissent aller d'un point à un autre de l'école. Ca pourrait être cool
- La quete de l'archimage me semble impossible ^^
- La MAJ et bien cool, les limites des batiments sont plus lisibles (serre / cochonier/...). Il faudrait ajouter la taille des salle sur les cartes / les passages possibles / "comment placer un belvedère (le meilleur batiement du jeu). **Fixed/Je n'avais pas vu**, ll y a la taille et si tu vois la porte au fond tu peux y accéder haut/bas, même principe pour le coté.
- Quel est le bonus d'amélioration d'un salle ? (Vaut il mieux avoir un cochonier lvl 3 et un lvl 1 ou bien 2 cochoniers lvl 2 ?)
- **Add** Que l'on puisse voir les places restantes d'artefacts dans une salle
- **Add** Avoir la vision de la réputation actuelle des factions lors d'un choix "Blabla -15 réputation avec les Orcs (actuellement 12)" par ex, ou bien pouvoir ouvrir la map avant de choisir. Ceci pourrait être entendu avec les bonus : si j'ai le bonus +20% golds, alors sur la carte pierre philosophale il y aurait "+500 golds (+100)"
- **Add** En fin de partie, demander validation lors des choix de bonus/malus. J'ai tellement peur de double cliquer pendant que je parcours les choix.
- **Add** Je n'ai pas trop utilisé les aptitudes de combats des élèves. C'est plutot rare que je me fight contre les Orcs/forces du mal. Vous pourriez ajouter à la fin des parties un combat avec tous les élèves (même ceux déjà partis) contre les forces du mal ! On perdrait toujours, mais il y aurait un score de dmg :) Et/Ou plus d’éventements random d'attaques / Invocations ratées
- **Add** Pour les map qui ont différents slots de constructions à la base injoignables, ajouter la carte "Pont" pour les rejoindre à différents niveaux
- **Add** Des évènements qui mettent en jeu différents anciens élèves. "John la fameux chasseur de dragon à terrassé GROSDRAGON le méchant. Aller fêter ca avec les paysans survivants (si carte alcool) +10 réputation. Vendre la tête au roi +100golds". "John le vendeur de drogue s'est fait attrapé. Payer sa caution pour sauver l'image de l'école -150or. C'était un mauvais élève -10 réputation. Implorer le roi..." :)

Je vous dis BRAVO ! C'est vraiment un super jeu ! Mon école "CORONA MAGIE" me fait passer un confinement agréable :)
J'y ai passé plus de 20h et il me reste encore pas mal de choses à voir ^^
![image](https://user-images.githubusercontent.com/63210876/78510652-3cad9f80-7797-11ea-969a-28b137624746.png)

Merci pour ce jeu !
**Add** Merci pour ce jeu !

**Comment by Loyssis** [comment]
Bonjour,
Je confirme avoir rencontrer les même genres de bugs qui sont cités plus haut. De plus j'ai eu par moment:
-un des professeur qui n'a pas de texture
-des cartes qui disparaissent sans être utilisées au moment d'être posées
-des cartes qui ne sont pas données notamment lors d'événements (remise de diplôme des élèves, et une fête en demande d'une sorte de miss Granger)
-des objets qui ont du mal à se placer sur leur emplacement lors du dépôt de la carte

Dans les implémentations je trouve les propositions de ZobiTheBee assez cool. Je rajouterai également la possibilité de voir ce que l'on possède déjà lors de la sélection d'un choix d'événement ou de carte (attributs, pendentifs, salles...)

**Comment by Sheitale** [comment]
> Payer les frais mensuels (profs) se fait instantanément, vant de cliquer dessus, mais on ne peut pas avoir de dette. Du coup ca peut avoir du bon.

Je l'ai toujours connu comme ça moi !

> Quand on met des ingrédients dans le chaudron... Celui-ci se ferme en auto à chaque ajout. Ce n'est pas top de devoir l'ouvrir 3 fois pour ajouter les 3 ingrédients.

Je crois que tu peux l'ouvrir en cliquant sur le chaudron en bas juste à gauche des cartes de manas. 
Par l'intermédiaire des cartes, c'est peut-être juste la dépose rapide !

> -des cartes qui disparaissent sans être utilisées au moment d'être posées

Il me semble qu'il y a des cartes accessoires comme la ramure de cerf, les cornes de démons, l'auréole, les ailes, les amulettes ou les bâtons qui se consument quand tu les actives et qui provoque un effet directement sur les élèves. 
Tu ne parles pas de celles-là ?

Je dis ça... Heu... Parce que je passais pas là... 
*Cours se cacher en rougissant pour laisser les pros faire leur boulot*

**Comment by Loyssis** [comment]
Merci pour l'astuce du chaudron, je n'avais pas vu.
Par contre la les cartes qui disparaissent de base que tu mentionnes, il n'y a pas de soucis. Je parle d'un objet physique ou un animal. Cela s'est passé plusieurs fois et je me rappel surtout d'un serpent manavore que j'avais anticiper pour un étage et qui s'est volatilisé.
Merci de passer, c'est toujours bien de pouvoir échanger.

**Comment by Neelan22** [comment]
Les bugs de Zobi sont connus, nous devons nous y atteler. Pour le remarques, nous avons en projet de  faire des téléporteurs. Monter le niveau d'une salle améliorer son efficacité de 10%. Augmenter le niveau d'une salle ou construire une nouvelle dépend du nombre d'élève et de la position de la salle dans le chateau, c'est au joueur de décider quelle est la meilleure solution. Nous ajouterons + d'info bulles dans les prochaines mises à jour.
Les bugs de Loyssis sont étonnant et on en a jamais entendu parlé. Ca sent les bugs nul ultra rares. On va se noter ça dans un coin. Le serpent manavore qui disparait ne nous plait vraiment pas :(

**Comment by Loyssis** [comment]
Alors si c'est rare ça reste une bonne nouvelle. A voir car j'ai refait d'autres parties et cela ne s'est pas reproduit. Si je me souvient un minimum des choses, c'était lors d'une campagne bien avancée. J'avait déjà beaucoup d'éléments affichés. Cela ne ramait pas du tout, ou très peu (fps stables). J'avait dans la centaine d'éléments mouvant affichés car pas loin de 100 étudiant, plus les profs et les animaux. J'était dans le niveau de la forêt et papy troll n'a pas été content, donc une attaque d'orcs (avec le malus qui rajoute des combattants) était en train de se produire ou venait de se finir. J'ai essayé de posé le manavore à ce moment là. Si cela peut aider...

**Comment by Neelan22** [comment]
merci beaucoup pour les précisions !

**Comment by Neelan22** [comment]
Merci beaucoup pour tous vos retours. Dans un souci de clarté, j'ai noté tous vos retours dans un document annexe et je vais fermer cette issue qui contient beaucoup d'info, bugs, suggestions (Il y en a beaucoup qui sont redondant avec d'autres issues).
N’hésitez pas à faire d'autres issues si vous avez de nouveau bugs.
