### ISSUE TITLE
Les composants et potions génèrent du prestige quand utilisés

### ISSUE THREAD

**Issue by allikrid** [JulienNigon/SpellcasterUniversity-Bug-Report#987]
J'ai pu générer plus de 1700 prestige de cette manière sur ma première partie de campagne.
[https://steamcommunity.com/sharedfiles/filedetails/?id=2050953738](url)

**Comment by Neelan22** [comment]
C'est pas gentil d'essayer de casser notre jeu !

Le lien ne marche pas mais de ce que j'ai pu lire sur le hub Steam ça viendrait de la salle des trophées. On va retoucher 2-3 trucs dessus. Pour le moment nous avons revu la génération de composants, qui devrait être bien plus raisonnable.
