### ISSUE TITLE
Salle des trophées + générateur d'ingrédients = game breaking (et divers)

### ISSUE THREAD

**Issue by ghost** [JulienNigon/SpellcasterUniversity-Bug-Report#995]
**Un mot de remerciement d'abord** pour ce très beau jeu. Je l'ai trouvé prenant
J'ai commencé une liste de remarques et suggestions après 37 heures de jeu, mais je viens aujourd'hui après la màj introduisant la salle des trophées car le problème est plutôt sérieux.

C'est très simple : il suffit de placer un générateur d'ingrédients du type "composantes rituelles" dans une salle des trophées bien placée et c'est le déluge d'ingrédients, donc de potions, de prestige et de mana.

J'ai pu atteindre ainsi 1080 de prestige pépère en partie normale, marathon, 17e année, map du volcan. J'ai produit plus de 48000 de mana de lumière alors que ce n'était pas mon focus. A la fin, en vitesse lente, **un ingrédient popait toutes les secondes littéralement** - ce qui était d'ailleurs fastidieux à gérer (ce qui me fait d'ailleurs penser : ce serait bien pratique de créer automatiquement une potion en cliquant sur son nom dans le menu, pourvu que les ingrédients soient dans le deck).

Pour la map finale sur la tortue, j'ai remporté la victoire en moins de 4 ans, **avec la progression du Seigneur réduite à 0** après avoir spammé le soutien des Orcs. J'ai eu un peu de chance : j'ai pu obtenir 4 salles des trophées, dont deux équipées d'un ou deux générateurs d'ingrédients chacune.

J'imagine que ce n'était pas l'intention initiale. J'aime beaucoup le concept des salles de trophées, cela accentue le besoin d'optimisation dans le placement des salles et, pour moi qui aime avoir des élèves touche-à-tout, c'est un vrai plaisir. Mais on ne peut évidemment pas continuer ainsi.

Parmi les solutions possibles : limiter le placement de générateur d'ingrédients dans la salle des trophées, l'empêcher carrément ou limiter le nombre de salle des trophées. Faire en sorte que l'utilisation de cartes d'ingrédients ou de potion ne génère pas de prestige ne suffira malheureusement pas à résoudre le problème.

Merci encore et bon courage dans le développement.
Signé : un prof IRL :)

**Comment by Neelan22** [comment]
Merci beaucoup pour les retours !
Nous avons effectivement pu voir le monstre que nous avions créé :o 
Nous avons prévu de modifier légèrement le fonctionnement de la salle des trophées (tout en gardant l'idée des effets sur les salles orthogonales). 
Pour la prochaine mise à jour, nous avons revu l'algorithme qui génère les composants, ça devrait être plus raisonnable :)
